//! This code was AUTOGENERATED using the Codama library.

use {
    carbon_core::{
        clickhouse::{
            rows::{deterministic_event_id, ClickHouseRow, ClickHouseRowContext, ClickHouseTable},
            ClickHouseColumnDefinition, ClickHouseManagedTable,
        },
        instruction::InstructionMetadata,
    },
    chrono::{DateTime, Utc},
};

#[derive(Debug, Clone, serde::Serialize)]
pub struct BestSwapOutAmountViolationEventClickHouseRow {
    pub program_id: String,
    pub family_name: String,
    pub event_type: String,
    pub event_id: String,
    pub slot: u64,
    pub signature: String,
    pub instruction_index: u32,
    pub stack_height: u32,
    pub absolute_path: Vec<u8>,
    pub event_seq: u32,
    pub source_name: String,
    pub mode: String,
    pub decoder_version: String,
    pub ingest_ts: String,
    pub chain_time: Option<String>,
    pub partition_time: String,
    pub block_hash: Option<String>,
    pub tx_index: Option<u64>,
    pub expected_out_amount: u64,
    pub out_amount: u64,
}

impl BestSwapOutAmountViolationEventClickHouseRow {
    pub const FAMILY_NAME: &'static str = "jupiter_swap_best_swap_out_amount_violation";
    pub const EVENT_TYPE: &'static str = "best_swap_out_amount_violation";
    pub const DEFAULT_TABLE_NAME: &'static str =
        "jupiter_swap_best_swap_out_amount_violation_landing";

    pub fn from_parts(
        source: crate::events::best_swap_out_amount_violation::BestSwapOutAmountViolationEvent,
        metadata: &InstructionMetadata,
        context: &ClickHouseRowContext,
    ) -> Self {
        let _ = &source;
        let ingest_ts = Utc::now();
        let chain_time = metadata
            .transaction_metadata
            .block_time
            .and_then(DateTime::<Utc>::from_timestamp_secs);
        let partition_time = chain_time.unwrap_or(ingest_ts);
        let signature = metadata.transaction_metadata.signature.to_string();
        let event_seq = 0u32;

        Self {
            program_id: crate::PROGRAM_ID.to_string(),
            family_name: Self::FAMILY_NAME.to_string(),
            event_type: Self::EVENT_TYPE.to_string(),
            event_id: deterministic_event_id(
                crate::PROGRAM_ID.as_ref(),
                &signature,
                &metadata.absolute_path,
                Self::EVENT_TYPE,
                event_seq,
            ),
            slot: metadata.transaction_metadata.slot,
            signature,
            instruction_index: metadata.index,
            stack_height: metadata.stack_height,
            absolute_path: metadata.absolute_path.clone(),
            event_seq,
            source_name: context.source_name.clone(),
            mode: context.mode.clone(),
            decoder_version: context.decoder_version.clone(),
            ingest_ts: format_datetime(ingest_ts),
            chain_time: chain_time.map(format_datetime),
            partition_time: format_datetime(partition_time),
            block_hash: metadata
                .transaction_metadata
                .block_hash
                .map(|hash| hash.to_string()),
            tx_index: metadata.transaction_metadata.index,
            expected_out_amount: source.expected_out_amount,
            out_amount: source.out_amount,
        }
    }
}

impl ClickHouseTable for BestSwapOutAmountViolationEventClickHouseRow {
    fn table() -> &'static str {
        Self::DEFAULT_TABLE_NAME
    }

    fn columns() -> Vec<&'static str> {
        vec![
            "program_id",
            "family_name",
            "event_type",
            "event_id",
            "slot",
            "signature",
            "instruction_index",
            "stack_height",
            "absolute_path",
            "event_seq",
            "source_name",
            "mode",
            "decoder_version",
            "ingest_ts",
            "chain_time",
            "partition_time",
            "block_hash",
            "tx_index",
            "expected_out_amount",
            "out_amount",
        ]
    }

    fn create_table_sql(table_name: &str) -> String {
        let engine = Self::clickhouse_engine(table_name);
        Self::create_table_sql_for(table_name, &engine, true)
    }
}

impl BestSwapOutAmountViolationEventClickHouseRow {
    pub fn migration_operations(table_name: &str) -> Vec<String> {
        let mut operations = Vec::new();
        operations.push(Self::create_table_sql(table_name));
        operations.extend(Self::add_column_sql(table_name));
        operations
    }

    pub fn managed_tables(table_name: &str) -> Vec<ClickHouseManagedTable> {
        let engine = Self::clickhouse_engine(table_name);
        vec![Self::managed_table_for(
            table_name,
            Self::create_table_sql(table_name),
            engine,
            true,
        )]
    }

    fn managed_table_for(
        table_name: &str,
        create_table_sql: String,
        engine: String,
        include_merge_tree_layout: bool,
    ) -> ClickHouseManagedTable {
        ClickHouseManagedTable {
            name: table_name.to_string(),
            create_table_sql,
            drop_table_sql: format!("DROP TABLE IF EXISTS {table_name}"),
            engine: Some(Self::clickhouse_engine_name(&engine)),
            partition_by: include_merge_tree_layout
                .then(|| r#"toYear(partition_time)"#.to_string()),
            order_by: include_merge_tree_layout
                .then(|| r#"(program_id, family_name, event_id, slot)"#.to_string()),
            columns: Self::column_definitions(table_name),
        }
    }

    pub fn add_column_sql(table_name: &str) -> Vec<String> {
        vec![
            format!("ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS program_id String"),
            format!("ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS family_name String"),
            format!("ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS event_type String"),
            format!("ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS event_id String"),
            format!("ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS slot UInt64"),
            format!("ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS signature String"),
            format!("ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS instruction_index UInt32"),
            format!("ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS stack_height UInt32"),
            format!("ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS absolute_path Array(UInt8)"),
            format!("ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS event_seq UInt32"),
            format!("ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS source_name String"),
            format!("ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS mode String"),
            format!("ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS decoder_version String"),
            format!("ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS ingest_ts DateTime64(3, 'UTC')"),
            format!("ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS chain_time Nullable(DateTime64(3, 'UTC'))"),
            format!("ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS partition_time DateTime64(3, 'UTC')"),
            format!("ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS block_hash Nullable(String)"),
            format!("ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS tx_index Nullable(UInt64)"),
            format!("ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS expected_out_amount UInt64"),
            format!("ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS out_amount UInt64"),
        ]
    }

    pub fn column_definitions(table_name: &str) -> Vec<ClickHouseColumnDefinition> {
        vec![
            ClickHouseColumnDefinition {
                name: "program_id".to_string(),
                clickhouse_type: r#"String"#.to_string(),
                add_column_sql: format!("ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS program_id String"),
                modify_column_sql: format!("ALTER TABLE {table_name} MODIFY COLUMN program_id String"),
            },
            ClickHouseColumnDefinition {
                name: "family_name".to_string(),
                clickhouse_type: r#"String"#.to_string(),
                add_column_sql: format!("ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS family_name String"),
                modify_column_sql: format!("ALTER TABLE {table_name} MODIFY COLUMN family_name String"),
            },
            ClickHouseColumnDefinition {
                name: "event_type".to_string(),
                clickhouse_type: r#"String"#.to_string(),
                add_column_sql: format!("ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS event_type String"),
                modify_column_sql: format!("ALTER TABLE {table_name} MODIFY COLUMN event_type String"),
            },
            ClickHouseColumnDefinition {
                name: "event_id".to_string(),
                clickhouse_type: r#"String"#.to_string(),
                add_column_sql: format!("ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS event_id String"),
                modify_column_sql: format!("ALTER TABLE {table_name} MODIFY COLUMN event_id String"),
            },
            ClickHouseColumnDefinition {
                name: "slot".to_string(),
                clickhouse_type: r#"UInt64"#.to_string(),
                add_column_sql: format!("ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS slot UInt64"),
                modify_column_sql: format!("ALTER TABLE {table_name} MODIFY COLUMN slot UInt64"),
            },
            ClickHouseColumnDefinition {
                name: "signature".to_string(),
                clickhouse_type: r#"String"#.to_string(),
                add_column_sql: format!("ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS signature String"),
                modify_column_sql: format!("ALTER TABLE {table_name} MODIFY COLUMN signature String"),
            },
            ClickHouseColumnDefinition {
                name: "instruction_index".to_string(),
                clickhouse_type: r#"UInt32"#.to_string(),
                add_column_sql: format!("ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS instruction_index UInt32"),
                modify_column_sql: format!("ALTER TABLE {table_name} MODIFY COLUMN instruction_index UInt32"),
            },
            ClickHouseColumnDefinition {
                name: "stack_height".to_string(),
                clickhouse_type: r#"UInt32"#.to_string(),
                add_column_sql: format!("ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS stack_height UInt32"),
                modify_column_sql: format!("ALTER TABLE {table_name} MODIFY COLUMN stack_height UInt32"),
            },
            ClickHouseColumnDefinition {
                name: "absolute_path".to_string(),
                clickhouse_type: r#"Array(UInt8)"#.to_string(),
                add_column_sql: format!("ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS absolute_path Array(UInt8)"),
                modify_column_sql: format!("ALTER TABLE {table_name} MODIFY COLUMN absolute_path Array(UInt8)"),
            },
            ClickHouseColumnDefinition {
                name: "event_seq".to_string(),
                clickhouse_type: r#"UInt32"#.to_string(),
                add_column_sql: format!("ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS event_seq UInt32"),
                modify_column_sql: format!("ALTER TABLE {table_name} MODIFY COLUMN event_seq UInt32"),
            },
            ClickHouseColumnDefinition {
                name: "source_name".to_string(),
                clickhouse_type: r#"String"#.to_string(),
                add_column_sql: format!("ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS source_name String"),
                modify_column_sql: format!("ALTER TABLE {table_name} MODIFY COLUMN source_name String"),
            },
            ClickHouseColumnDefinition {
                name: "mode".to_string(),
                clickhouse_type: r#"String"#.to_string(),
                add_column_sql: format!("ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS mode String"),
                modify_column_sql: format!("ALTER TABLE {table_name} MODIFY COLUMN mode String"),
            },
            ClickHouseColumnDefinition {
                name: "decoder_version".to_string(),
                clickhouse_type: r#"String"#.to_string(),
                add_column_sql: format!("ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS decoder_version String"),
                modify_column_sql: format!("ALTER TABLE {table_name} MODIFY COLUMN decoder_version String"),
            },
            ClickHouseColumnDefinition {
                name: "ingest_ts".to_string(),
                clickhouse_type: r#"DateTime64(3, 'UTC')"#.to_string(),
                add_column_sql: format!("ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS ingest_ts DateTime64(3, 'UTC')"),
                modify_column_sql: format!("ALTER TABLE {table_name} MODIFY COLUMN ingest_ts DateTime64(3, 'UTC')"),
            },
            ClickHouseColumnDefinition {
                name: "chain_time".to_string(),
                clickhouse_type: r#"Nullable(DateTime64(3, 'UTC'))"#.to_string(),
                add_column_sql: format!("ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS chain_time Nullable(DateTime64(3, 'UTC'))"),
                modify_column_sql: format!("ALTER TABLE {table_name} MODIFY COLUMN chain_time Nullable(DateTime64(3, 'UTC'))"),
            },
            ClickHouseColumnDefinition {
                name: "partition_time".to_string(),
                clickhouse_type: r#"DateTime64(3, 'UTC')"#.to_string(),
                add_column_sql: format!("ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS partition_time DateTime64(3, 'UTC')"),
                modify_column_sql: format!("ALTER TABLE {table_name} MODIFY COLUMN partition_time DateTime64(3, 'UTC')"),
            },
            ClickHouseColumnDefinition {
                name: "block_hash".to_string(),
                clickhouse_type: r#"Nullable(String)"#.to_string(),
                add_column_sql: format!("ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS block_hash Nullable(String)"),
                modify_column_sql: format!("ALTER TABLE {table_name} MODIFY COLUMN block_hash Nullable(String)"),
            },
            ClickHouseColumnDefinition {
                name: "tx_index".to_string(),
                clickhouse_type: r#"Nullable(UInt64)"#.to_string(),
                add_column_sql: format!("ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS tx_index Nullable(UInt64)"),
                modify_column_sql: format!("ALTER TABLE {table_name} MODIFY COLUMN tx_index Nullable(UInt64)"),
            },
            ClickHouseColumnDefinition {
                name: "expected_out_amount".to_string(),
                clickhouse_type: r#"UInt64"#.to_string(),
                add_column_sql: format!("ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS expected_out_amount UInt64"),
                modify_column_sql: format!("ALTER TABLE {table_name} MODIFY COLUMN expected_out_amount UInt64"),
            },
            ClickHouseColumnDefinition {
                name: "out_amount".to_string(),
                clickhouse_type: r#"UInt64"#.to_string(),
                add_column_sql: format!("ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS out_amount UInt64"),
                modify_column_sql: format!("ALTER TABLE {table_name} MODIFY COLUMN out_amount UInt64"),
            },
        ]
    }

    fn clickhouse_engine(table_name: &str) -> String {
        let _ = table_name;
        format!("MergeTree")
    }

    fn clickhouse_engine_name(engine: &str) -> String {
        engine
            .split_once('(')
            .map(|(name, _)| name)
            .unwrap_or(engine)
            .to_string()
    }

    fn create_table_sql_for(
        table_name: &str,
        engine: &str,
        include_merge_tree_clauses: bool,
    ) -> String {
        let merge_tree_clauses = if include_merge_tree_clauses {
            " PARTITION BY toYear(partition_time) ORDER BY (program_id, family_name, event_id, slot)"
        } else {
            ""
        };
        format!(
            "CREATE TABLE IF NOT EXISTS {table_name} (\
            program_id String,\
            family_name String,\
            event_type String,\
            event_id String,\
            slot UInt64,\
            signature String,\
            instruction_index UInt32,\
            stack_height UInt32,\
            absolute_path Array(UInt8),\
            event_seq UInt32,\
            source_name String,\
            mode String,\
            decoder_version String,\
            ingest_ts DateTime64(3, 'UTC'),\
            chain_time Nullable(DateTime64(3, 'UTC')),\
            partition_time DateTime64(3, 'UTC'),\
            block_hash Nullable(String),\
            tx_index Nullable(UInt64),\
            expected_out_amount UInt64,\
            out_amount UInt64\
        ) ENGINE = {engine}{merge_tree_clauses}"
        )
    }
}

impl ClickHouseRow for BestSwapOutAmountViolationEventClickHouseRow {
    fn table_name(&self) -> &'static str {
        Self::table()
    }

    fn partition_key(&self) -> String {
        self.partition_time[..4].to_string()
    }
}

fn format_datetime(value: DateTime<Utc>) -> String {
    value.format("%Y-%m-%d %H:%M:%S%.3f").to_string()
}

#[allow(dead_code)]
fn clickhouse_enum_variant<T>(value: &T) -> String
where
    T: serde::Serialize + std::fmt::Debug + ?Sized,
{
    match serde_json::to_value(value) {
        Ok(serde_json::Value::String(variant)) => variant,
        Ok(serde_json::Value::Object(object)) if object.len() == 1 => object
            .into_iter()
            .next()
            .map(|(variant, _)| variant)
            .unwrap_or_default(),
        _ => clickhouse_debug_variant(value),
    }
}

#[allow(dead_code)]
fn clickhouse_debug_variant<T>(value: &T) -> String
where
    T: std::fmt::Debug + ?Sized,
{
    let debug = format!("{value:?}");
    debug
        .split(['(', ' ', '{'])
        .next()
        .unwrap_or_default()
        .to_string()
}
