//! This code was AUTOGENERATED using the Codama library.

#[allow(unused_imports)]
use carbon_core::clickhouse::rows::clickhouse_enum_variant;
use carbon_core::{
    clickhouse::{
        rows::{
            ClickHouseEventLandingMetadata, ClickHouseRowContext, CLICKHOUSE_EVENT_COMMON_COLUMNS,
        },
        ClickHouseColumnSpec,
    },
    instruction::InstructionMetadata,
};

#[derive(Debug, Clone, serde::Serialize)]
pub struct BestSwapOutAmountViolationEventClickHouseRow {
    #[serde(flatten)]
    pub metadata: ClickHouseEventLandingMetadata,
    pub expected_out_amount: u64,
    pub out_amount: u64,
}

impl BestSwapOutAmountViolationEventClickHouseRow {
    pub const FAMILY_NAME: &'static str = "jupiter_swap_best_swap_out_amount_violation";
    pub const EVENT_TYPE: &'static str = "best_swap_out_amount_violation";
    pub const DEFAULT_TABLE_NAME: &'static str =
        "jupiter_swap_best_swap_out_amount_violation_landing";
    pub const COMMON_COLUMNS: &'static [ClickHouseColumnSpec] = CLICKHOUSE_EVENT_COMMON_COLUMNS;
    pub const PAYLOAD_COLUMNS: &'static [ClickHouseColumnSpec] = &[
        ClickHouseColumnSpec::new("expected_out_amount", r#"UInt64"#),
        ClickHouseColumnSpec::new("out_amount", r#"UInt64"#),
    ];

    pub fn from_parts(
        source: crate::events::best_swap_out_amount_violation::BestSwapOutAmountViolationEvent,
        metadata: &InstructionMetadata,
        context: &ClickHouseRowContext,
    ) -> Self {
        let _ = &source;
        let event_seq = 0u32;

        Self {
            metadata: ClickHouseEventLandingMetadata::new(
                crate::PROGRAM_ID.as_ref(),
                crate::PROGRAM_ID.to_string(),
                Self::FAMILY_NAME,
                Self::EVENT_TYPE,
                event_seq,
                metadata,
                context,
            ),
            expected_out_amount: source.expected_out_amount,
            out_amount: source.out_amount,
        }
    }
}

carbon_core::impl_clickhouse_event_row!(
    BestSwapOutAmountViolationEventClickHouseRow,
    super::clickhouse_event_table_options
);
