//! This code was AUTOGENERATED using the Codama library.

#[allow(unused_imports)]
use carbon_core::clickhouse::rows::clickhouse_enum_variant;
use carbon_core::{
    clickhouse::{
        rows::{
            ClickHouseEventLandingMetadata, ClickHouseRowContext, CLICKHOUSE_EVENT_COMMON_COLUMNS,
        },
        ClickHouseColumnSpec,
    },
    instruction::InstructionMetadata,
};

#[derive(Debug, Clone, serde::Serialize)]
pub struct CandidateSwapQuoteErrorEventClickHouseRow {
    #[serde(flatten)]
    pub metadata: ClickHouseEventLandingMetadata,
    pub candidate_index: u64,
    pub in_amount: u64,
    pub error_code: u64,
}

impl CandidateSwapQuoteErrorEventClickHouseRow {
    pub const FAMILY_NAME: &'static str = "jupiter_swap_candidate_swap_quote_error";
    pub const EVENT_TYPE: &'static str = "candidate_swap_quote_error";
    pub const DEFAULT_TABLE_NAME: &'static str = "jupiter_swap_candidate_swap_quote_error_landing";
    pub const COMMON_COLUMNS: &'static [ClickHouseColumnSpec] = CLICKHOUSE_EVENT_COMMON_COLUMNS;
    pub const PAYLOAD_COLUMNS: &'static [ClickHouseColumnSpec] = &[
        ClickHouseColumnSpec::new("candidate_index", r#"UInt64"#),
        ClickHouseColumnSpec::new("in_amount", r#"UInt64"#),
        ClickHouseColumnSpec::new("error_code", r#"UInt64"#),
    ];

    pub fn from_parts(
        source: crate::events::candidate_swap_quote_error::CandidateSwapQuoteErrorEvent,
        metadata: &InstructionMetadata,
        context: &ClickHouseRowContext,
    ) -> Self {
        let _ = &source;
        let event_seq = 0u32;

        Self {
            metadata: ClickHouseEventLandingMetadata::new(
                crate::PROGRAM_ID.as_ref(),
                crate::PROGRAM_ID.to_string(),
                Self::FAMILY_NAME,
                Self::EVENT_TYPE,
                event_seq,
                metadata,
                context,
            ),
            candidate_index: source.candidate_index,
            in_amount: source.in_amount,
            error_code: source.error_code,
        }
    }
}

carbon_core::impl_clickhouse_event_row!(CandidateSwapQuoteErrorEventClickHouseRow);
