//! This code was AUTOGENERATED using the Codama library.

use carbon_core::clickhouse::rows::{
    deterministic_instruction_id, ClickHouseRow, ClickHouseRowContext, ClickHouseTable,
};
use carbon_core::instruction::InstructionMetadata;
use chrono::{DateTime, Utc};

#[derive(Debug, Clone, serde::Serialize)]
pub struct ClaimTokenInstructionClickHouseRow {
    pub program_id: String,
    pub family_name: String,
    pub instruction_type: String,
    pub instruction_id: String,
    pub slot: u64,
    pub signature: String,
    pub instruction_index: u32,
    pub stack_height: u32,
    pub absolute_path: Vec<u8>,
    pub source_name: String,
    pub mode: String,
    pub decoder_version: String,
    pub ingest_ts: String,
    pub chain_time: Option<String>,
    pub partition_time: String,
    pub block_hash: Option<String>,
    pub tx_index: Option<u64>,
    pub id: u8,
}

impl ClaimTokenInstructionClickHouseRow {
    pub const FAMILY_NAME: &'static str = "jupiter_swap_claim_token_instruction";
    pub const INSTRUCTION_TYPE: &'static str = "claim_token";
    pub const DEFAULT_TABLE_NAME: &'static str = "jupiter_swap_claim_token_instruction_landing";

    pub fn from_parts(
        source: crate::instructions::claim_token::ClaimToken,
        metadata: &InstructionMetadata,
        context: &ClickHouseRowContext,
    ) -> Self {
        let _ = &source;
        let ingest_ts = Utc::now();
        let chain_time = metadata
            .transaction_metadata
            .block_time
            .and_then(DateTime::<Utc>::from_timestamp_secs);
        let partition_time = chain_time.unwrap_or(ingest_ts);
        let signature = metadata.transaction_metadata.signature.to_string();

        Self {
            program_id: crate::PROGRAM_ID.to_string(),
            family_name: Self::FAMILY_NAME.to_string(),
            instruction_type: Self::INSTRUCTION_TYPE.to_string(),
            instruction_id: deterministic_instruction_id(
                crate::PROGRAM_ID.as_ref(),
                &signature,
                &metadata.absolute_path,
                Self::INSTRUCTION_TYPE,
            ),
            slot: metadata.transaction_metadata.slot,
            signature,
            instruction_index: metadata.index,
            stack_height: metadata.stack_height,
            absolute_path: metadata.absolute_path.clone(),
            source_name: context.source_name.clone(),
            mode: context.mode.clone(),
            decoder_version: context.decoder_version.clone(),
            ingest_ts: format_datetime(ingest_ts),
            chain_time: chain_time.map(format_datetime),
            partition_time: format_datetime(partition_time),
            block_hash: metadata
                .transaction_metadata
                .block_hash
                .map(|hash| hash.to_string()),
            tx_index: metadata.transaction_metadata.index,
            id: source.id,
        }
    }
}

impl ClickHouseTable for ClaimTokenInstructionClickHouseRow {
    fn table() -> &'static str {
        Self::DEFAULT_TABLE_NAME
    }

    fn columns() -> Vec<&'static str> {
        vec![
            "program_id",
            "family_name",
            "instruction_type",
            "instruction_id",
            "slot",
            "signature",
            "instruction_index",
            "stack_height",
            "absolute_path",
            "source_name",
            "mode",
            "decoder_version",
            "ingest_ts",
            "chain_time",
            "partition_time",
            "block_hash",
            "tx_index",
            "id",
        ]
    }

    fn create_table_sql(table_name: &str) -> String {
        let engine = Self::clickhouse_engine(table_name);
        Self::create_table_sql_for(table_name, &engine, true)
    }
}

impl ClaimTokenInstructionClickHouseRow {
    pub fn migration_operations(table_name: &str) -> Vec<String> {
        let mut operations = Vec::new();
        operations.push(Self::create_table_sql(table_name));
        operations.extend(Self::add_column_sql(table_name));
        operations
    }

    pub fn add_column_sql(table_name: &str) -> Vec<String> {
        vec![
            format!("ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS program_id String"),
            format!("ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS family_name String"),
            format!("ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS instruction_type String"),
            format!("ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS instruction_id String"),
            format!("ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS slot UInt64"),
            format!("ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS signature String"),
            format!("ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS instruction_index UInt32"),
            format!("ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS stack_height UInt32"),
            format!("ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS absolute_path Array(UInt8)"),
            format!("ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS source_name String"),
            format!("ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS mode String"),
            format!("ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS decoder_version String"),
            format!("ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS ingest_ts DateTime64(3, 'UTC')"),
            format!("ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS chain_time Nullable(DateTime64(3, 'UTC'))"),
            format!("ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS partition_time DateTime64(3, 'UTC')"),
            format!("ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS block_hash Nullable(String)"),
            format!("ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS tx_index Nullable(UInt64)"),
            format!("ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS id UInt8"),
        ]
    }

    fn clickhouse_engine(table_name: &str) -> String {
        let _ = table_name;
        format!("MergeTree")
    }

    fn create_table_sql_for(
        table_name: &str,
        engine: &str,
        include_merge_tree_clauses: bool,
    ) -> String {
        let merge_tree_clauses = if include_merge_tree_clauses {
            " PARTITION BY toYear(partition_time) ORDER BY (program_id, family_name, instruction_id, slot)"
        } else {
            ""
        };
        format!(
            "CREATE TABLE IF NOT EXISTS {table_name} (\
            program_id String,\
            family_name String,\
            instruction_type String,\
            instruction_id String,\
            slot UInt64,\
            signature String,\
            instruction_index UInt32,\
            stack_height UInt32,\
            absolute_path Array(UInt8),\
            source_name String,\
            mode String,\
            decoder_version String,\
            ingest_ts DateTime64(3, 'UTC'),\
            chain_time Nullable(DateTime64(3, 'UTC')),\
            partition_time DateTime64(3, 'UTC'),\
            block_hash Nullable(String),\
            tx_index Nullable(UInt64),\
            id UInt8\
        ) ENGINE = {engine}{merge_tree_clauses}"
        )
    }
}

impl ClickHouseRow for ClaimTokenInstructionClickHouseRow {
    fn table_name(&self) -> &'static str {
        Self::table()
    }

    fn partition_key(&self) -> String {
        self.partition_time[..4].to_string()
    }
}

fn format_datetime(value: DateTime<Utc>) -> String {
    value.format("%Y-%m-%d %H:%M:%S%.3f").to_string()
}

#[allow(dead_code)]
fn clickhouse_enum_variant<T>(value: &T) -> String
where
    T: serde::Serialize + std::fmt::Debug + ?Sized,
{
    match serde_json::to_value(value) {
        Ok(serde_json::Value::String(variant)) => variant,
        Ok(serde_json::Value::Object(object)) if object.len() == 1 => object
            .into_iter()
            .next()
            .map(|(variant, _)| variant)
            .unwrap_or_default(),
        _ => clickhouse_debug_variant(value),
    }
}

#[allow(dead_code)]
fn clickhouse_debug_variant<T>(value: &T) -> String
where
    T: std::fmt::Debug + ?Sized,
{
    let debug = format!("{value:?}");
    debug
        .split(|ch: char| ch == '(' || ch == '{' || ch.is_whitespace())
        .next()
        .unwrap_or_default()
        .to_string()
}
