//! This code was AUTOGENERATED using the Codama library.

#[allow(unused_imports)]
use carbon_core::clickhouse::rows::clickhouse_enum_variant;
use carbon_core::{
    clickhouse::{
        rows::{
            ClickHouseInstructionLandingMetadata, ClickHouseRowContext,
            CLICKHOUSE_INSTRUCTION_COMMON_COLUMNS,
        },
        ClickHouseColumnSpec,
    },
    instruction::InstructionMetadata,
};

#[derive(Debug, Clone, serde::Serialize)]
pub struct CloseTokenInstructionClickHouseRow {
    #[serde(flatten)]
    pub metadata: ClickHouseInstructionLandingMetadata,
    pub id: u8,
    pub burn_all: bool,
}

impl CloseTokenInstructionClickHouseRow {
    pub const FAMILY_NAME: &'static str = "jupiter_swap_close_token_instruction";
    pub const INSTRUCTION_TYPE: &'static str = "close_token";
    pub const DEFAULT_TABLE_NAME: &'static str = "jupiter_swap_close_token_instruction_landing";
    pub const COMMON_COLUMNS: &'static [ClickHouseColumnSpec] =
        CLICKHOUSE_INSTRUCTION_COMMON_COLUMNS;
    pub const PAYLOAD_COLUMNS: &'static [ClickHouseColumnSpec] = &[
        ClickHouseColumnSpec::new("id", r#"UInt8"#),
        ClickHouseColumnSpec::new("burn_all", r#"Bool"#),
    ];

    pub fn from_parts(
        source: crate::instructions::close_token::CloseToken,
        metadata: &InstructionMetadata,
        context: &ClickHouseRowContext,
    ) -> Self {
        let _ = &source;

        Self {
            metadata: ClickHouseInstructionLandingMetadata::new(
                crate::PROGRAM_ID.as_ref(),
                crate::PROGRAM_ID.to_string(),
                Self::FAMILY_NAME,
                Self::INSTRUCTION_TYPE,
                metadata,
                context,
            ),
            id: source.id,
            burn_all: source.burn_all,
        }
    }
}

carbon_core::impl_clickhouse_instruction_row!(
    CloseTokenInstructionClickHouseRow,
    super::clickhouse_instruction_table_options
);
