//! This code was AUTOGENERATED using the Codama library.

use carbon_core::{
    clickhouse::rows::{
        deterministic_event_id, ClickHouseRow, ClickHouseRowContext, ClickHouseTable,
    },
    instruction::InstructionMetadata,
};
use chrono::{DateTime, Utc};

#[derive(Debug, Clone, serde::Serialize)]
pub struct ClickHouseSwapEventV2 {
    pub input_mint: String,
    pub input_amount: u64,
    pub output_mint: String,
    pub output_amount: u64,
}

impl Default for ClickHouseSwapEventV2 {
    fn default() -> Self {
        Self {
            input_mint: String::new(),
            input_amount: 0,
            output_mint: String::new(),
            output_amount: 0,
        }
    }
}

impl From<&crate::types::SwapEventV2> for ClickHouseSwapEventV2 {
    fn from(value: &crate::types::SwapEventV2) -> Self {
        Self {
            input_mint: value.input_mint.to_string(),
            input_amount: value.input_amount,
            output_mint: value.output_mint.to_string(),
            output_amount: value.output_amount,
        }
    }
}

#[derive(Debug, Clone, serde::Serialize)]
pub struct ClickHouseCandidateSwapResult {
    pub variant: String,
    pub value_0: Option<u64>,
}

impl ClickHouseCandidateSwapResult {
    fn new(variant: String) -> Self {
        Self {
            variant,
            value_0: None,
        }
    }
}

impl Default for ClickHouseCandidateSwapResult {
    fn default() -> Self {
        Self::new("OutAmount".to_string())
    }
}

impl From<&crate::types::CandidateSwapResult> for ClickHouseCandidateSwapResult {
    fn from(value: &crate::types::CandidateSwapResult) -> Self {
        let mut row = match value {
            crate::types::CandidateSwapResult::OutAmount(..) => Self::new("OutAmount".to_string()),
            crate::types::CandidateSwapResult::ProgramError(..) => {
                Self::new("ProgramError".to_string())
            }
        };

        let _ = &mut row;
        match value {
            crate::types::CandidateSwapResult::OutAmount(value_0) => {
                row.value_0 = Some(*value_0);
            }
            crate::types::CandidateSwapResult::ProgramError(value_0) => {
                row.value_0 = Some(*value_0);
            }
        }

        row
    }
}

#[derive(Debug, Clone, serde::Serialize)]
pub struct JupiterSwapCpiEventClickHouseRow {
    pub program_id: String,
    pub family_name: String,
    pub event_type: String,
    pub event_id: String,
    pub slot: u64,
    pub signature: String,
    pub instruction_index: u32,
    pub stack_height: u32,
    pub absolute_path: Vec<u8>,
    pub event_seq: u32,
    pub source_name: String,
    pub mode: String,
    pub decoder_version: String,
    pub ingest_ts: String,
    pub chain_time: Option<String>,
    pub partition_time: String,
    pub block_hash: Option<String>,
    pub tx_index: Option<u64>,
    pub fee_event_account: Option<String>,
    pub fee_event_mint: Option<String>,
    pub fee_event_amount: Option<u64>,
    pub swap_event_amm: Option<String>,
    pub swap_event_input_mint: Option<String>,
    pub swap_event_input_amount: Option<u64>,
    pub swap_event_output_mint: Option<String>,
    pub swap_event_output_amount: Option<u64>,
    pub swaps_event_swap_events_present: bool,
    pub swaps_event_swap_events: Vec<ClickHouseSwapEventV2>,
    pub candidate_swap_results_results_present: bool,
    pub candidate_swap_results_results: Vec<ClickHouseCandidateSwapResult>,
    pub candidate_swap_quote_error_candidate_index: Option<u64>,
    pub candidate_swap_quote_error_in_amount: Option<u64>,
    pub candidate_swap_quote_error_error_code: Option<u64>,
    pub best_swap_out_amount_violation_expected_out_amount: Option<u64>,
    pub best_swap_out_amount_violation_out_amount: Option<u64>,
}

impl JupiterSwapCpiEventClickHouseRow {
    pub const FAMILY_NAME: &'static str = "jupiter_swap_cpi_event";
    pub const DEFAULT_TABLE_NAME: &'static str = "jupiter_swap_cpi_event_landing";

    pub fn from_fee_event(
        source: &crate::events::fee_event::FeeEventEvent,
        metadata: &InstructionMetadata,
        context: &ClickHouseRowContext,
    ) -> Self {
        let mut row = Self::base("fee_event", metadata, context, Utc::now());
        let _ = &mut row;
        row.fee_event_account = Some(source.account.to_string());
        row.fee_event_mint = Some(source.mint.to_string());
        row.fee_event_amount = Some(source.amount);
        row
    }

    pub fn from_swap_event(
        source: &crate::events::swap_event::SwapEventEvent,
        metadata: &InstructionMetadata,
        context: &ClickHouseRowContext,
    ) -> Self {
        let mut row = Self::base("swap_event", metadata, context, Utc::now());
        let _ = &mut row;
        row.swap_event_amm = Some(source.amm.to_string());
        row.swap_event_input_mint = Some(source.input_mint.to_string());
        row.swap_event_input_amount = Some(source.input_amount);
        row.swap_event_output_mint = Some(source.output_mint.to_string());
        row.swap_event_output_amount = Some(source.output_amount);
        row
    }

    pub fn from_swaps_event(
        source: &crate::events::swaps_event::SwapsEventEvent,
        metadata: &InstructionMetadata,
        context: &ClickHouseRowContext,
    ) -> Self {
        let mut row = Self::base("swaps_event", metadata, context, Utc::now());
        let _ = &mut row;
        row.swaps_event_swap_events_present = true;
        row.swaps_event_swap_events = source
            .swap_events
            .iter()
            .map(|value| ClickHouseSwapEventV2::from(value))
            .collect();
        row
    }

    pub fn from_candidate_swap_results(
        source: &crate::events::candidate_swap_results::CandidateSwapResultsEvent,
        metadata: &InstructionMetadata,
        context: &ClickHouseRowContext,
    ) -> Self {
        let mut row = Self::base("candidate_swap_results", metadata, context, Utc::now());
        let _ = &mut row;
        row.candidate_swap_results_results_present = true;
        row.candidate_swap_results_results = source
            .results
            .iter()
            .map(|value| ClickHouseCandidateSwapResult::from(value))
            .collect();
        row
    }

    pub fn from_candidate_swap_quote_error(
        source: &crate::events::candidate_swap_quote_error::CandidateSwapQuoteErrorEvent,
        metadata: &InstructionMetadata,
        context: &ClickHouseRowContext,
    ) -> Self {
        let mut row = Self::base("candidate_swap_quote_error", metadata, context, Utc::now());
        let _ = &mut row;
        row.candidate_swap_quote_error_candidate_index = Some(source.candidate_index);
        row.candidate_swap_quote_error_in_amount = Some(source.in_amount);
        row.candidate_swap_quote_error_error_code = Some(source.error_code);
        row
    }

    pub fn from_best_swap_out_amount_violation(
        source: &crate::events::best_swap_out_amount_violation::BestSwapOutAmountViolationEvent,
        metadata: &InstructionMetadata,
        context: &ClickHouseRowContext,
    ) -> Self {
        let mut row = Self::base(
            "best_swap_out_amount_violation",
            metadata,
            context,
            Utc::now(),
        );
        let _ = &mut row;
        row.best_swap_out_amount_violation_expected_out_amount = Some(source.expected_out_amount);
        row.best_swap_out_amount_violation_out_amount = Some(source.out_amount);
        row
    }

    fn base(
        event_type: &'static str,
        metadata: &InstructionMetadata,
        context: &ClickHouseRowContext,
        ingest_ts: DateTime<Utc>,
    ) -> Self {
        let chain_time = metadata
            .transaction_metadata
            .block_time
            .and_then(DateTime::<Utc>::from_timestamp_secs);
        let partition_time = chain_time.unwrap_or(ingest_ts);
        let signature = metadata.transaction_metadata.signature.to_string();
        let event_seq = 0u32;

        Self {
            program_id: crate::PROGRAM_ID.to_string(),
            family_name: Self::FAMILY_NAME.to_string(),
            event_type: event_type.to_string(),
            event_id: deterministic_event_id(
                crate::PROGRAM_ID.as_ref(),
                &signature,
                &metadata.absolute_path,
                event_type,
                event_seq,
            ),
            slot: metadata.transaction_metadata.slot,
            signature,
            instruction_index: metadata.index,
            stack_height: metadata.stack_height,
            absolute_path: metadata.absolute_path.clone(),
            event_seq,
            source_name: context.source_name.clone(),
            mode: context.mode.clone(),
            decoder_version: context.decoder_version.clone(),
            ingest_ts: format_datetime(ingest_ts),
            chain_time: chain_time.map(format_datetime),
            partition_time: format_datetime(partition_time),
            block_hash: metadata
                .transaction_metadata
                .block_hash
                .map(|hash| hash.to_string()),
            tx_index: metadata.transaction_metadata.index,
            fee_event_account: None,
            fee_event_mint: None,
            fee_event_amount: None,
            swap_event_amm: None,
            swap_event_input_mint: None,
            swap_event_input_amount: None,
            swap_event_output_mint: None,
            swap_event_output_amount: None,
            swaps_event_swap_events_present: false,
            swaps_event_swap_events: Vec::new(),
            candidate_swap_results_results_present: false,
            candidate_swap_results_results: Vec::new(),
            candidate_swap_quote_error_candidate_index: None,
            candidate_swap_quote_error_in_amount: None,
            candidate_swap_quote_error_error_code: None,
            best_swap_out_amount_violation_expected_out_amount: None,
            best_swap_out_amount_violation_out_amount: None,
        }
    }
}

impl ClickHouseTable for JupiterSwapCpiEventClickHouseRow {
    fn table() -> &'static str {
        Self::DEFAULT_TABLE_NAME
    }

    fn columns() -> Vec<&'static str> {
        vec![
            "program_id",
            "family_name",
            "event_type",
            "event_id",
            "slot",
            "signature",
            "instruction_index",
            "stack_height",
            "absolute_path",
            "event_seq",
            "source_name",
            "mode",
            "decoder_version",
            "ingest_ts",
            "chain_time",
            "partition_time",
            "block_hash",
            "tx_index",
            "fee_event_account",
            "fee_event_mint",
            "fee_event_amount",
            "swap_event_amm",
            "swap_event_input_mint",
            "swap_event_input_amount",
            "swap_event_output_mint",
            "swap_event_output_amount",
            "swaps_event_swap_events_present",
            "swaps_event_swap_events",
            "candidate_swap_results_results_present",
            "candidate_swap_results_results",
            "candidate_swap_quote_error_candidate_index",
            "candidate_swap_quote_error_in_amount",
            "candidate_swap_quote_error_error_code",
            "best_swap_out_amount_violation_expected_out_amount",
            "best_swap_out_amount_violation_out_amount",
        ]
    }

    fn create_table_sql(table_name: &str) -> String {
        let engine = Self::clickhouse_engine(table_name);
        Self::create_table_sql_for(table_name, &engine, true)
    }
}

impl JupiterSwapCpiEventClickHouseRow {
    pub fn migration_operations(table_name: &str) -> Vec<String> {
        let mut operations = Vec::new();
        operations.push(Self::create_table_sql(table_name));
        operations.extend(Self::add_column_sql(table_name));
        operations
    }

    pub fn add_column_sql(table_name: &str) -> Vec<String> {
        vec![
            format!("ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS program_id String"),
            format!("ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS family_name String"),
            format!("ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS event_type String"),
            format!("ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS event_id String"),
            format!("ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS slot UInt64"),
            format!("ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS signature String"),
            format!("ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS instruction_index UInt32"),
            format!("ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS stack_height UInt32"),
            format!("ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS absolute_path Array(UInt8)"),
            format!("ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS event_seq UInt32"),
            format!("ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS source_name String"),
            format!("ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS mode String"),
            format!("ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS decoder_version String"),
            format!("ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS ingest_ts DateTime64(3, 'UTC')"),
            format!("ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS chain_time Nullable(DateTime64(3, 'UTC'))"),
            format!("ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS partition_time DateTime64(3, 'UTC')"),
            format!("ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS block_hash Nullable(String)"),
            format!("ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS tx_index Nullable(UInt64)"),
            format!("ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS fee_event_account Nullable(String)"),
            format!("ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS fee_event_mint Nullable(String)"),
            format!("ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS fee_event_amount Nullable(UInt64)"),
            format!("ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS swap_event_amm Nullable(String)"),
            format!("ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS swap_event_input_mint Nullable(String)"),
            format!("ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS swap_event_input_amount Nullable(UInt64)"),
            format!("ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS swap_event_output_mint Nullable(String)"),
            format!("ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS swap_event_output_amount Nullable(UInt64)"),
            format!("ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS swaps_event_swap_events_present Bool"),
            format!("ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS swaps_event_swap_events Array(Tuple(input_mint String, input_amount UInt64, output_mint String, output_amount UInt64))"),
            format!("ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS candidate_swap_results_results_present Bool"),
            format!("ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS candidate_swap_results_results Array(Tuple(variant Enum8('OutAmount' = 0, 'ProgramError' = 1), value_0 Nullable(UInt64)))"),
            format!("ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS candidate_swap_quote_error_candidate_index Nullable(UInt64)"),
            format!("ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS candidate_swap_quote_error_in_amount Nullable(UInt64)"),
            format!("ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS candidate_swap_quote_error_error_code Nullable(UInt64)"),
            format!("ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS best_swap_out_amount_violation_expected_out_amount Nullable(UInt64)"),
            format!("ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS best_swap_out_amount_violation_out_amount Nullable(UInt64)"),
        ]
    }

    fn clickhouse_engine(table_name: &str) -> String {
        let _ = table_name;
        format!("MergeTree")
    }

    fn create_table_sql_for(
        table_name: &str,
        engine: &str,
        include_merge_tree_clauses: bool,
    ) -> String {
        let merge_tree_clauses = if include_merge_tree_clauses {
            " PARTITION BY toYear(partition_time) ORDER BY (program_id, family_name, event_id, slot)"
        } else {
            ""
        };
        format!(
            "CREATE TABLE IF NOT EXISTS {table_name} (\
            program_id String,\
            family_name String,\
            event_type String,\
            event_id String,\
            slot UInt64,\
            signature String,\
            instruction_index UInt32,\
            stack_height UInt32,\
            absolute_path Array(UInt8),\
            event_seq UInt32,\
            source_name String,\
            mode String,\
            decoder_version String,\
            ingest_ts DateTime64(3, 'UTC'),\
            chain_time Nullable(DateTime64(3, 'UTC')),\
            partition_time DateTime64(3, 'UTC'),\
            block_hash Nullable(String),\
            tx_index Nullable(UInt64),\
            fee_event_account Nullable(String),\
            fee_event_mint Nullable(String),\
            fee_event_amount Nullable(UInt64),\
            swap_event_amm Nullable(String),\
            swap_event_input_mint Nullable(String),\
            swap_event_input_amount Nullable(UInt64),\
            swap_event_output_mint Nullable(String),\
            swap_event_output_amount Nullable(UInt64),\
            swaps_event_swap_events_present Bool,\
            swaps_event_swap_events Array(Tuple(input_mint String, input_amount UInt64, output_mint String, output_amount UInt64)),\
            candidate_swap_results_results_present Bool,\
            candidate_swap_results_results Array(Tuple(variant Enum8('OutAmount' = 0, 'ProgramError' = 1), value_0 Nullable(UInt64))),\
            candidate_swap_quote_error_candidate_index Nullable(UInt64),\
            candidate_swap_quote_error_in_amount Nullable(UInt64),\
            candidate_swap_quote_error_error_code Nullable(UInt64),\
            best_swap_out_amount_violation_expected_out_amount Nullable(UInt64),\
            best_swap_out_amount_violation_out_amount Nullable(UInt64)\
        ) ENGINE = {engine}{merge_tree_clauses}"
        )
    }
}

impl ClickHouseRow for JupiterSwapCpiEventClickHouseRow {
    fn table_name(&self) -> &'static str {
        Self::table()
    }

    fn partition_key(&self) -> String {
        self.partition_time[..4].to_string()
    }
}

fn format_datetime(value: DateTime<Utc>) -> String {
    value.format("%Y-%m-%d %H:%M:%S%.3f").to_string()
}

#[allow(dead_code)]
fn clickhouse_enum_variant<T>(value: &T) -> String
where
    T: serde::Serialize + std::fmt::Debug + ?Sized,
{
    match serde_json::to_value(value) {
        Ok(serde_json::Value::String(variant)) => variant,
        Ok(serde_json::Value::Object(object)) if object.len() == 1 => object
            .into_iter()
            .next()
            .map(|(variant, _)| variant)
            .unwrap_or_default(),
        _ => clickhouse_debug_variant(value),
    }
}

#[allow(dead_code)]
fn clickhouse_debug_variant<T>(value: &T) -> String
where
    T: std::fmt::Debug + ?Sized,
{
    let debug = format!("{value:?}");
    debug
        .split(['(', ' ', '{'])
        .next()
        .unwrap_or_default()
        .to_string()
}
