//! This code was AUTOGENERATED using the Codama library.

#[allow(unused_imports)]
use carbon_core::clickhouse::rows::clickhouse_enum_variant;
use carbon_core::{
    clickhouse::{
        rows::{
            ClickHouseInstructionLandingMetadata, ClickHouseRowContext,
            CLICKHOUSE_INSTRUCTION_COMMON_COLUMNS,
        },
        ClickHouseColumnSpec,
    },
    instruction::InstructionMetadata,
};

#[derive(Debug, Clone, serde::Serialize)]
pub struct CreateTokenAccountInstructionClickHouseRow {
    #[serde(flatten)]
    pub metadata: ClickHouseInstructionLandingMetadata,
    pub bump: u8,
}

impl CreateTokenAccountInstructionClickHouseRow {
    pub const FAMILY_NAME: &'static str = "jupiter_swap_create_token_account_instruction";
    pub const INSTRUCTION_TYPE: &'static str = "create_token_account";
    pub const DEFAULT_TABLE_NAME: &'static str =
        "jupiter_swap_create_token_account_instruction_landing";
    pub const COMMON_COLUMNS: &'static [ClickHouseColumnSpec] =
        CLICKHOUSE_INSTRUCTION_COMMON_COLUMNS;
    pub const PAYLOAD_COLUMNS: &'static [ClickHouseColumnSpec] =
        &[ClickHouseColumnSpec::new("bump", r#"UInt8"#)];

    pub fn from_parts(
        source: crate::instructions::create_token_account::CreateTokenAccount,
        metadata: &InstructionMetadata,
        context: &ClickHouseRowContext,
    ) -> Self {
        let _ = &source;

        Self {
            metadata: ClickHouseInstructionLandingMetadata::new(
                crate::PROGRAM_ID.as_ref(),
                crate::PROGRAM_ID.to_string(),
                Self::FAMILY_NAME,
                Self::INSTRUCTION_TYPE,
                metadata,
                context,
            ),
            bump: source.bump,
        }
    }
}

carbon_core::impl_clickhouse_instruction_row!(
    CreateTokenAccountInstructionClickHouseRow,
    super::clickhouse_instruction_table_options
);
