//! This code was AUTOGENERATED using the Codama library.

use super::types::*;
#[allow(unused_imports)]
use carbon_core::clickhouse::rows::clickhouse_enum_variant;
use carbon_core::{
    clickhouse::{
        rows::{
            ClickHouseInstructionLandingMetadata, ClickHouseRowContext,
            CLICKHOUSE_INSTRUCTION_COMMON_COLUMNS,
        },
        ClickHouseColumnSpec,
    },
    instruction::InstructionMetadata,
};

#[derive(Debug, Clone, serde::Serialize)]
pub struct ExactOutRouteV2InstructionClickHouseRow {
    #[serde(flatten)]
    pub metadata: ClickHouseInstructionLandingMetadata,
    pub out_amount: u64,
    pub quoted_in_amount: u64,
    pub slippage_bps: u16,
    pub platform_fee_bps: u16,
    pub positive_slippage_bps: u16,
    pub route_plan: Vec<ClickHouseRoutePlanStepV2>,
}

impl ExactOutRouteV2InstructionClickHouseRow {
    pub const FAMILY_NAME: &'static str = "jupiter_swap_exact_out_route_v2_instruction";
    pub const INSTRUCTION_TYPE: &'static str = "exact_out_route_v2";
    pub const DEFAULT_TABLE_NAME: &'static str =
        "jupiter_swap_exact_out_route_v2_instruction_landing";
    pub const COMMON_COLUMNS: &'static [ClickHouseColumnSpec] =
        CLICKHOUSE_INSTRUCTION_COMMON_COLUMNS;
    pub const PAYLOAD_COLUMNS: &'static [ClickHouseColumnSpec] = &[
        ClickHouseColumnSpec::new("out_amount", r#"UInt64"#),
        ClickHouseColumnSpec::new("quoted_in_amount", r#"UInt64"#),
        ClickHouseColumnSpec::new("slippage_bps", r#"UInt16"#),
        ClickHouseColumnSpec::new("platform_fee_bps", r#"UInt16"#),
        ClickHouseColumnSpec::new("positive_slippage_bps", r#"UInt16"#),
        ClickHouseColumnSpec::new("route_plan", ROUTE_PLAN_STEP_V2_ARRAY_DDL),
    ];

    pub fn from_parts(
        source: crate::instructions::exact_out_route_v2::ExactOutRouteV2,
        metadata: &InstructionMetadata,
        context: &ClickHouseRowContext,
    ) -> Self {
        let _ = &source;

        Self {
            metadata: ClickHouseInstructionLandingMetadata::new(
                crate::PROGRAM_ID.as_ref(),
                crate::PROGRAM_ID.to_string(),
                Self::FAMILY_NAME,
                Self::INSTRUCTION_TYPE,
                metadata,
                context,
            ),
            out_amount: source.out_amount,
            quoted_in_amount: source.quoted_in_amount,
            slippage_bps: source.slippage_bps,
            platform_fee_bps: source.platform_fee_bps,
            positive_slippage_bps: source.positive_slippage_bps,
            route_plan: source
                .route_plan
                .iter()
                .map(|value| ClickHouseRoutePlanStepV2::from(value))
                .collect(),
        }
    }
}

carbon_core::impl_clickhouse_instruction_row!(ExactOutRouteV2InstructionClickHouseRow);
