//! This code was AUTOGENERATED using the Codama library.

#[allow(unused_imports)]
use carbon_core::clickhouse::rows::clickhouse_enum_variant;
use carbon_core::{
    clickhouse::{
        rows::{
            ClickHouseEventLandingMetadata, ClickHouseRowContext, CLICKHOUSE_EVENT_COMMON_COLUMNS,
        },
        ClickHouseColumnSpec,
    },
    instruction::InstructionMetadata,
};

#[derive(Debug, Clone, serde::Serialize)]
pub struct FeeEventEventClickHouseRow {
    #[serde(flatten)]
    pub metadata: ClickHouseEventLandingMetadata,
    pub account: String,
    pub mint: String,
    pub amount: u64,
}

impl FeeEventEventClickHouseRow {
    pub const FAMILY_NAME: &'static str = "jupiter_swap_fee_event";
    pub const EVENT_TYPE: &'static str = "fee_event";
    pub const DEFAULT_TABLE_NAME: &'static str = "jupiter_swap_fee_event_landing";
    pub const COMMON_COLUMNS: &'static [ClickHouseColumnSpec] = CLICKHOUSE_EVENT_COMMON_COLUMNS;
    pub const PAYLOAD_COLUMNS: &'static [ClickHouseColumnSpec] = &[
        ClickHouseColumnSpec::new("account", r#"String"#),
        ClickHouseColumnSpec::new("mint", r#"String"#),
        ClickHouseColumnSpec::new("amount", r#"UInt64"#),
    ];

    pub fn from_parts(
        source: crate::events::fee_event::FeeEventEvent,
        metadata: &InstructionMetadata,
        context: &ClickHouseRowContext,
    ) -> Self {
        let _ = &source;
        let event_seq = 0u32;

        Self {
            metadata: ClickHouseEventLandingMetadata::new(
                crate::PROGRAM_ID.as_ref(),
                crate::PROGRAM_ID.to_string(),
                Self::FAMILY_NAME,
                Self::EVENT_TYPE,
                event_seq,
                metadata,
                context,
            ),
            account: source.account.to_string(),
            mint: source.mint.to_string(),
            amount: source.amount,
        }
    }
}

carbon_core::impl_clickhouse_event_row!(
    FeeEventEventClickHouseRow,
    super::clickhouse_instruction_table_options
);
