//! This code was AUTOGENERATED using the Codama library.
pub mod cpi_event_row;

pub use cpi_event_row::*;

use std::time::Duration;

use carbon_core::{
    clickhouse::{
        rows::{ClickHouseRows, ClickHouseTable},
        ClickHouseAdmin, ClickHouseConfig, ClickHouseInstructionProcessor, ClickHouseSchema,
    },
    error::CarbonResult,
    instruction::InstructionMetadata,
};
use solana_instruction::AccountMeta;

use super::JupiterSwapInstruction;

pub const DEFAULT_DATABASE: &str = "default";
pub const DEFAULT_SOURCE_NAME: &str = "block_crawler";
pub const DEFAULT_MODE: &str = "backfill";
pub const DEFAULT_DECODER_VERSION: &str = "v1";
pub const DEFAULT_MAX_ROWS: usize = 500;
pub const DEFAULT_FLUSH_INTERVAL_MS: u64 = 1_000;

pub type JupiterSwapClickHouseInstructionProcessor = ClickHouseInstructionProcessor<
    JupiterSwapInstruction,
    JupiterSwapInstructionWithClickHouseMetadata,
    JupiterSwapSwapEventLandingRow,
>;

pub struct JupiterSwapClickHouseInstructionsMigration;

impl ClickHouseSchema for JupiterSwapClickHouseInstructionsMigration {
    fn operations(config: &ClickHouseConfig) -> Vec<String> {
        vec![JupiterSwapSwapEventLandingRow::create_table_sql(&config.table)]
    }
}

impl JupiterSwapClickHouseInstructionsMigration {
    pub async fn run(config: &ClickHouseConfig) -> CarbonResult<()> {
        ClickHouseAdmin::new(config.clone())
            .execute_schema::<Self>()
            .await
    }
}

pub struct JupiterSwapInstructionWithClickHouseMetadata(
    pub JupiterSwapInstruction,
    pub InstructionMetadata,
    pub Vec<AccountMeta>,
);

impl From<(JupiterSwapInstruction, InstructionMetadata, Vec<AccountMeta>)>
    for JupiterSwapInstructionWithClickHouseMetadata
{
    fn from(
        value: (JupiterSwapInstruction, InstructionMetadata, Vec<AccountMeta>),
    ) -> Self {
        Self(value.0, value.1, value.2)
    }
}

impl ClickHouseRows<JupiterSwapSwapEventLandingRow>
    for JupiterSwapInstructionWithClickHouseMetadata
{
    fn clickhouse_rows(&self, config: &ClickHouseConfig) -> Vec<JupiterSwapSwapEventLandingRow> {
        let JupiterSwapInstructionWithClickHouseMetadata(instruction, metadata, _accounts) = self;

        match instruction {
            JupiterSwapInstruction::CpiEvent(instruction) => match instruction.as_ref() {
                super::CpiEvent::SwapEvent(swap_event) => vec![
                    JupiterSwapSwapEventLandingRow::from_parts(metadata, swap_event, config),
                ],
                _ => Vec::new(),
            },
            _ => Vec::new(),
        }
    }
}

pub fn default_clickhouse_config_from_database_url(
    database_url: &str,
) -> CarbonResult<ClickHouseConfig> {
    ClickHouseConfig::from_database_url(
        database_url,
        DEFAULT_DATABASE.to_string(),
        JupiterSwapSwapEventLandingRow::DEFAULT_TABLE_NAME.to_string(),
        DEFAULT_SOURCE_NAME.to_string(),
        DEFAULT_MODE.to_string(),
        DEFAULT_DECODER_VERSION.to_string(),
        DEFAULT_MAX_ROWS,
        Duration::from_millis(DEFAULT_FLUSH_INTERVAL_MS),
    )
}

pub async fn bootstrap_clickhouse_from_database_url(
    database_url: &str,
) -> CarbonResult<ClickHouseConfig> {
    let config = default_clickhouse_config_from_database_url(database_url)?;
    JupiterSwapClickHouseInstructionsMigration::run(&config).await?;
    Ok(config)
}

pub fn default_clickhouse_processor(
    config: ClickHouseConfig,
) -> JupiterSwapClickHouseInstructionProcessor {
    ClickHouseInstructionProcessor::new(config)
}
