//! This code was AUTOGENERATED using the Codama library.
pub mod best_swap_out_amount_violation_event_row;
pub mod candidate_swap_quote_error_event_row;
pub mod candidate_swap_results_event_row;
pub mod claim_row;
pub mod claim_token_row;
pub mod close_token_row;
pub mod close_wsol_token_account_row;
pub mod create_token_account_row;
pub mod create_token_ledger_row;
pub mod exact_out_route_row;
pub mod exact_out_route_v2_row;
pub mod fee_event_event_row;
pub mod route_row;
pub mod route_v2_row;
pub mod route_with_token_ledger_row;
pub mod set_token_ledger_row;
pub mod shared_accounts_exact_out_route_row;
pub mod shared_accounts_exact_out_route_v2_row;
pub mod shared_accounts_route_row;
pub mod shared_accounts_route_v2_row;
pub mod shared_accounts_route_with_token_ledger_row;
pub mod swap_event_event_row;
pub mod swaps_event_event_row;
pub mod types;

pub use self::best_swap_out_amount_violation_event_row::BestSwapOutAmountViolationEventClickHouseRow;
pub use self::candidate_swap_quote_error_event_row::CandidateSwapQuoteErrorEventClickHouseRow;
pub use self::candidate_swap_results_event_row::CandidateSwapResultsEventClickHouseRow;
pub use self::claim_row::ClaimInstructionClickHouseRow;
pub use self::claim_token_row::ClaimTokenInstructionClickHouseRow;
pub use self::close_token_row::CloseTokenInstructionClickHouseRow;
pub use self::close_wsol_token_account_row::CloseWsolTokenAccountInstructionClickHouseRow;
pub use self::create_token_account_row::CreateTokenAccountInstructionClickHouseRow;
pub use self::create_token_ledger_row::CreateTokenLedgerInstructionClickHouseRow;
pub use self::exact_out_route_row::ExactOutRouteInstructionClickHouseRow;
pub use self::exact_out_route_v2_row::ExactOutRouteV2InstructionClickHouseRow;
pub use self::fee_event_event_row::FeeEventEventClickHouseRow;
pub use self::route_row::RouteInstructionClickHouseRow;
pub use self::route_v2_row::RouteV2InstructionClickHouseRow;
pub use self::route_with_token_ledger_row::RouteWithTokenLedgerInstructionClickHouseRow;
pub use self::set_token_ledger_row::SetTokenLedgerInstructionClickHouseRow;
pub use self::shared_accounts_exact_out_route_row::SharedAccountsExactOutRouteInstructionClickHouseRow;
pub use self::shared_accounts_exact_out_route_v2_row::SharedAccountsExactOutRouteV2InstructionClickHouseRow;
pub use self::shared_accounts_route_row::SharedAccountsRouteInstructionClickHouseRow;
pub use self::shared_accounts_route_v2_row::SharedAccountsRouteV2InstructionClickHouseRow;
pub use self::shared_accounts_route_with_token_ledger_row::SharedAccountsRouteWithTokenLedgerInstructionClickHouseRow;
pub use self::swap_event_event_row::SwapEventEventClickHouseRow;
pub use self::swaps_event_event_row::SwapsEventEventClickHouseRow;

use std::time::Duration;

use carbon_core::{
    clickhouse::{
        ClickHouseAdmin, ClickHouseBatchSettings, ClickHouseConfig, ClickHouseInstructionProcessor,
        ClickHouseTableOptions,
    },
    error::CarbonResult,
    instruction::InstructionMetadata,
};
use solana_instruction::AccountMeta;

use super::{CpiEvent, JupiterSwapInstruction};

pub const DEFAULT_DATABASE: &str = "default";
pub const DEFAULT_SOURCE_NAME: &str = "block_crawler";
pub const DEFAULT_MODE: &str = "backfill";
pub const DEFAULT_DECODER_VERSION: &str = "v1";
pub const DEFAULT_BATCH_MAX_ROWS: usize = 500;
pub const DEFAULT_BATCH_FLUSH_INTERVAL_MS: u64 = 1_000;

pub(crate) fn clickhouse_instruction_table_options() -> ClickHouseTableOptions {
    ClickHouseTableOptions {
        on_cluster_clause: r#""#,
        engine: r#"MergeTree"#.to_string(),
        local_engine: None,
        local_table_suffix: r#"_local"#,
        partition_by: r#"toYear(partition_time)"#,
        order_by: r#"(program_id, family_name, instruction_id, slot)"#,
        ttl_clause: r#""#,
        settings_clause: r#" SETTINGS non_replicated_deduplication_window = 1000"#,
    }
}

#[derive(Debug, Clone, serde::Serialize)]
#[serde(untagged)]
pub enum JupiterSwapClickHouseInstructionRow {
    Claim(claim_row::ClaimInstructionClickHouseRow),
    ClaimToken(claim_token_row::ClaimTokenInstructionClickHouseRow),
    CloseToken(close_token_row::CloseTokenInstructionClickHouseRow),
    CloseWsolTokenAccount(close_wsol_token_account_row::CloseWsolTokenAccountInstructionClickHouseRow),
    CreateTokenAccount(create_token_account_row::CreateTokenAccountInstructionClickHouseRow),
    CreateTokenLedger(create_token_ledger_row::CreateTokenLedgerInstructionClickHouseRow),
    ExactOutRoute(exact_out_route_row::ExactOutRouteInstructionClickHouseRow),
    ExactOutRouteV2(exact_out_route_v2_row::ExactOutRouteV2InstructionClickHouseRow),
    Route(route_row::RouteInstructionClickHouseRow),
    RouteV2(route_v2_row::RouteV2InstructionClickHouseRow),
    RouteWithTokenLedger(route_with_token_ledger_row::RouteWithTokenLedgerInstructionClickHouseRow),
    SetTokenLedger(set_token_ledger_row::SetTokenLedgerInstructionClickHouseRow),
    SharedAccountsExactOutRoute(shared_accounts_exact_out_route_row::SharedAccountsExactOutRouteInstructionClickHouseRow),
    SharedAccountsExactOutRouteV2(shared_accounts_exact_out_route_v2_row::SharedAccountsExactOutRouteV2InstructionClickHouseRow),
    SharedAccountsRoute(shared_accounts_route_row::SharedAccountsRouteInstructionClickHouseRow),
    SharedAccountsRouteV2(shared_accounts_route_v2_row::SharedAccountsRouteV2InstructionClickHouseRow),
    SharedAccountsRouteWithTokenLedger(shared_accounts_route_with_token_ledger_row::SharedAccountsRouteWithTokenLedgerInstructionClickHouseRow),
    BestSwapOutAmountViolationEvent(best_swap_out_amount_violation_event_row::BestSwapOutAmountViolationEventClickHouseRow),
    CandidateSwapQuoteErrorEvent(candidate_swap_quote_error_event_row::CandidateSwapQuoteErrorEventClickHouseRow),
    CandidateSwapResultsEvent(candidate_swap_results_event_row::CandidateSwapResultsEventClickHouseRow),
    FeeEventEvent(fee_event_event_row::FeeEventEventClickHouseRow),
    SwapEventEvent(swap_event_event_row::SwapEventEventClickHouseRow),
    SwapsEventEvent(swaps_event_event_row::SwapsEventEventClickHouseRow),
}

pub type JupiterSwapClickHouseInstructionProcessor = ClickHouseInstructionProcessor<
    JupiterSwapInstruction,
    JupiterSwapInstructionWithClickHouseMetadata,
    JupiterSwapClickHouseInstructionRow,
>;

pub struct JupiterSwapClickHouseInstructionsMigration;

carbon_core::clickhouse_row_dispatch!(
    instruction
    JupiterSwapClickHouseInstructionRow,
    JupiterSwapClickHouseInstructionsMigration,
    JupiterSwapInstructionWithClickHouseMetadata,
    JupiterSwapInstruction,
    {
        Claim => claim_row::ClaimInstructionClickHouseRow,
        ClaimToken => claim_token_row::ClaimTokenInstructionClickHouseRow,
        CloseToken => close_token_row::CloseTokenInstructionClickHouseRow,
        CloseWsolTokenAccount => close_wsol_token_account_row::CloseWsolTokenAccountInstructionClickHouseRow,
        CreateTokenAccount => create_token_account_row::CreateTokenAccountInstructionClickHouseRow,
        CreateTokenLedger => create_token_ledger_row::CreateTokenLedgerInstructionClickHouseRow,
        ExactOutRoute => exact_out_route_row::ExactOutRouteInstructionClickHouseRow,
        ExactOutRouteV2 => exact_out_route_v2_row::ExactOutRouteV2InstructionClickHouseRow,
        Route => route_row::RouteInstructionClickHouseRow,
        RouteV2 => route_v2_row::RouteV2InstructionClickHouseRow,
        RouteWithTokenLedger => route_with_token_ledger_row::RouteWithTokenLedgerInstructionClickHouseRow,
        SetTokenLedger => set_token_ledger_row::SetTokenLedgerInstructionClickHouseRow,
        SharedAccountsExactOutRoute => shared_accounts_exact_out_route_row::SharedAccountsExactOutRouteInstructionClickHouseRow,
        SharedAccountsExactOutRouteV2 => shared_accounts_exact_out_route_v2_row::SharedAccountsExactOutRouteV2InstructionClickHouseRow,
        SharedAccountsRoute => shared_accounts_route_row::SharedAccountsRouteInstructionClickHouseRow,
        SharedAccountsRouteV2 => shared_accounts_route_v2_row::SharedAccountsRouteV2InstructionClickHouseRow,
        SharedAccountsRouteWithTokenLedger => shared_accounts_route_with_token_ledger_row::SharedAccountsRouteWithTokenLedgerInstructionClickHouseRow,
    }
    events CpiEvent {
        BestSwapOutAmountViolationEvent: BestSwapOutAmountViolation => best_swap_out_amount_violation_event_row::BestSwapOutAmountViolationEventClickHouseRow,
        CandidateSwapQuoteErrorEvent: CandidateSwapQuoteError => candidate_swap_quote_error_event_row::CandidateSwapQuoteErrorEventClickHouseRow,
        CandidateSwapResultsEvent: CandidateSwapResults => candidate_swap_results_event_row::CandidateSwapResultsEventClickHouseRow,
        FeeEventEvent: FeeEvent => fee_event_event_row::FeeEventEventClickHouseRow,
        SwapEventEvent: SwapEvent => swap_event_event_row::SwapEventEventClickHouseRow,
        SwapsEventEvent: SwapsEvent => swaps_event_event_row::SwapsEventEventClickHouseRow,
    }
);

impl JupiterSwapClickHouseInstructionsMigration {
    pub async fn run(config: &ClickHouseConfig) -> CarbonResult<()> {
        ClickHouseAdmin::new(config.clone())
            .execute_schema::<Self>()
            .await
    }
}

pub struct JupiterSwapInstructionWithClickHouseMetadata(
    pub JupiterSwapInstruction,
    pub InstructionMetadata,
    pub Vec<AccountMeta>,
);

impl
    From<(
        JupiterSwapInstruction,
        InstructionMetadata,
        Vec<AccountMeta>,
    )> for JupiterSwapInstructionWithClickHouseMetadata
{
    fn from(
        value: (
            JupiterSwapInstruction,
            InstructionMetadata,
            Vec<AccountMeta>,
        ),
    ) -> Self {
        Self(value.0, value.1, value.2)
    }
}

pub fn clickhouse_config_from_database_url(database_url: &str) -> CarbonResult<ClickHouseConfig> {
    ClickHouseConfig::from_database_url(
        database_url,
        DEFAULT_DATABASE.to_string(),
        claim_row::ClaimInstructionClickHouseRow::DEFAULT_TABLE_NAME.to_string(),
        DEFAULT_SOURCE_NAME.to_string(),
        DEFAULT_MODE.to_string(),
        DEFAULT_DECODER_VERSION.to_string(),
        ClickHouseBatchSettings::new(
            DEFAULT_BATCH_MAX_ROWS,
            Duration::from_millis(DEFAULT_BATCH_FLUSH_INTERVAL_MS),
        ),
    )
}

pub async fn bootstrap_clickhouse_from_database_url(
    database_url: &str,
) -> CarbonResult<ClickHouseConfig> {
    let config = clickhouse_config_from_database_url(database_url)?;
    JupiterSwapClickHouseInstructionsMigration::run(&config).await?;
    Ok(config)
}

pub fn clickhouse_processor(config: ClickHouseConfig) -> JupiterSwapClickHouseInstructionProcessor {
    ClickHouseInstructionProcessor::new(config)
}

pub async fn setup_clickhouse(
    database_url: &str,
) -> CarbonResult<JupiterSwapClickHouseInstructionProcessor> {
    let config = bootstrap_clickhouse_from_database_url(database_url).await?;
    Ok(clickhouse_processor(config))
}
