//! This code was AUTOGENERATED using the Codama library.

use super::types::*;
#[allow(unused_imports)]
use carbon_core::clickhouse::rows::clickhouse_enum_variant;
use carbon_core::{
    clickhouse::{
        rows::{
            ClickHouseInstructionLandingMetadata, ClickHouseRowContext,
            CLICKHOUSE_INSTRUCTION_COMMON_COLUMNS,
        },
        ClickHouseColumnSpec,
    },
    instruction::InstructionMetadata,
};

#[derive(Debug, Clone, serde::Serialize)]
pub struct SharedAccountsRouteInstructionClickHouseRow {
    #[serde(flatten)]
    pub metadata: ClickHouseInstructionLandingMetadata,
    pub id: u8,
    pub route_plan: Vec<ClickHouseRoutePlanStep>,
    pub in_amount: u64,
    pub quoted_out_amount: u64,
    pub slippage_bps: u16,
    pub platform_fee_bps: u8,
}

impl SharedAccountsRouteInstructionClickHouseRow {
    pub const FAMILY_NAME: &'static str = "jupiter_swap_shared_accounts_route_instruction";
    pub const INSTRUCTION_TYPE: &'static str = "shared_accounts_route";
    pub const DEFAULT_TABLE_NAME: &'static str =
        "jupiter_swap_shared_accounts_route_instruction_landing";
    pub const COMMON_COLUMNS: &'static [ClickHouseColumnSpec] =
        CLICKHOUSE_INSTRUCTION_COMMON_COLUMNS;
    pub const PAYLOAD_COLUMNS: &'static [ClickHouseColumnSpec] = &[
        ClickHouseColumnSpec::new("id", r#"UInt8"#),
        ClickHouseColumnSpec::new("route_plan", ROUTE_PLAN_STEP_ARRAY_DDL),
        ClickHouseColumnSpec::new("in_amount", r#"UInt64"#),
        ClickHouseColumnSpec::new("quoted_out_amount", r#"UInt64"#),
        ClickHouseColumnSpec::new("slippage_bps", r#"UInt16"#),
        ClickHouseColumnSpec::new("platform_fee_bps", r#"UInt8"#),
    ];

    pub fn from_parts(
        source: crate::instructions::shared_accounts_route::SharedAccountsRoute,
        metadata: &InstructionMetadata,
        context: &ClickHouseRowContext,
    ) -> Self {
        let _ = &source;

        Self {
            metadata: ClickHouseInstructionLandingMetadata::new(
                crate::PROGRAM_ID.as_ref(),
                crate::PROGRAM_ID.to_string(),
                Self::FAMILY_NAME,
                Self::INSTRUCTION_TYPE,
                metadata,
                context,
            ),
            id: source.id,
            route_plan: source
                .route_plan
                .iter()
                .map(|value| ClickHouseRoutePlanStep::from(value))
                .collect(),
            in_amount: source.in_amount,
            quoted_out_amount: source.quoted_out_amount,
            slippage_bps: source.slippage_bps,
            platform_fee_bps: source.platform_fee_bps,
        }
    }
}

carbon_core::impl_clickhouse_instruction_row!(
    SharedAccountsRouteInstructionClickHouseRow,
    super::clickhouse_instruction_table_options
);
