//! This code was AUTOGENERATED using the Codama library.

use super::types::*;
#[allow(unused_imports)]
use carbon_core::clickhouse::rows::clickhouse_enum_variant;
use carbon_core::{
    clickhouse::{
        rows::{
            ClickHouseEventLandingMetadata, ClickHouseRowContext, CLICKHOUSE_EVENT_COMMON_COLUMNS,
        },
        ClickHouseColumnSpec,
    },
    instruction::InstructionMetadata,
};

#[derive(Debug, Clone, serde::Serialize)]
pub struct SwapsEventEventClickHouseRow {
    #[serde(flatten)]
    pub metadata: ClickHouseEventLandingMetadata,
    pub swap_events: Vec<ClickHouseSwapEventV2>,
}

impl SwapsEventEventClickHouseRow {
    pub const FAMILY_NAME: &'static str = "jupiter_swap_swaps_event";
    pub const EVENT_TYPE: &'static str = "swaps_event";
    pub const DEFAULT_TABLE_NAME: &'static str = "jupiter_swap_swaps_event_landing";
    pub const COMMON_COLUMNS: &'static [ClickHouseColumnSpec] = CLICKHOUSE_EVENT_COMMON_COLUMNS;
    pub const PAYLOAD_COLUMNS: &'static [ClickHouseColumnSpec] = &[ClickHouseColumnSpec::new(
        "swap_events",
        SWAP_EVENT_V2_ARRAY_DDL,
    )];

    pub fn from_parts(
        source: crate::events::swaps_event::SwapsEventEvent,
        metadata: &InstructionMetadata,
        context: &ClickHouseRowContext,
    ) -> Self {
        let _ = &source;
        let event_seq = 0u32;

        Self {
            metadata: ClickHouseEventLandingMetadata::new(
                crate::PROGRAM_ID.as_ref(),
                crate::PROGRAM_ID.to_string(),
                Self::FAMILY_NAME,
                Self::EVENT_TYPE,
                event_seq,
                metadata,
                context,
            ),
            swap_events: source
                .swap_events
                .iter()
                .map(|value| ClickHouseSwapEventV2::from(value))
                .collect(),
        }
    }
}

carbon_core::impl_clickhouse_event_row!(
    SwapsEventEventClickHouseRow,
    super::clickhouse_instruction_table_options
);
