//! This code was AUTOGENERATED using the Codama library.

#[allow(unused_imports)]
use carbon_core::clickhouse::rows::clickhouse_enum_variant;
use carbon_core::{
    clickhouse::{
        rows::{
            ClickHouseEventLandingMetadata, ClickHouseRowContext, CLICKHOUSE_EVENT_COMMON_COLUMNS,
        },
        ClickHouseColumnSpec,
    },
    instruction::InstructionMetadata,
};

#[derive(Debug, Clone, serde::Serialize)]
pub struct SwapEventEventClickHouseRow {
    #[serde(flatten)]
    pub metadata: ClickHouseEventLandingMetadata,
    pub amm: String,
    pub input_mint: String,
    pub input_amount: u64,
    pub output_mint: String,
    pub output_amount: u64,
}

impl SwapEventEventClickHouseRow {
    pub const FAMILY_NAME: &'static str = "jupiter_swap_swap_event";
    pub const EVENT_TYPE: &'static str = "swap_event";
    pub const DEFAULT_TABLE_NAME: &'static str = "jupiter_swap_swap_event_landing";
    pub const COMMON_COLUMNS: &'static [ClickHouseColumnSpec] = CLICKHOUSE_EVENT_COMMON_COLUMNS;
    pub const PAYLOAD_COLUMNS: &'static [ClickHouseColumnSpec] = &[
        ClickHouseColumnSpec::new("amm", r#"String"#),
        ClickHouseColumnSpec::new("input_mint", r#"String"#),
        ClickHouseColumnSpec::new("input_amount", r#"UInt64"#),
        ClickHouseColumnSpec::new("output_mint", r#"String"#),
        ClickHouseColumnSpec::new("output_amount", r#"UInt64"#),
    ];

    pub fn from_parts(
        source: crate::events::swap_event::SwapEventEvent,
        metadata: &InstructionMetadata,
        context: &ClickHouseRowContext,
    ) -> Self {
        let _ = &source;
        let event_seq = 0u32;

        Self {
            metadata: ClickHouseEventLandingMetadata::new(
                crate::PROGRAM_ID.as_ref(),
                crate::PROGRAM_ID.to_string(),
                Self::FAMILY_NAME,
                Self::EVENT_TYPE,
                event_seq,
                metadata,
                context,
            ),
            amm: source.amm.to_string(),
            input_mint: source.input_mint.to_string(),
            input_amount: source.input_amount,
            output_mint: source.output_mint.to_string(),
            output_amount: source.output_amount,
        }
    }
}

carbon_core::impl_clickhouse_event_row!(SwapEventEventClickHouseRow);
