//! This code was AUTOGENERATED using the Codama library.
#[allow(unused_imports)]
use carbon_core::clickhouse::rows::clickhouse_enum_variant;

#[derive(Debug, Clone, serde::Serialize)]
pub struct ClickHouseSwapEventV2 {
    pub input_mint: String,
    pub input_amount: u64,
    pub output_mint: String,
    pub output_amount: u64,
}

impl Default for ClickHouseSwapEventV2 {
    fn default() -> Self {
        Self {
            input_mint: String::new(),
            input_amount: 0,
            output_mint: String::new(),
            output_amount: 0,
        }
    }
}

impl From<&crate::types::SwapEventV2> for ClickHouseSwapEventV2 {
    fn from(value: &crate::types::SwapEventV2) -> Self {
        Self {
            input_mint: value.input_mint.to_string(),
            input_amount: value.input_amount,
            output_mint: value.output_mint.to_string(),
            output_amount: value.output_amount,
        }
    }
}

#[derive(Debug, Clone, serde::Serialize)]
pub struct ClickHouseCandidateSwapResult {
    pub variant: String,
    pub value_0: Option<u64>,
}

impl ClickHouseCandidateSwapResult {
    fn new(variant: String) -> Self {
        Self {
            variant,
            value_0: None,
        }
    }
}

impl Default for ClickHouseCandidateSwapResult {
    fn default() -> Self {
        Self::new("OutAmount".to_string())
    }
}

impl From<&crate::types::CandidateSwapResult> for ClickHouseCandidateSwapResult {
    fn from(value: &crate::types::CandidateSwapResult) -> Self {
        let mut row = match value {
            crate::types::CandidateSwapResult::OutAmount(..) => Self::new("OutAmount".to_string()),
            crate::types::CandidateSwapResult::ProgramError(..) => {
                Self::new("ProgramError".to_string())
            }
        };

        let _ = &mut row;
        match value {
            crate::types::CandidateSwapResult::OutAmount(value_0) => {
                row.value_0 = Some(*value_0);
            }
            crate::types::CandidateSwapResult::ProgramError(value_0) => {
                row.value_0 = Some(*value_0);
            }
        }

        row
    }
}

#[derive(Debug, Clone, serde::Serialize)]
pub struct ClickHouseRemainingAccountsSlice {
    pub accounts_type: u8,
    pub length: u8,
}

impl Default for ClickHouseRemainingAccountsSlice {
    fn default() -> Self {
        Self {
            accounts_type: 0,
            length: 0,
        }
    }
}

impl From<&crate::types::RemainingAccountsSlice> for ClickHouseRemainingAccountsSlice {
    fn from(value: &crate::types::RemainingAccountsSlice) -> Self {
        Self {
            accounts_type: value.accounts_type,
            length: value.length,
        }
    }
}

#[derive(Debug, Clone, serde::Serialize)]
pub struct ClickHouseRemainingAccountsInfo {
    pub slices: Vec<ClickHouseRemainingAccountsSlice>,
}

impl Default for ClickHouseRemainingAccountsInfo {
    fn default() -> Self {
        Self { slices: Vec::new() }
    }
}

impl From<&crate::types::RemainingAccountsInfo> for ClickHouseRemainingAccountsInfo {
    fn from(value: &crate::types::RemainingAccountsInfo) -> Self {
        Self {
            slices: value
                .slices
                .iter()
                .map(|value| ClickHouseRemainingAccountsSlice::from(value))
                .collect(),
        }
    }
}

#[derive(Debug, Clone, Copy, Default)]
pub struct ClickHouseUInt128(pub u128);

impl serde::Serialize for ClickHouseUInt128 {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        serializer.serialize_str(&self.0.to_string())
    }
}

#[derive(Debug, Clone, serde::Serialize)]
pub struct ClickHouseCandidateSwap {
    pub variant: String,
    pub swap_id: Option<u64>,
    pub is_base_to_quote: Option<bool>,
    pub side: Option<String>,
    pub a_to_b: Option<bool>,
    pub is_bid: Option<bool>,
    pub remaining_accounts_info_present: bool,
    pub remaining_accounts_info: ClickHouseRemainingAccountsInfo,
}

impl ClickHouseCandidateSwap {
    fn new(variant: String) -> Self {
        Self {
            variant,
            swap_id: None,
            is_base_to_quote: None,
            side: None,
            a_to_b: None,
            is_bid: None,
            remaining_accounts_info_present: false,
            remaining_accounts_info: ClickHouseRemainingAccountsInfo::default(),
        }
    }
}

impl Default for ClickHouseCandidateSwap {
    fn default() -> Self {
        Self::new("HumidiFi".to_string())
    }
}

impl From<&crate::types::CandidateSwap> for ClickHouseCandidateSwap {
    fn from(value: &crate::types::CandidateSwap) -> Self {
        let mut row = match value {
            crate::types::CandidateSwap::HumidiFi { .. } => Self::new("HumidiFi".to_string()),
            crate::types::CandidateSwap::TesseraV { .. } => Self::new("TesseraV".to_string()),
            crate::types::CandidateSwap::HumidiFiV2 { .. } => Self::new("HumidiFiV2".to_string()),
            crate::types::CandidateSwap::RaydiumV2 => Self::new("RaydiumV2".to_string()),
            crate::types::CandidateSwap::RaydiumClmm => Self::new("RaydiumClmm".to_string()),
            crate::types::CandidateSwap::Whirlpool { .. } => Self::new("Whirlpool".to_string()),
            crate::types::CandidateSwap::ZeroFi => Self::new("ZeroFi".to_string()),
            crate::types::CandidateSwap::BisonFiV2 { .. } => Self::new("BisonFiV2".to_string()),
            crate::types::CandidateSwap::GoonFiV2 { .. } => Self::new("GoonFiV2".to_string()),
            crate::types::CandidateSwap::GoonFiV3 { .. } => Self::new("GoonFiV3".to_string()),
            crate::types::CandidateSwap::WhirlpoolV2 { .. } => Self::new("WhirlpoolV2".to_string()),
            crate::types::CandidateSwap::ZeroFiSwapV2 => Self::new("ZeroFiSwapV2".to_string()),
        };

        let _ = &mut row;
        match value {
            crate::types::CandidateSwap::HumidiFi {
                swap_id,
                is_base_to_quote,
            } => {
                row.swap_id = Some(*swap_id);
                row.is_base_to_quote = Some(*is_base_to_quote);
            }
            crate::types::CandidateSwap::TesseraV { side } => {
                row.side = Some(clickhouse_enum_variant(side));
            }
            crate::types::CandidateSwap::HumidiFiV2 {
                swap_id,
                is_base_to_quote,
            } => {
                row.swap_id = Some(*swap_id);
                row.is_base_to_quote = Some(*is_base_to_quote);
            }
            crate::types::CandidateSwap::RaydiumV2 => {}
            crate::types::CandidateSwap::RaydiumClmm => {}
            crate::types::CandidateSwap::Whirlpool { a_to_b } => {
                row.a_to_b = Some(*a_to_b);
            }
            crate::types::CandidateSwap::ZeroFi => {}
            crate::types::CandidateSwap::BisonFiV2 { a_to_b } => {
                row.a_to_b = Some(*a_to_b);
            }
            crate::types::CandidateSwap::GoonFiV2 { is_bid } => {
                row.is_bid = Some(*is_bid);
            }
            crate::types::CandidateSwap::GoonFiV3 { is_bid } => {
                row.is_bid = Some(*is_bid);
            }
            crate::types::CandidateSwap::WhirlpoolV2 {
                a_to_b,
                remaining_accounts_info,
            } => {
                row.a_to_b = Some(*a_to_b);
                if let Some(value) = remaining_accounts_info.as_ref() {
                    row.remaining_accounts_info_present = true;
                    row.remaining_accounts_info = ClickHouseRemainingAccountsInfo::from(value);
                }
            }
            crate::types::CandidateSwap::ZeroFiSwapV2 => {}
        }

        row
    }
}

#[derive(Debug, Clone, serde::Serialize)]
pub struct ClickHouseCandidateSwapWithBps {
    pub candidate_swap: ClickHouseCandidateSwap,
    pub bps: u32,
}

impl Default for ClickHouseCandidateSwapWithBps {
    fn default() -> Self {
        Self {
            candidate_swap: ClickHouseCandidateSwap::default(),
            bps: 0,
        }
    }
}

impl From<&crate::types::CandidateSwapWithBps> for ClickHouseCandidateSwapWithBps {
    fn from(value: &crate::types::CandidateSwapWithBps) -> Self {
        Self {
            candidate_swap: ClickHouseCandidateSwap::from(&value.candidate_swap),
            bps: value.bps,
        }
    }
}

#[derive(Debug, Clone, serde::Serialize)]
pub struct ClickHouseSwap {
    pub variant: String,
    pub a_to_b: Option<bool>,
    pub side: Option<String>,
    pub x_to_y: Option<bool>,
    pub stable: Option<bool>,
    pub from_token_id: Option<u64>,
    pub to_token_id: Option<u64>,
    pub bridge_stake_seed: Option<u32>,
    pub pool_index: Option<u8>,
    pub quantity_is_input: Option<bool>,
    pub quantity_is_collateral: Option<bool>,
    pub src_lst_value_calc_accs: Option<u8>,
    pub dst_lst_value_calc_accs: Option<u8>,
    pub src_lst_index: Option<u32>,
    pub dst_lst_index: Option<u32>,
    pub lst_value_calc_accs: Option<u8>,
    pub lst_index: Option<u32>,
    pub remaining_accounts_info_present: bool,
    pub remaining_accounts_info: ClickHouseRemainingAccountsInfo,
    pub is_y: Option<bool>,
    pub is_quote_to_base: Option<bool>,
    pub in_index: Option<u8>,
    pub out_index: Option<u8>,
    pub share_fee_rate: Option<u64>,
    pub is_bid: Option<bool>,
    pub blacklist_bump: Option<u8>,
    pub swap_id: Option<ClickHouseUInt128>,
    pub is_base_to_quote: Option<bool>,
    pub swap_for_y: Option<bool>,
    pub dynamic_v1_candidate_swaps_present: bool,
    pub dynamic_v1_candidate_swaps: Vec<ClickHouseCandidateSwap>,
    pub dynamic_v2_candidate_swaps_present: bool,
    pub dynamic_v2_candidate_swaps: Vec<ClickHouseCandidateSwapWithBps>,
    pub best_position: Option<u8>,
    pub is_mint: Option<bool>,
    pub fill_data_present: bool,
    pub fill_data: Vec<u8>,
    pub lst_amounts_present: bool,
    pub lst_amounts: Vec<u64>,
    pub seed: Option<u64>,
    pub auth_amount_in: Option<u64>,
    pub auth: Option<u64>,
    pub amount_is_token_a: Option<bool>,
    pub is_base_in: Option<bool>,
    pub swap_type: Option<String>,
    pub max_split_quote_calls: Option<u8>,
    pub max_split_candidates: Option<u8>,
    pub claim_cashback: Option<bool>,
}

impl ClickHouseSwap {
    fn new(variant: String) -> Self {
        Self {
            variant,
            a_to_b: None,
            side: None,
            x_to_y: None,
            stable: None,
            from_token_id: None,
            to_token_id: None,
            bridge_stake_seed: None,
            pool_index: None,
            quantity_is_input: None,
            quantity_is_collateral: None,
            src_lst_value_calc_accs: None,
            dst_lst_value_calc_accs: None,
            src_lst_index: None,
            dst_lst_index: None,
            lst_value_calc_accs: None,
            lst_index: None,
            remaining_accounts_info_present: false,
            remaining_accounts_info: ClickHouseRemainingAccountsInfo::default(),
            is_y: None,
            is_quote_to_base: None,
            in_index: None,
            out_index: None,
            share_fee_rate: None,
            is_bid: None,
            blacklist_bump: None,
            swap_id: None,
            is_base_to_quote: None,
            swap_for_y: None,
            dynamic_v1_candidate_swaps_present: false,
            dynamic_v1_candidate_swaps: Vec::new(),
            dynamic_v2_candidate_swaps_present: false,
            dynamic_v2_candidate_swaps: Vec::new(),
            best_position: None,
            is_mint: None,
            fill_data_present: false,
            fill_data: Vec::new(),
            lst_amounts_present: false,
            lst_amounts: Vec::new(),
            seed: None,
            auth_amount_in: None,
            auth: None,
            amount_is_token_a: None,
            is_base_in: None,
            swap_type: None,
            max_split_quote_calls: None,
            max_split_candidates: None,
            claim_cashback: None,
        }
    }
}

impl Default for ClickHouseSwap {
    fn default() -> Self {
        Self::new("Saber".to_string())
    }
}

impl From<&crate::types::Swap> for ClickHouseSwap {
    fn from(value: &crate::types::Swap) -> Self {
        let mut row = match value {
            crate::types::Swap::Saber => Self::new("Saber".to_string()),
            crate::types::Swap::SaberAddDecimalsDeposit => {
                Self::new("SaberAddDecimalsDeposit".to_string())
            }
            crate::types::Swap::SaberAddDecimalsWithdraw => {
                Self::new("SaberAddDecimalsWithdraw".to_string())
            }
            crate::types::Swap::TokenSwap => Self::new("TokenSwap".to_string()),
            crate::types::Swap::Sencha => Self::new("Sencha".to_string()),
            crate::types::Swap::Step => Self::new("Step".to_string()),
            crate::types::Swap::Cropper => Self::new("Cropper".to_string()),
            crate::types::Swap::Raydium => Self::new("Raydium".to_string()),
            crate::types::Swap::Crema { .. } => Self::new("Crema".to_string()),
            crate::types::Swap::Lifinity => Self::new("Lifinity".to_string()),
            crate::types::Swap::Mercurial => Self::new("Mercurial".to_string()),
            crate::types::Swap::Cykura => Self::new("Cykura".to_string()),
            crate::types::Swap::Serum { .. } => Self::new("Serum".to_string()),
            crate::types::Swap::MarinadeDeposit => Self::new("MarinadeDeposit".to_string()),
            crate::types::Swap::MarinadeUnstake => Self::new("MarinadeUnstake".to_string()),
            crate::types::Swap::Aldrin { .. } => Self::new("Aldrin".to_string()),
            crate::types::Swap::AldrinV2 { .. } => Self::new("AldrinV2".to_string()),
            crate::types::Swap::Whirlpool { .. } => Self::new("Whirlpool".to_string()),
            crate::types::Swap::Invariant { .. } => Self::new("Invariant".to_string()),
            crate::types::Swap::Meteora => Self::new("Meteora".to_string()),
            crate::types::Swap::GooseFX => Self::new("GooseFX".to_string()),
            crate::types::Swap::DeltaFi { .. } => Self::new("DeltaFi".to_string()),
            crate::types::Swap::Balansol => Self::new("Balansol".to_string()),
            crate::types::Swap::MarcoPolo { .. } => Self::new("MarcoPolo".to_string()),
            crate::types::Swap::Dradex { .. } => Self::new("Dradex".to_string()),
            crate::types::Swap::LifinityV2 => Self::new("LifinityV2".to_string()),
            crate::types::Swap::RaydiumClmm => Self::new("RaydiumClmm".to_string()),
            crate::types::Swap::Openbook { .. } => Self::new("Openbook".to_string()),
            crate::types::Swap::Phoenix { .. } => Self::new("Phoenix".to_string()),
            crate::types::Swap::Symmetry { .. } => Self::new("Symmetry".to_string()),
            crate::types::Swap::TokenSwapV2 => Self::new("TokenSwapV2".to_string()),
            crate::types::Swap::HeliumTreasuryManagementRedeemV0 => {
                Self::new("HeliumTreasuryManagementRedeemV0".to_string())
            }
            crate::types::Swap::StakeDexStakeWrappedSol => {
                Self::new("StakeDexStakeWrappedSol".to_string())
            }
            crate::types::Swap::StakeDexSwapViaStake { .. } => {
                Self::new("StakeDexSwapViaStake".to_string())
            }
            crate::types::Swap::GooseFXV2 => Self::new("GooseFXV2".to_string()),
            crate::types::Swap::Perps => Self::new("Perps".to_string()),
            crate::types::Swap::PerpsAddLiquidity => Self::new("PerpsAddLiquidity".to_string()),
            crate::types::Swap::PerpsRemoveLiquidity => {
                Self::new("PerpsRemoveLiquidity".to_string())
            }
            crate::types::Swap::MeteoraDlmm => Self::new("MeteoraDlmm".to_string()),
            crate::types::Swap::OpenBookV2 { .. } => Self::new("OpenBookV2".to_string()),
            crate::types::Swap::RaydiumClmmV2 => Self::new("RaydiumClmmV2".to_string()),
            crate::types::Swap::StakeDexPrefundWithdrawStakeAndDepositStake { .. } => {
                Self::new("StakeDexPrefundWithdrawStakeAndDepositStake".to_string())
            }
            crate::types::Swap::Clone { .. } => Self::new("Clone".to_string()),
            crate::types::Swap::SanctumS { .. } => Self::new("SanctumS".to_string()),
            crate::types::Swap::SanctumSAddLiquidity { .. } => {
                Self::new("SanctumSAddLiquidity".to_string())
            }
            crate::types::Swap::SanctumSRemoveLiquidity { .. } => {
                Self::new("SanctumSRemoveLiquidity".to_string())
            }
            crate::types::Swap::RaydiumCP => Self::new("RaydiumCP".to_string()),
            crate::types::Swap::WhirlpoolSwapV2 { .. } => Self::new("WhirlpoolSwapV2".to_string()),
            crate::types::Swap::OneIntro => Self::new("OneIntro".to_string()),
            crate::types::Swap::PumpWrappedBuy => Self::new("PumpWrappedBuy".to_string()),
            crate::types::Swap::PumpWrappedSell => Self::new("PumpWrappedSell".to_string()),
            crate::types::Swap::PerpsV2 => Self::new("PerpsV2".to_string()),
            crate::types::Swap::PerpsV2AddLiquidity => Self::new("PerpsV2AddLiquidity".to_string()),
            crate::types::Swap::PerpsV2RemoveLiquidity => {
                Self::new("PerpsV2RemoveLiquidity".to_string())
            }
            crate::types::Swap::MoonshotWrappedBuy => Self::new("MoonshotWrappedBuy".to_string()),
            crate::types::Swap::MoonshotWrappedSell => Self::new("MoonshotWrappedSell".to_string()),
            crate::types::Swap::StabbleStableSwap => Self::new("StabbleStableSwap".to_string()),
            crate::types::Swap::StabbleWeightedSwap => Self::new("StabbleWeightedSwap".to_string()),
            crate::types::Swap::Obric { .. } => Self::new("Obric".to_string()),
            crate::types::Swap::FoxBuyFromEstimatedCost => {
                Self::new("FoxBuyFromEstimatedCost".to_string())
            }
            crate::types::Swap::FoxClaimPartial { .. } => Self::new("FoxClaimPartial".to_string()),
            crate::types::Swap::SolFi { .. } => Self::new("SolFi".to_string()),
            crate::types::Swap::SolayerDelegateNoInit => {
                Self::new("SolayerDelegateNoInit".to_string())
            }
            crate::types::Swap::SolayerUndelegateNoInit => {
                Self::new("SolayerUndelegateNoInit".to_string())
            }
            crate::types::Swap::TokenMill { .. } => Self::new("TokenMill".to_string()),
            crate::types::Swap::DaosFunBuy => Self::new("DaosFunBuy".to_string()),
            crate::types::Swap::DaosFunSell => Self::new("DaosFunSell".to_string()),
            crate::types::Swap::ZeroFi => Self::new("ZeroFi".to_string()),
            crate::types::Swap::StakeDexWithdrawWrappedSol => {
                Self::new("StakeDexWithdrawWrappedSol".to_string())
            }
            crate::types::Swap::VirtualsBuy => Self::new("VirtualsBuy".to_string()),
            crate::types::Swap::VirtualsSell => Self::new("VirtualsSell".to_string()),
            crate::types::Swap::Perena { .. } => Self::new("Perena".to_string()),
            crate::types::Swap::PumpSwapBuy => Self::new("PumpSwapBuy".to_string()),
            crate::types::Swap::PumpSwapSell => Self::new("PumpSwapSell".to_string()),
            crate::types::Swap::Gamma => Self::new("Gamma".to_string()),
            crate::types::Swap::MeteoraDlmmSwapV2 { .. } => {
                Self::new("MeteoraDlmmSwapV2".to_string())
            }
            crate::types::Swap::Woofi => Self::new("Woofi".to_string()),
            crate::types::Swap::MeteoraDammV2 => Self::new("MeteoraDammV2".to_string()),
            crate::types::Swap::MeteoraDynamicBondingCurveSwap => {
                Self::new("MeteoraDynamicBondingCurveSwap".to_string())
            }
            crate::types::Swap::StabbleStableSwapV2 => Self::new("StabbleStableSwapV2".to_string()),
            crate::types::Swap::StabbleWeightedSwapV2 => {
                Self::new("StabbleWeightedSwapV2".to_string())
            }
            crate::types::Swap::RaydiumLaunchlabBuy { .. } => {
                Self::new("RaydiumLaunchlabBuy".to_string())
            }
            crate::types::Swap::RaydiumLaunchlabSell { .. } => {
                Self::new("RaydiumLaunchlabSell".to_string())
            }
            crate::types::Swap::BoopdotfunWrappedBuy => {
                Self::new("BoopdotfunWrappedBuy".to_string())
            }
            crate::types::Swap::BoopdotfunWrappedSell => {
                Self::new("BoopdotfunWrappedSell".to_string())
            }
            crate::types::Swap::Plasma { .. } => Self::new("Plasma".to_string()),
            crate::types::Swap::GoonFi { .. } => Self::new("GoonFi".to_string()),
            crate::types::Swap::HumidiFi { .. } => Self::new("HumidiFi".to_string()),
            crate::types::Swap::MeteoraDynamicBondingCurveSwapWithRemainingAccounts => {
                Self::new("MeteoraDynamicBondingCurveSwapWithRemainingAccounts".to_string())
            }
            crate::types::Swap::TesseraV { .. } => Self::new("TesseraV".to_string()),
            crate::types::Swap::PumpWrappedBuyV2 => Self::new("PumpWrappedBuyV2".to_string()),
            crate::types::Swap::PumpWrappedSellV2 => Self::new("PumpWrappedSellV2".to_string()),
            crate::types::Swap::PumpSwapBuyV2 => Self::new("PumpSwapBuyV2".to_string()),
            crate::types::Swap::PumpSwapSellV2 => Self::new("PumpSwapSellV2".to_string()),
            crate::types::Swap::Heaven { .. } => Self::new("Heaven".to_string()),
            crate::types::Swap::SolFiV2 { .. } => Self::new("SolFiV2".to_string()),
            crate::types::Swap::Aquifer => Self::new("Aquifer".to_string()),
            crate::types::Swap::PumpWrappedBuyV3 => Self::new("PumpWrappedBuyV3".to_string()),
            crate::types::Swap::PumpWrappedSellV3 => Self::new("PumpWrappedSellV3".to_string()),
            crate::types::Swap::PumpSwapBuyV3 => Self::new("PumpSwapBuyV3".to_string()),
            crate::types::Swap::PumpSwapSellV3 => Self::new("PumpSwapSellV3".to_string()),
            crate::types::Swap::JupiterLendDeposit => Self::new("JupiterLendDeposit".to_string()),
            crate::types::Swap::JupiterLendRedeem => Self::new("JupiterLendRedeem".to_string()),
            crate::types::Swap::DefiTuna { .. } => Self::new("DefiTuna".to_string()),
            crate::types::Swap::AlphaQ { .. } => Self::new("AlphaQ".to_string()),
            crate::types::Swap::RaydiumV2 => Self::new("RaydiumV2".to_string()),
            crate::types::Swap::SarosDlmm { .. } => Self::new("SarosDlmm".to_string()),
            crate::types::Swap::Futarchy { .. } => Self::new("Futarchy".to_string()),
            crate::types::Swap::MeteoraDammV2WithRemainingAccounts => {
                Self::new("MeteoraDammV2WithRemainingAccounts".to_string())
            }
            crate::types::Swap::Obsidian => Self::new("Obsidian".to_string()),
            crate::types::Swap::WhaleStreet { .. } => Self::new("WhaleStreet".to_string()),
            crate::types::Swap::DynamicV1 { .. } => Self::new("DynamicV1".to_string()),
            crate::types::Swap::PumpWrappedBuyV4 => Self::new("PumpWrappedBuyV4".to_string()),
            crate::types::Swap::PumpWrappedSellV4 => Self::new("PumpWrappedSellV4".to_string()),
            crate::types::Swap::CarrotIssue => Self::new("CarrotIssue".to_string()),
            crate::types::Swap::CarrotRedeem => Self::new("CarrotRedeem".to_string()),
            crate::types::Swap::Manifest { .. } => Self::new("Manifest".to_string()),
            crate::types::Swap::BisonFi { .. } => Self::new("BisonFi".to_string()),
            crate::types::Swap::HumidiFiV2 { .. } => Self::new("HumidiFiV2".to_string()),
            crate::types::Swap::PerenaStar { .. } => Self::new("PerenaStar".to_string()),
            crate::types::Swap::JupiterRfqV2 { .. } => Self::new("JupiterRfqV2".to_string()),
            crate::types::Swap::GoonFiV2 { .. } => Self::new("GoonFiV2".to_string()),
            crate::types::Swap::Scorch { .. } => Self::new("Scorch".to_string()),
            crate::types::Swap::VaultLiquidUnstake { .. } => {
                Self::new("VaultLiquidUnstake".to_string())
            }
            crate::types::Swap::XOrca => Self::new("XOrca".to_string()),
            crate::types::Swap::Quantum { .. } => Self::new("Quantum".to_string()),
            crate::types::Swap::WhaleStreetV2 { .. } => Self::new("WhaleStreetV2".to_string()),
            crate::types::Swap::Riptide { .. } => Self::new("Riptide".to_string()),
            crate::types::Swap::RunnerRodeo => Self::new("RunnerRodeo".to_string()),
            crate::types::Swap::TaurusFi { .. } => Self::new("TaurusFi".to_string()),
            crate::types::Swap::Omnipair => Self::new("Omnipair".to_string()),
            crate::types::Swap::MSwap => Self::new("MSwap".to_string()),
            crate::types::Swap::Hylo { .. } => Self::new("Hylo".to_string()),
            crate::types::Swap::VoltrDeposit => Self::new("VoltrDeposit".to_string()),
            crate::types::Swap::VoltrWithdraw => Self::new("VoltrWithdraw".to_string()),
            crate::types::Swap::SanctumSV2 { .. } => Self::new("SanctumSV2".to_string()),
            crate::types::Swap::LemmingsFi { .. } => Self::new("LemmingsFi".to_string()),
            crate::types::Swap::ScaleVmmBuy => Self::new("ScaleVmmBuy".to_string()),
            crate::types::Swap::ScaleVmmSell => Self::new("ScaleVmmSell".to_string()),
            crate::types::Swap::ScaleAmmBuy => Self::new("ScaleAmmBuy".to_string()),
            crate::types::Swap::ScaleAmmSell => Self::new("ScaleAmmSell".to_string()),
            crate::types::Swap::BisonFiV2 { .. } => Self::new("BisonFiV2".to_string()),
            crate::types::Swap::Trends => Self::new("Trends".to_string()),
            crate::types::Swap::HumaDeposit => Self::new("HumaDeposit".to_string()),
            crate::types::Swap::HumaInstantWithdraw => Self::new("HumaInstantWithdraw".to_string()),
            crate::types::Swap::Kipseli { .. } => Self::new("Kipseli".to_string()),
            crate::types::Swap::DynamicV2 { .. } => Self::new("DynamicV2".to_string()),
            crate::types::Swap::PumpSwapBuyV3WithCashbackClaim => {
                Self::new("PumpSwapBuyV3WithCashbackClaim".to_string())
            }
            crate::types::Swap::PumpSwapSellV3WithCashbackClaim => {
                Self::new("PumpSwapSellV3WithCashbackClaim".to_string())
            }
            crate::types::Swap::PumpWrappedBuyV4WithCashbackClaim => {
                Self::new("PumpWrappedBuyV4WithCashbackClaim".to_string())
            }
            crate::types::Swap::PumpWrappedSellV4WithCashbackClaim => {
                Self::new("PumpWrappedSellV4WithCashbackClaim".to_string())
            }
            crate::types::Swap::GoonFiV3 { .. } => Self::new("GoonFiV3".to_string()),
            crate::types::Swap::PumpWrappedBuyV5 { .. } => {
                Self::new("PumpWrappedBuyV5".to_string())
            }
            crate::types::Swap::PumpWrappedSellV5 { .. } => {
                Self::new("PumpWrappedSellV5".to_string())
            }
            crate::types::Swap::ZeroFiSwapV2 => Self::new("ZeroFiSwapV2".to_string()),
        };

        let _ = &mut row;
        match value {
            crate::types::Swap::Saber => {}
            crate::types::Swap::SaberAddDecimalsDeposit => {}
            crate::types::Swap::SaberAddDecimalsWithdraw => {}
            crate::types::Swap::TokenSwap => {}
            crate::types::Swap::Sencha => {}
            crate::types::Swap::Step => {}
            crate::types::Swap::Cropper => {}
            crate::types::Swap::Raydium => {}
            crate::types::Swap::Crema { a_to_b } => {
                row.a_to_b = Some(*a_to_b);
            }
            crate::types::Swap::Lifinity => {}
            crate::types::Swap::Mercurial => {}
            crate::types::Swap::Cykura => {}
            crate::types::Swap::Serum { side } => {
                row.side = Some(clickhouse_enum_variant(side));
            }
            crate::types::Swap::MarinadeDeposit => {}
            crate::types::Swap::MarinadeUnstake => {}
            crate::types::Swap::Aldrin { side } => {
                row.side = Some(clickhouse_enum_variant(side));
            }
            crate::types::Swap::AldrinV2 { side } => {
                row.side = Some(clickhouse_enum_variant(side));
            }
            crate::types::Swap::Whirlpool { a_to_b } => {
                row.a_to_b = Some(*a_to_b);
            }
            crate::types::Swap::Invariant { x_to_y } => {
                row.x_to_y = Some(*x_to_y);
            }
            crate::types::Swap::Meteora => {}
            crate::types::Swap::GooseFX => {}
            crate::types::Swap::DeltaFi { stable } => {
                row.stable = Some(*stable);
            }
            crate::types::Swap::Balansol => {}
            crate::types::Swap::MarcoPolo { x_to_y } => {
                row.x_to_y = Some(*x_to_y);
            }
            crate::types::Swap::Dradex { side } => {
                row.side = Some(clickhouse_enum_variant(side));
            }
            crate::types::Swap::LifinityV2 => {}
            crate::types::Swap::RaydiumClmm => {}
            crate::types::Swap::Openbook { side } => {
                row.side = Some(clickhouse_enum_variant(side));
            }
            crate::types::Swap::Phoenix { side } => {
                row.side = Some(clickhouse_enum_variant(side));
            }
            crate::types::Swap::Symmetry {
                from_token_id,
                to_token_id,
            } => {
                row.from_token_id = Some(*from_token_id);
                row.to_token_id = Some(*to_token_id);
            }
            crate::types::Swap::TokenSwapV2 => {}
            crate::types::Swap::HeliumTreasuryManagementRedeemV0 => {}
            crate::types::Swap::StakeDexStakeWrappedSol => {}
            crate::types::Swap::StakeDexSwapViaStake { bridge_stake_seed } => {
                row.bridge_stake_seed = Some(*bridge_stake_seed);
            }
            crate::types::Swap::GooseFXV2 => {}
            crate::types::Swap::Perps => {}
            crate::types::Swap::PerpsAddLiquidity => {}
            crate::types::Swap::PerpsRemoveLiquidity => {}
            crate::types::Swap::MeteoraDlmm => {}
            crate::types::Swap::OpenBookV2 { side } => {
                row.side = Some(clickhouse_enum_variant(side));
            }
            crate::types::Swap::RaydiumClmmV2 => {}
            crate::types::Swap::StakeDexPrefundWithdrawStakeAndDepositStake {
                bridge_stake_seed,
            } => {
                row.bridge_stake_seed = Some(*bridge_stake_seed);
            }
            crate::types::Swap::Clone {
                pool_index,
                quantity_is_input,
                quantity_is_collateral,
            } => {
                row.pool_index = Some(*pool_index);
                row.quantity_is_input = Some(*quantity_is_input);
                row.quantity_is_collateral = Some(*quantity_is_collateral);
            }
            crate::types::Swap::SanctumS {
                src_lst_value_calc_accs,
                dst_lst_value_calc_accs,
                src_lst_index,
                dst_lst_index,
            } => {
                row.src_lst_value_calc_accs = Some(*src_lst_value_calc_accs);
                row.dst_lst_value_calc_accs = Some(*dst_lst_value_calc_accs);
                row.src_lst_index = Some(*src_lst_index);
                row.dst_lst_index = Some(*dst_lst_index);
            }
            crate::types::Swap::SanctumSAddLiquidity {
                lst_value_calc_accs,
                lst_index,
            } => {
                row.lst_value_calc_accs = Some(*lst_value_calc_accs);
                row.lst_index = Some(*lst_index);
            }
            crate::types::Swap::SanctumSRemoveLiquidity {
                lst_value_calc_accs,
                lst_index,
            } => {
                row.lst_value_calc_accs = Some(*lst_value_calc_accs);
                row.lst_index = Some(*lst_index);
            }
            crate::types::Swap::RaydiumCP => {}
            crate::types::Swap::WhirlpoolSwapV2 {
                a_to_b,
                remaining_accounts_info,
            } => {
                row.a_to_b = Some(*a_to_b);
                if let Some(value) = remaining_accounts_info.as_ref() {
                    row.remaining_accounts_info_present = true;
                    row.remaining_accounts_info = ClickHouseRemainingAccountsInfo::from(value);
                }
            }
            crate::types::Swap::OneIntro => {}
            crate::types::Swap::PumpWrappedBuy => {}
            crate::types::Swap::PumpWrappedSell => {}
            crate::types::Swap::PerpsV2 => {}
            crate::types::Swap::PerpsV2AddLiquidity => {}
            crate::types::Swap::PerpsV2RemoveLiquidity => {}
            crate::types::Swap::MoonshotWrappedBuy => {}
            crate::types::Swap::MoonshotWrappedSell => {}
            crate::types::Swap::StabbleStableSwap => {}
            crate::types::Swap::StabbleWeightedSwap => {}
            crate::types::Swap::Obric { x_to_y } => {
                row.x_to_y = Some(*x_to_y);
            }
            crate::types::Swap::FoxBuyFromEstimatedCost => {}
            crate::types::Swap::FoxClaimPartial { is_y } => {
                row.is_y = Some(*is_y);
            }
            crate::types::Swap::SolFi { is_quote_to_base } => {
                row.is_quote_to_base = Some(*is_quote_to_base);
            }
            crate::types::Swap::SolayerDelegateNoInit => {}
            crate::types::Swap::SolayerUndelegateNoInit => {}
            crate::types::Swap::TokenMill { side } => {
                row.side = Some(clickhouse_enum_variant(side));
            }
            crate::types::Swap::DaosFunBuy => {}
            crate::types::Swap::DaosFunSell => {}
            crate::types::Swap::ZeroFi => {}
            crate::types::Swap::StakeDexWithdrawWrappedSol => {}
            crate::types::Swap::VirtualsBuy => {}
            crate::types::Swap::VirtualsSell => {}
            crate::types::Swap::Perena {
                in_index,
                out_index,
            } => {
                row.in_index = Some(*in_index);
                row.out_index = Some(*out_index);
            }
            crate::types::Swap::PumpSwapBuy => {}
            crate::types::Swap::PumpSwapSell => {}
            crate::types::Swap::Gamma => {}
            crate::types::Swap::MeteoraDlmmSwapV2 {
                remaining_accounts_info,
            } => {
                row.remaining_accounts_info_present = true;
                row.remaining_accounts_info =
                    ClickHouseRemainingAccountsInfo::from(remaining_accounts_info);
            }
            crate::types::Swap::Woofi => {}
            crate::types::Swap::MeteoraDammV2 => {}
            crate::types::Swap::MeteoraDynamicBondingCurveSwap => {}
            crate::types::Swap::StabbleStableSwapV2 => {}
            crate::types::Swap::StabbleWeightedSwapV2 => {}
            crate::types::Swap::RaydiumLaunchlabBuy { share_fee_rate } => {
                row.share_fee_rate = Some(*share_fee_rate);
            }
            crate::types::Swap::RaydiumLaunchlabSell { share_fee_rate } => {
                row.share_fee_rate = Some(*share_fee_rate);
            }
            crate::types::Swap::BoopdotfunWrappedBuy => {}
            crate::types::Swap::BoopdotfunWrappedSell => {}
            crate::types::Swap::Plasma { side } => {
                row.side = Some(clickhouse_enum_variant(side));
            }
            crate::types::Swap::GoonFi {
                is_bid,
                blacklist_bump,
            } => {
                row.is_bid = Some(*is_bid);
                row.blacklist_bump = Some(*blacklist_bump);
            }
            crate::types::Swap::HumidiFi {
                swap_id,
                is_base_to_quote,
            } => {
                row.swap_id = Some(ClickHouseUInt128((*swap_id) as u128));
                row.is_base_to_quote = Some(*is_base_to_quote);
            }
            crate::types::Swap::MeteoraDynamicBondingCurveSwapWithRemainingAccounts => {}
            crate::types::Swap::TesseraV { side } => {
                row.side = Some(clickhouse_enum_variant(side));
            }
            crate::types::Swap::PumpWrappedBuyV2 => {}
            crate::types::Swap::PumpWrappedSellV2 => {}
            crate::types::Swap::PumpSwapBuyV2 => {}
            crate::types::Swap::PumpSwapSellV2 => {}
            crate::types::Swap::Heaven { a_to_b } => {
                row.a_to_b = Some(*a_to_b);
            }
            crate::types::Swap::SolFiV2 { is_quote_to_base } => {
                row.is_quote_to_base = Some(*is_quote_to_base);
            }
            crate::types::Swap::Aquifer => {}
            crate::types::Swap::PumpWrappedBuyV3 => {}
            crate::types::Swap::PumpWrappedSellV3 => {}
            crate::types::Swap::PumpSwapBuyV3 => {}
            crate::types::Swap::PumpSwapSellV3 => {}
            crate::types::Swap::JupiterLendDeposit => {}
            crate::types::Swap::JupiterLendRedeem => {}
            crate::types::Swap::DefiTuna {
                a_to_b,
                remaining_accounts_info,
            } => {
                row.a_to_b = Some(*a_to_b);
                if let Some(value) = remaining_accounts_info.as_ref() {
                    row.remaining_accounts_info_present = true;
                    row.remaining_accounts_info = ClickHouseRemainingAccountsInfo::from(value);
                }
            }
            crate::types::Swap::AlphaQ { a_to_b } => {
                row.a_to_b = Some(*a_to_b);
            }
            crate::types::Swap::RaydiumV2 => {}
            crate::types::Swap::SarosDlmm { swap_for_y } => {
                row.swap_for_y = Some(*swap_for_y);
            }
            crate::types::Swap::Futarchy { side } => {
                row.side = Some(clickhouse_enum_variant(side));
            }
            crate::types::Swap::MeteoraDammV2WithRemainingAccounts => {}
            crate::types::Swap::Obsidian => {}
            crate::types::Swap::WhaleStreet { side } => {
                row.side = Some(clickhouse_enum_variant(side));
            }
            crate::types::Swap::DynamicV1 {
                candidate_swaps,
                best_position,
            } => {
                row.dynamic_v1_candidate_swaps_present = true;
                row.dynamic_v1_candidate_swaps = candidate_swaps
                    .iter()
                    .map(|value| ClickHouseCandidateSwap::from(value))
                    .collect();
                row.best_position = best_position.as_ref().map(|value| *value);
            }
            crate::types::Swap::PumpWrappedBuyV4 => {}
            crate::types::Swap::PumpWrappedSellV4 => {}
            crate::types::Swap::CarrotIssue => {}
            crate::types::Swap::CarrotRedeem => {}
            crate::types::Swap::Manifest { side } => {
                row.side = Some(clickhouse_enum_variant(side));
            }
            crate::types::Swap::BisonFi { a_to_b } => {
                row.a_to_b = Some(*a_to_b);
            }
            crate::types::Swap::HumidiFiV2 {
                swap_id,
                is_base_to_quote,
            } => {
                row.swap_id = Some(ClickHouseUInt128((*swap_id) as u128));
                row.is_base_to_quote = Some(*is_base_to_quote);
            }
            crate::types::Swap::PerenaStar { is_mint } => {
                row.is_mint = Some(*is_mint);
            }
            crate::types::Swap::JupiterRfqV2 { side, fill_data } => {
                row.side = Some(clickhouse_enum_variant(side));
                row.fill_data_present = true;
                row.fill_data = fill_data.to_vec();
            }
            crate::types::Swap::GoonFiV2 { is_bid } => {
                row.is_bid = Some(*is_bid);
            }
            crate::types::Swap::Scorch { swap_id } => {
                row.swap_id = Some(ClickHouseUInt128(*swap_id));
            }
            crate::types::Swap::VaultLiquidUnstake { lst_amounts, seed } => {
                row.lst_amounts_present = true;
                row.lst_amounts = lst_amounts.iter().map(|value| *value).collect();
                row.seed = Some(*seed);
            }
            crate::types::Swap::XOrca => {}
            crate::types::Swap::Quantum { side } => {
                row.side = Some(clickhouse_enum_variant(side));
            }
            crate::types::Swap::WhaleStreetV2 {
                side,
                auth_amount_in,
                auth,
            } => {
                row.side = Some(clickhouse_enum_variant(side));
                row.auth_amount_in = Some(*auth_amount_in);
                row.auth = Some(*auth);
            }
            crate::types::Swap::Riptide { amount_is_token_a } => {
                row.amount_is_token_a = Some(*amount_is_token_a);
            }
            crate::types::Swap::RunnerRodeo => {}
            crate::types::Swap::TaurusFi { is_base_in } => {
                row.is_base_in = Some(*is_base_in);
            }
            crate::types::Swap::Omnipair => {}
            crate::types::Swap::MSwap => {}
            crate::types::Swap::Hylo { swap_type } => {
                row.swap_type = Some(clickhouse_enum_variant(swap_type));
            }
            crate::types::Swap::VoltrDeposit => {}
            crate::types::Swap::VoltrWithdraw => {}
            crate::types::Swap::SanctumSV2 {
                src_lst_value_calc_accs,
                dst_lst_value_calc_accs,
                src_lst_index,
                dst_lst_index,
            } => {
                row.src_lst_value_calc_accs = Some(*src_lst_value_calc_accs);
                row.dst_lst_value_calc_accs = Some(*dst_lst_value_calc_accs);
                row.src_lst_index = Some(*src_lst_index);
                row.dst_lst_index = Some(*dst_lst_index);
            }
            crate::types::Swap::LemmingsFi { is_base_in } => {
                row.is_base_in = Some(*is_base_in);
            }
            crate::types::Swap::ScaleVmmBuy => {}
            crate::types::Swap::ScaleVmmSell => {}
            crate::types::Swap::ScaleAmmBuy => {}
            crate::types::Swap::ScaleAmmSell => {}
            crate::types::Swap::BisonFiV2 { a_to_b } => {
                row.a_to_b = Some(*a_to_b);
            }
            crate::types::Swap::Trends => {}
            crate::types::Swap::HumaDeposit => {}
            crate::types::Swap::HumaInstantWithdraw => {}
            crate::types::Swap::Kipseli { is_base_to_quote } => {
                row.is_base_to_quote = Some(*is_base_to_quote);
            }
            crate::types::Swap::DynamicV2 {
                candidate_swaps,
                max_split_quote_calls,
                max_split_candidates,
            } => {
                row.dynamic_v2_candidate_swaps_present = true;
                row.dynamic_v2_candidate_swaps = candidate_swaps
                    .iter()
                    .map(|value| ClickHouseCandidateSwapWithBps::from(value))
                    .collect();
                row.max_split_quote_calls = Some(*max_split_quote_calls);
                row.max_split_candidates = Some(*max_split_candidates);
            }
            crate::types::Swap::PumpSwapBuyV3WithCashbackClaim => {}
            crate::types::Swap::PumpSwapSellV3WithCashbackClaim => {}
            crate::types::Swap::PumpWrappedBuyV4WithCashbackClaim => {}
            crate::types::Swap::PumpWrappedSellV4WithCashbackClaim => {}
            crate::types::Swap::GoonFiV3 { is_bid } => {
                row.is_bid = Some(*is_bid);
            }
            crate::types::Swap::PumpWrappedBuyV5 { claim_cashback } => {
                row.claim_cashback = Some(*claim_cashback);
            }
            crate::types::Swap::PumpWrappedSellV5 { claim_cashback } => {
                row.claim_cashback = Some(*claim_cashback);
            }
            crate::types::Swap::ZeroFiSwapV2 => {}
        }

        row
    }
}

#[derive(Debug, Clone, serde::Serialize)]
pub struct ClickHouseRoutePlanStep {
    pub swap: ClickHouseSwap,
    pub percent: u8,
    pub input_index: u8,
    pub output_index: u8,
}

impl Default for ClickHouseRoutePlanStep {
    fn default() -> Self {
        Self {
            swap: ClickHouseSwap::default(),
            percent: 0,
            input_index: 0,
            output_index: 0,
        }
    }
}

impl From<&crate::types::RoutePlanStep> for ClickHouseRoutePlanStep {
    fn from(value: &crate::types::RoutePlanStep) -> Self {
        Self {
            swap: ClickHouseSwap::from(&value.swap),
            percent: value.percent,
            input_index: value.input_index,
            output_index: value.output_index,
        }
    }
}

#[derive(Debug, Clone, serde::Serialize)]
pub struct ClickHouseRoutePlanStepV2 {
    pub swap: ClickHouseSwap,
    pub bps: u16,
    pub input_index: u8,
    pub output_index: u8,
}

impl Default for ClickHouseRoutePlanStepV2 {
    fn default() -> Self {
        Self {
            swap: ClickHouseSwap::default(),
            bps: 0,
            input_index: 0,
            output_index: 0,
        }
    }
}

impl From<&crate::types::RoutePlanStepV2> for ClickHouseRoutePlanStepV2 {
    fn from(value: &crate::types::RoutePlanStepV2) -> Self {
        Self {
            swap: ClickHouseSwap::from(&value.swap),
            bps: value.bps,
            input_index: value.input_index,
            output_index: value.output_index,
        }
    }
}
