#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT"

FORCE=false
if [[ "${1:-}" == "--force" ]]; then
  FORCE=true
fi

OUT="$ROOT/.env.demo.local"
if [[ -f "$OUT" && "$FORCE" != true ]]; then
  echo ".env.demo.local already exists; use --force to overwrite"
  exit 1
fi

read_env_key() {
  local file="$1"
  local key="$2"
  awk -F= -v key="$key" '
    $0 !~ /^[[:space:]]*#/ && $1 == key {
      sub(/^[^=]*=/, "", $0)
      print $0
      exit
    }
  ' "$file" 2>/dev/null || true
}

JUP_ENV="examples/jupiter-swap-clickhouse/.env"
TOK_ENV="examples/token-program-clickhouse/.env"

solana_rpc="$(read_env_key "$JUP_ENV" RPC_URL)"
database_url="$(read_env_key "$JUP_ENV" DATABASE_URL)"
start_slot="$(read_env_key "$JUP_ENV" BLOCK_CRAWLER_START_SLOT)"
end_slot="$(read_env_key "$JUP_ENV" BLOCK_CRAWLER_END_SLOT)"
jup_metrics="$(read_env_key "$JUP_ENV" PROMETHEUS_METRICS_ADDR)"
tok_metrics="$(read_env_key "$TOK_ENV" PROMETHEUS_METRICS_ADDR)"

tmp="$(mktemp)"
cat > "$tmp" <<EOF
# Generated by scripts/demo/init-env-from-examples.sh.
# Do not commit this file.
SOLANA_RPC_URL=${solana_rpc}
DATABASE_URL=${database_url:-http://carbon:carbon@localhost:8123}
JUPITER_START_SLOT=${start_slot}
JUPITER_END_SLOT=${end_slot}
JUPITER_PROMETHEUS_METRICS_ADDR=${jup_metrics:-0.0.0.0:9464}
TOKEN_PROMETHEUS_METRICS_ADDR=${tok_metrics:-0.0.0.0:9465}
ELEVENLABS_API_KEY=
ELEVENLABS_VOICE_ID=
ELEVENLABS_MODEL_ID=eleven_multilingual_v2
ELEVENLABS_OUTPUT_FORMAT=mp3_44100_128
ELEVENLABS_DISABLE_AUTO_VOICE_FALLBACK=false
ELEVENLABS_AUTO_WRITE_VOICE_ID=false
RECORDER_BACKEND=ffmpeg_x11
DEMO_DISPLAY=:95
DEMO_SCREEN_SIZE=1920x1080
DEMO_FPS=30
DEMO_VNC_PORT=5903
DEMO_NOVNC_PORT=6083
DEMO_OUTPUT_DIR=demo-artifacts
DEMO_RECORDING_DIR=demo-artifacts/recordings
DEMO_AUDIO_DIR=demo-artifacts/audio
DEMO_FINAL_VIDEO=demo-artifacts/clickhouse-sink-tutorial.mp4
OBS_WEBSOCKET_HOST=127.0.0.1
OBS_WEBSOCKET_PORT=4455
OBS_WEBSOCKET_PASSWORD=
EOF

install -m 0600 "$tmp" "$OUT"
rm -f "$tmp"

for key in \
  SOLANA_RPC_URL DATABASE_URL JUPITER_START_SLOT JUPITER_END_SLOT \
  JUPITER_PROMETHEUS_METRICS_ADDR TOKEN_PROMETHEUS_METRICS_ADDR \
  ELEVENLABS_API_KEY ELEVENLABS_VOICE_ID OBS_WEBSOCKET_PASSWORD
do
  value="$(read_env_key "$OUT" "$key")"
  if [[ -n "$value" && "$value" != \<*\> ]]; then
    echo "$key: present"
  else
    echo "$key: missing"
  fi
done

echo "Created .env.demo.local with mode 0600"
