//! This code was AUTOGENERATED using the Codama library.

#[allow(unused_imports)]
use carbon_core::clickhouse::rows::clickhouse_enum_variant;
use carbon_core::{
    clickhouse::{
        rows::{
            ClickHouseInstructionLandingMetadata, ClickHouseRowContext,
            CLICKHOUSE_INSTRUCTION_COMMON_COLUMNS,
        },
        ClickHouseColumnSpec,
    },
    instruction::InstructionMetadata,
};

#[derive(Debug, Clone, serde::Serialize)]
pub struct AmountToUiAmountInstructionClickHouseRow {
    #[serde(flatten)]
    pub metadata: ClickHouseInstructionLandingMetadata,
    pub amount: u64,
}

impl AmountToUiAmountInstructionClickHouseRow {
    pub const FAMILY_NAME: &'static str = "token_program_amount_to_ui_amount_instruction";
    pub const INSTRUCTION_TYPE: &'static str = "amount_to_ui_amount";
    pub const DEFAULT_TABLE_NAME: &'static str =
        "token_program_amount_to_ui_amount_instruction_landing";
    pub const COMMON_COLUMNS: &'static [ClickHouseColumnSpec] =
        CLICKHOUSE_INSTRUCTION_COMMON_COLUMNS;
    pub const PAYLOAD_COLUMNS: &'static [ClickHouseColumnSpec] =
        &[ClickHouseColumnSpec::new("amount", r#"UInt64"#)];

    pub fn from_parts(
        source: crate::instructions::amount_to_ui_amount::AmountToUiAmount,
        metadata: &InstructionMetadata,
        context: &ClickHouseRowContext,
    ) -> Self {
        let _ = &source;

        Self {
            metadata: ClickHouseInstructionLandingMetadata::new(
                crate::PROGRAM_ID.as_ref(),
                crate::PROGRAM_ID.to_string(),
                Self::FAMILY_NAME,
                Self::INSTRUCTION_TYPE,
                metadata,
                context,
            ),
            amount: source.amount,
        }
    }
}

carbon_core::impl_clickhouse_instruction_row!(AmountToUiAmountInstructionClickHouseRow);
