//! This code was AUTOGENERATED using the Codama library.

#[allow(unused_imports)]
use carbon_core::clickhouse::rows::clickhouse_enum_variant;
use {
    super::types::*,
    carbon_core::{
        clickhouse::{
            rows::{
                ClickHouseInstructionLandingMetadata, ClickHouseRowContext,
                CLICKHOUSE_INSTRUCTION_COMMON_COLUMNS,
            },
            ClickHouseColumnSpec,
        },
        instruction::InstructionMetadata,
    },
};

#[derive(Debug, Clone, serde::Serialize)]
pub struct BatchInstructionClickHouseRow {
    #[serde(flatten)]
    pub metadata: ClickHouseInstructionLandingMetadata,
    pub data: Vec<ClickHouseBatchItem>,
}

impl BatchInstructionClickHouseRow {
    pub const FAMILY_NAME: &'static str = "token_program_batch_instruction";
    pub const INSTRUCTION_TYPE: &'static str = "batch";
    pub const DEFAULT_TABLE_NAME: &'static str = "token_program_batch_instruction_landing";
    pub const COMMON_COLUMNS: &'static [ClickHouseColumnSpec] =
        CLICKHOUSE_INSTRUCTION_COMMON_COLUMNS;
    pub const PAYLOAD_COLUMNS: &'static [ClickHouseColumnSpec] = &[ClickHouseColumnSpec::new(
        "data",
        r#"Array(Tuple(number_of_accounts UInt8, instruction_data Array(UInt8)))"#,
    )];

    pub fn from_parts(
        source: crate::instructions::batch::Batch,
        metadata: &InstructionMetadata,
        context: &ClickHouseRowContext,
    ) -> Self {
        let _ = &source;

        Self {
            metadata: ClickHouseInstructionLandingMetadata::new(
                crate::PROGRAM_ID.as_ref(),
                crate::PROGRAM_ID.to_string(),
                Self::FAMILY_NAME,
                Self::INSTRUCTION_TYPE,
                metadata,
                context,
            ),
            data: source
                .data
                .iter()
                .map(|value| ClickHouseBatchItem::from(value))
                .collect(),
        }
    }
}

carbon_core::impl_clickhouse_instruction_row!(BatchInstructionClickHouseRow);
