//! This code was AUTOGENERATED using the Codama library.

#[allow(unused_imports)]
use carbon_core::clickhouse::rows::clickhouse_enum_variant;
use carbon_core::{
    clickhouse::{
        rows::{
            ClickHouseInstructionLandingMetadata, ClickHouseRowContext,
            CLICKHOUSE_INSTRUCTION_COMMON_COLUMNS,
        },
        ClickHouseColumnSpec,
    },
    instruction::InstructionMetadata,
};

#[derive(Debug, Clone, serde::Serialize)]
pub struct InitializeMintInstructionClickHouseRow {
    #[serde(flatten)]
    pub metadata: ClickHouseInstructionLandingMetadata,
    pub decimals: u8,
    pub mint_authority: String,
    pub freeze_authority: Option<String>,
}

impl InitializeMintInstructionClickHouseRow {
    pub const FAMILY_NAME: &'static str = "token_program_initialize_mint_instruction";
    pub const INSTRUCTION_TYPE: &'static str = "initialize_mint";
    pub const DEFAULT_TABLE_NAME: &'static str =
        "token_program_initialize_mint_instruction_landing";
    pub const COMMON_COLUMNS: &'static [ClickHouseColumnSpec] =
        CLICKHOUSE_INSTRUCTION_COMMON_COLUMNS;
    pub const PAYLOAD_COLUMNS: &'static [ClickHouseColumnSpec] = &[
        ClickHouseColumnSpec::new("decimals", r#"UInt8"#),
        ClickHouseColumnSpec::new("mint_authority", r#"String"#),
        ClickHouseColumnSpec::new("freeze_authority", r#"Nullable(String)"#),
    ];

    pub fn from_parts(
        source: crate::instructions::initialize_mint::InitializeMint,
        metadata: &InstructionMetadata,
        context: &ClickHouseRowContext,
    ) -> Self {
        let _ = &source;

        Self {
            metadata: ClickHouseInstructionLandingMetadata::new(
                crate::PROGRAM_ID.as_ref(),
                crate::PROGRAM_ID.to_string(),
                Self::FAMILY_NAME,
                Self::INSTRUCTION_TYPE,
                metadata,
                context,
            ),
            decimals: source.decimals,
            mint_authority: source.mint_authority.to_string(),
            freeze_authority: source
                .freeze_authority
                .as_ref()
                .map(|value| value.to_string()),
        }
    }
}

carbon_core::impl_clickhouse_instruction_row!(
    InitializeMintInstructionClickHouseRow,
    super::clickhouse_instruction_table_options
);
