//! This code was AUTOGENERATED using the Codama library.

#[allow(unused_imports)]
use carbon_core::clickhouse::rows::clickhouse_enum_variant;
use carbon_core::{
    clickhouse::{
        rows::{
            ClickHouseInstructionLandingMetadata, ClickHouseRowContext,
            CLICKHOUSE_INSTRUCTION_COMMON_COLUMNS,
        },
        ClickHouseColumnSpec,
    },
    instruction::InstructionMetadata,
};

#[derive(Debug, Clone, serde::Serialize)]
pub struct InitializeAccount3InstructionClickHouseRow {
    #[serde(flatten)]
    pub metadata: ClickHouseInstructionLandingMetadata,
    pub owner: String,
}

impl InitializeAccount3InstructionClickHouseRow {
    pub const FAMILY_NAME: &'static str = "token_program_initialize_account3_instruction";
    pub const INSTRUCTION_TYPE: &'static str = "initialize_account3";
    pub const DEFAULT_TABLE_NAME: &'static str =
        "token_program_initialize_account3_instruction_landing";
    pub const COMMON_COLUMNS: &'static [ClickHouseColumnSpec] =
        CLICKHOUSE_INSTRUCTION_COMMON_COLUMNS;
    pub const PAYLOAD_COLUMNS: &'static [ClickHouseColumnSpec] =
        &[ClickHouseColumnSpec::new("owner", r#"String"#)];

    pub fn from_parts(
        source: crate::instructions::initialize_account3::InitializeAccount3,
        metadata: &InstructionMetadata,
        context: &ClickHouseRowContext,
    ) -> Self {
        let _ = &source;

        Self {
            metadata: ClickHouseInstructionLandingMetadata::new(
                crate::PROGRAM_ID.as_ref(),
                crate::PROGRAM_ID.to_string(),
                Self::FAMILY_NAME,
                Self::INSTRUCTION_TYPE,
                metadata,
                context,
            ),
            owner: source.owner.to_string(),
        }
    }
}

carbon_core::impl_clickhouse_instruction_row!(InitializeAccount3InstructionClickHouseRow);
