//! This code was AUTOGENERATED using the Codama library.

#[allow(unused_imports)]
use carbon_core::clickhouse::rows::clickhouse_enum_variant;
use carbon_core::{
    clickhouse::{
        rows::{
            ClickHouseInstructionLandingMetadata, ClickHouseRowContext,
            CLICKHOUSE_INSTRUCTION_COMMON_COLUMNS,
        },
        ClickHouseColumnSpec,
    },
    instruction::InstructionMetadata,
};

#[derive(Debug, Clone, serde::Serialize)]
pub struct InitializeMultisigInstructionClickHouseRow {
    #[serde(flatten)]
    pub metadata: ClickHouseInstructionLandingMetadata,
    pub m: u8,
}

impl InitializeMultisigInstructionClickHouseRow {
    pub const FAMILY_NAME: &'static str = "token_program_initialize_multisig_instruction";
    pub const INSTRUCTION_TYPE: &'static str = "initialize_multisig";
    pub const DEFAULT_TABLE_NAME: &'static str =
        "token_program_initialize_multisig_instruction_landing";
    pub const COMMON_COLUMNS: &'static [ClickHouseColumnSpec] =
        CLICKHOUSE_INSTRUCTION_COMMON_COLUMNS;
    pub const PAYLOAD_COLUMNS: &'static [ClickHouseColumnSpec] =
        &[ClickHouseColumnSpec::new("m", r#"UInt8"#)];

    pub fn from_parts(
        source: crate::instructions::initialize_multisig::InitializeMultisig,
        metadata: &InstructionMetadata,
        context: &ClickHouseRowContext,
    ) -> Self {
        let _ = &source;

        Self {
            metadata: ClickHouseInstructionLandingMetadata::new(
                crate::PROGRAM_ID.as_ref(),
                crate::PROGRAM_ID.to_string(),
                Self::FAMILY_NAME,
                Self::INSTRUCTION_TYPE,
                metadata,
                context,
            ),
            m: source.m,
        }
    }
}

carbon_core::impl_clickhouse_instruction_row!(InitializeMultisigInstructionClickHouseRow);
