//! This code was AUTOGENERATED using the Codama library.
pub mod amount_to_ui_amount_row;
pub mod approve_checked_row;
pub mod approve_row;
pub mod batch_row;
pub mod burn_checked_row;
pub mod burn_row;
pub mod close_account_row;
pub mod freeze_account_row;
pub mod get_account_data_size_row;
pub mod initialize_account2_row;
pub mod initialize_account3_row;
pub mod initialize_account_row;
pub mod initialize_immutable_owner_row;
pub mod initialize_mint2_row;
pub mod initialize_mint_row;
pub mod initialize_multisig2_row;
pub mod initialize_multisig_row;
pub mod mint_to_checked_row;
pub mod mint_to_row;
pub mod revoke_row;
pub mod set_authority_row;
pub mod sync_native_row;
pub mod thaw_account_row;
pub mod transfer_checked_row;
pub mod transfer_row;
pub mod types;
pub mod ui_amount_to_amount_row;
pub mod unwrap_lamports_row;
pub mod withdraw_excess_lamports_row;

pub use self::{
    amount_to_ui_amount_row::AmountToUiAmountInstructionClickHouseRow,
    approve_checked_row::ApproveCheckedInstructionClickHouseRow,
    approve_row::ApproveInstructionClickHouseRow, batch_row::BatchInstructionClickHouseRow,
    burn_checked_row::BurnCheckedInstructionClickHouseRow, burn_row::BurnInstructionClickHouseRow,
    close_account_row::CloseAccountInstructionClickHouseRow,
    freeze_account_row::FreezeAccountInstructionClickHouseRow,
    get_account_data_size_row::GetAccountDataSizeInstructionClickHouseRow,
    initialize_account2_row::InitializeAccount2InstructionClickHouseRow,
    initialize_account3_row::InitializeAccount3InstructionClickHouseRow,
    initialize_account_row::InitializeAccountInstructionClickHouseRow,
    initialize_immutable_owner_row::InitializeImmutableOwnerInstructionClickHouseRow,
    initialize_mint2_row::InitializeMint2InstructionClickHouseRow,
    initialize_mint_row::InitializeMintInstructionClickHouseRow,
    initialize_multisig2_row::InitializeMultisig2InstructionClickHouseRow,
    initialize_multisig_row::InitializeMultisigInstructionClickHouseRow,
    mint_to_checked_row::MintToCheckedInstructionClickHouseRow,
    mint_to_row::MintToInstructionClickHouseRow, revoke_row::RevokeInstructionClickHouseRow,
    set_authority_row::SetAuthorityInstructionClickHouseRow,
    sync_native_row::SyncNativeInstructionClickHouseRow,
    thaw_account_row::ThawAccountInstructionClickHouseRow,
    transfer_checked_row::TransferCheckedInstructionClickHouseRow,
    transfer_row::TransferInstructionClickHouseRow,
    ui_amount_to_amount_row::UiAmountToAmountInstructionClickHouseRow,
    unwrap_lamports_row::UnwrapLamportsInstructionClickHouseRow,
    withdraw_excess_lamports_row::WithdrawExcessLamportsInstructionClickHouseRow,
};
use {
    super::TokenProgramInstruction,
    carbon_core::{
        clickhouse::{
            ClickHouseAdmin, ClickHouseBatchSettings, ClickHouseConfig,
            ClickHouseInstructionProcessor, ClickHouseTableOptions,
        },
        error::CarbonResult,
        instruction::InstructionMetadata,
    },
    solana_instruction::AccountMeta,
    std::time::Duration,
};

pub const DEFAULT_DATABASE: &str = "default";
pub const DEFAULT_SOURCE_NAME: &str = "block_crawler";
pub const DEFAULT_MODE: &str = "backfill";
pub const DEFAULT_DECODER_VERSION: &str = "v1";
pub const DEFAULT_BATCH_MAX_ROWS: usize = 500;
pub const DEFAULT_BATCH_FLUSH_INTERVAL_MS: u64 = 1_000;

pub(crate) fn clickhouse_instruction_table_options() -> ClickHouseTableOptions {
    ClickHouseTableOptions {
        on_cluster_clause: r#""#,
        engine: r#"MergeTree"#.to_string(),
        local_engine: None,
        local_table_suffix: r#"_local"#,
        partition_by: r#"toYear(partition_time)"#,
        order_by: r#"(program_id, family_name, instruction_id, slot)"#,
        ttl_clause: r#""#,
        settings_clause: r#" SETTINGS non_replicated_deduplication_window = 1000"#,
    }
}

#[derive(Debug, Clone, serde::Serialize)]
#[serde(untagged)]
pub enum TokenProgramClickHouseInstructionRow {
    AmountToUiAmount(amount_to_ui_amount_row::AmountToUiAmountInstructionClickHouseRow),
    Approve(approve_row::ApproveInstructionClickHouseRow),
    ApproveChecked(approve_checked_row::ApproveCheckedInstructionClickHouseRow),
    Batch(batch_row::BatchInstructionClickHouseRow),
    Burn(burn_row::BurnInstructionClickHouseRow),
    BurnChecked(burn_checked_row::BurnCheckedInstructionClickHouseRow),
    CloseAccount(close_account_row::CloseAccountInstructionClickHouseRow),
    FreezeAccount(freeze_account_row::FreezeAccountInstructionClickHouseRow),
    GetAccountDataSize(get_account_data_size_row::GetAccountDataSizeInstructionClickHouseRow),
    InitializeAccount(initialize_account_row::InitializeAccountInstructionClickHouseRow),
    InitializeAccount2(initialize_account2_row::InitializeAccount2InstructionClickHouseRow),
    InitializeAccount3(initialize_account3_row::InitializeAccount3InstructionClickHouseRow),
    InitializeImmutableOwner(
        initialize_immutable_owner_row::InitializeImmutableOwnerInstructionClickHouseRow,
    ),
    InitializeMint(initialize_mint_row::InitializeMintInstructionClickHouseRow),
    InitializeMint2(initialize_mint2_row::InitializeMint2InstructionClickHouseRow),
    InitializeMultisig(initialize_multisig_row::InitializeMultisigInstructionClickHouseRow),
    InitializeMultisig2(initialize_multisig2_row::InitializeMultisig2InstructionClickHouseRow),
    MintTo(mint_to_row::MintToInstructionClickHouseRow),
    MintToChecked(mint_to_checked_row::MintToCheckedInstructionClickHouseRow),
    Revoke(revoke_row::RevokeInstructionClickHouseRow),
    SetAuthority(set_authority_row::SetAuthorityInstructionClickHouseRow),
    SyncNative(sync_native_row::SyncNativeInstructionClickHouseRow),
    ThawAccount(thaw_account_row::ThawAccountInstructionClickHouseRow),
    Transfer(transfer_row::TransferInstructionClickHouseRow),
    TransferChecked(transfer_checked_row::TransferCheckedInstructionClickHouseRow),
    UiAmountToAmount(ui_amount_to_amount_row::UiAmountToAmountInstructionClickHouseRow),
    UnwrapLamports(unwrap_lamports_row::UnwrapLamportsInstructionClickHouseRow),
    WithdrawExcessLamports(
        withdraw_excess_lamports_row::WithdrawExcessLamportsInstructionClickHouseRow,
    ),
}

pub type TokenProgramClickHouseInstructionProcessor = ClickHouseInstructionProcessor<
    TokenProgramInstruction,
    TokenProgramInstructionWithClickHouseMetadata,
    TokenProgramClickHouseInstructionRow,
>;

pub struct TokenProgramClickHouseInstructionsMigration;

carbon_core::clickhouse_row_dispatch!(
    instruction
    TokenProgramClickHouseInstructionRow,
    TokenProgramClickHouseInstructionsMigration,
    TokenProgramInstructionWithClickHouseMetadata,
    TokenProgramInstruction,
    {
        AmountToUiAmount => amount_to_ui_amount_row::AmountToUiAmountInstructionClickHouseRow,
        Approve => approve_row::ApproveInstructionClickHouseRow,
        ApproveChecked => approve_checked_row::ApproveCheckedInstructionClickHouseRow,
        Batch => batch_row::BatchInstructionClickHouseRow,
        Burn => burn_row::BurnInstructionClickHouseRow,
        BurnChecked => burn_checked_row::BurnCheckedInstructionClickHouseRow,
        CloseAccount => close_account_row::CloseAccountInstructionClickHouseRow,
        FreezeAccount => freeze_account_row::FreezeAccountInstructionClickHouseRow,
        GetAccountDataSize => get_account_data_size_row::GetAccountDataSizeInstructionClickHouseRow,
        InitializeAccount => initialize_account_row::InitializeAccountInstructionClickHouseRow,
        InitializeAccount2 => initialize_account2_row::InitializeAccount2InstructionClickHouseRow,
        InitializeAccount3 => initialize_account3_row::InitializeAccount3InstructionClickHouseRow,
        InitializeImmutableOwner => initialize_immutable_owner_row::InitializeImmutableOwnerInstructionClickHouseRow,
        InitializeMint => initialize_mint_row::InitializeMintInstructionClickHouseRow,
        InitializeMint2 => initialize_mint2_row::InitializeMint2InstructionClickHouseRow,
        InitializeMultisig => initialize_multisig_row::InitializeMultisigInstructionClickHouseRow,
        InitializeMultisig2 => initialize_multisig2_row::InitializeMultisig2InstructionClickHouseRow,
        MintTo => mint_to_row::MintToInstructionClickHouseRow,
        MintToChecked => mint_to_checked_row::MintToCheckedInstructionClickHouseRow,
        Revoke => revoke_row::RevokeInstructionClickHouseRow,
        SetAuthority => set_authority_row::SetAuthorityInstructionClickHouseRow,
        SyncNative => sync_native_row::SyncNativeInstructionClickHouseRow,
        ThawAccount => thaw_account_row::ThawAccountInstructionClickHouseRow,
        Transfer => transfer_row::TransferInstructionClickHouseRow,
        TransferChecked => transfer_checked_row::TransferCheckedInstructionClickHouseRow,
        UiAmountToAmount => ui_amount_to_amount_row::UiAmountToAmountInstructionClickHouseRow,
        UnwrapLamports => unwrap_lamports_row::UnwrapLamportsInstructionClickHouseRow,
        WithdrawExcessLamports => withdraw_excess_lamports_row::WithdrawExcessLamportsInstructionClickHouseRow,
    }
);

impl TokenProgramClickHouseInstructionsMigration {
    pub async fn run(config: &ClickHouseConfig) -> CarbonResult<()> {
        ClickHouseAdmin::new(config.clone())
            .execute_schema::<Self>()
            .await
    }
}

pub struct TokenProgramInstructionWithClickHouseMetadata(
    pub TokenProgramInstruction,
    pub InstructionMetadata,
    pub Vec<AccountMeta>,
);

impl
    From<(
        TokenProgramInstruction,
        InstructionMetadata,
        Vec<AccountMeta>,
    )> for TokenProgramInstructionWithClickHouseMetadata
{
    fn from(
        value: (
            TokenProgramInstruction,
            InstructionMetadata,
            Vec<AccountMeta>,
        ),
    ) -> Self {
        Self(value.0, value.1, value.2)
    }
}

pub fn clickhouse_config_from_database_url(database_url: &str) -> CarbonResult<ClickHouseConfig> {
    ClickHouseConfig::from_database_url(
        database_url,
        DEFAULT_DATABASE.to_string(),
        amount_to_ui_amount_row::AmountToUiAmountInstructionClickHouseRow::DEFAULT_TABLE_NAME
            .to_string(),
        DEFAULT_SOURCE_NAME.to_string(),
        DEFAULT_MODE.to_string(),
        DEFAULT_DECODER_VERSION.to_string(),
        ClickHouseBatchSettings::new(
            DEFAULT_BATCH_MAX_ROWS,
            Duration::from_millis(DEFAULT_BATCH_FLUSH_INTERVAL_MS),
        ),
    )
}

pub async fn bootstrap_clickhouse_from_database_url(
    database_url: &str,
) -> CarbonResult<ClickHouseConfig> {
    let config = clickhouse_config_from_database_url(database_url)?;
    TokenProgramClickHouseInstructionsMigration::run(&config).await?;
    Ok(config)
}

pub fn clickhouse_processor(
    config: ClickHouseConfig,
) -> TokenProgramClickHouseInstructionProcessor {
    ClickHouseInstructionProcessor::new(config)
}

pub async fn setup_clickhouse(
    database_url: &str,
) -> CarbonResult<TokenProgramClickHouseInstructionProcessor> {
    let config = bootstrap_clickhouse_from_database_url(database_url).await?;
    Ok(clickhouse_processor(config))
}
