//! This code was AUTOGENERATED using the Codama library.

#[allow(unused_imports)]
use carbon_core::clickhouse::rows::clickhouse_enum_variant;
use carbon_core::{
    clickhouse::{
        rows::{
            ClickHouseInstructionLandingMetadata, ClickHouseRowContext,
            CLICKHOUSE_INSTRUCTION_COMMON_COLUMNS,
        },
        ClickHouseColumnSpec,
    },
    instruction::InstructionMetadata,
};

#[derive(Debug, Clone, serde::Serialize)]
pub struct RevokeInstructionClickHouseRow {
    #[serde(flatten)]
    pub metadata: ClickHouseInstructionLandingMetadata,
}

impl RevokeInstructionClickHouseRow {
    pub const FAMILY_NAME: &'static str = "token_program_revoke_instruction";
    pub const INSTRUCTION_TYPE: &'static str = "revoke";
    pub const DEFAULT_TABLE_NAME: &'static str = "token_program_revoke_instruction_landing";
    pub const COMMON_COLUMNS: &'static [ClickHouseColumnSpec] =
        CLICKHOUSE_INSTRUCTION_COMMON_COLUMNS;
    pub const PAYLOAD_COLUMNS: &'static [ClickHouseColumnSpec] = &[];

    pub fn from_parts(
        source: crate::instructions::revoke::Revoke,
        metadata: &InstructionMetadata,
        context: &ClickHouseRowContext,
    ) -> Self {
        let _ = &source;

        Self {
            metadata: ClickHouseInstructionLandingMetadata::new(
                crate::PROGRAM_ID.as_ref(),
                crate::PROGRAM_ID.to_string(),
                Self::FAMILY_NAME,
                Self::INSTRUCTION_TYPE,
                metadata,
                context,
            ),
        }
    }
}

carbon_core::impl_clickhouse_instruction_row!(
    RevokeInstructionClickHouseRow,
    super::clickhouse_instruction_table_options
);
