//! This code was AUTOGENERATED using the Codama library.

#[allow(unused_imports)]
use carbon_core::clickhouse::rows::clickhouse_enum_variant;
use carbon_core::{
    clickhouse::{
        rows::{
            ClickHouseInstructionLandingMetadata, ClickHouseRowContext,
            CLICKHOUSE_INSTRUCTION_COMMON_COLUMNS,
        },
        ClickHouseColumnSpec,
    },
    instruction::InstructionMetadata,
};

#[derive(Debug, Clone, serde::Serialize)]
pub struct SetAuthorityInstructionClickHouseRow {
    #[serde(flatten)]
    pub metadata: ClickHouseInstructionLandingMetadata,
    pub authority_type: String,
    pub new_authority: Option<String>,
}

impl SetAuthorityInstructionClickHouseRow {
    pub const FAMILY_NAME: &'static str = "token_program_set_authority_instruction";
    pub const INSTRUCTION_TYPE: &'static str = "set_authority";
    pub const DEFAULT_TABLE_NAME: &'static str = "token_program_set_authority_instruction_landing";
    pub const COMMON_COLUMNS: &'static [ClickHouseColumnSpec] =
        CLICKHOUSE_INSTRUCTION_COMMON_COLUMNS;
    pub const PAYLOAD_COLUMNS: &'static [ClickHouseColumnSpec] = &[
        ClickHouseColumnSpec::new(
            "authority_type",
            r#"Enum8('MintTokens' = 0, 'FreezeAccount' = 1, 'AccountOwner' = 2, 'CloseAccount' = 3)"#,
        ),
        ClickHouseColumnSpec::new("new_authority", r#"Nullable(String)"#),
    ];

    pub fn from_parts(
        source: crate::instructions::set_authority::SetAuthority,
        metadata: &InstructionMetadata,
        context: &ClickHouseRowContext,
    ) -> Self {
        let _ = &source;

        Self {
            metadata: ClickHouseInstructionLandingMetadata::new(
                crate::PROGRAM_ID.as_ref(),
                crate::PROGRAM_ID.to_string(),
                Self::FAMILY_NAME,
                Self::INSTRUCTION_TYPE,
                metadata,
                context,
            ),
            authority_type: clickhouse_enum_variant(&source.authority_type),
            new_authority: source.new_authority.as_ref().map(|value| value.to_string()),
        }
    }
}

carbon_core::impl_clickhouse_instruction_row!(
    SetAuthorityInstructionClickHouseRow,
    super::clickhouse_instruction_table_options
);
