//! This code was AUTOGENERATED using the Codama library.

#[allow(unused_imports)]
use carbon_core::clickhouse::rows::clickhouse_enum_variant;
use carbon_core::{
    clickhouse::{
        rows::{
            ClickHouseInstructionLandingMetadata, ClickHouseRowContext,
            CLICKHOUSE_INSTRUCTION_COMMON_COLUMNS,
        },
        ClickHouseColumnSpec,
    },
    instruction::InstructionMetadata,
};

#[derive(Debug, Clone, serde::Serialize)]
pub struct TransferCheckedInstructionClickHouseRow {
    #[serde(flatten)]
    pub metadata: ClickHouseInstructionLandingMetadata,
    pub amount: u64,
    pub decimals: u8,
}

impl TransferCheckedInstructionClickHouseRow {
    pub const FAMILY_NAME: &'static str = "token_program_transfer_checked_instruction";
    pub const INSTRUCTION_TYPE: &'static str = "transfer_checked";
    pub const DEFAULT_TABLE_NAME: &'static str =
        "token_program_transfer_checked_instruction_landing";
    pub const COMMON_COLUMNS: &'static [ClickHouseColumnSpec] =
        CLICKHOUSE_INSTRUCTION_COMMON_COLUMNS;
    pub const PAYLOAD_COLUMNS: &'static [ClickHouseColumnSpec] = &[
        ClickHouseColumnSpec::new("amount", r#"UInt64"#),
        ClickHouseColumnSpec::new("decimals", r#"UInt8"#),
    ];

    pub fn from_parts(
        source: crate::instructions::transfer_checked::TransferChecked,
        metadata: &InstructionMetadata,
        context: &ClickHouseRowContext,
    ) -> Self {
        let _ = &source;

        Self {
            metadata: ClickHouseInstructionLandingMetadata::new(
                crate::PROGRAM_ID.as_ref(),
                crate::PROGRAM_ID.to_string(),
                Self::FAMILY_NAME,
                Self::INSTRUCTION_TYPE,
                metadata,
                context,
            ),
            amount: source.amount,
            decimals: source.decimals,
        }
    }
}

carbon_core::impl_clickhouse_instruction_row!(
    TransferCheckedInstructionClickHouseRow,
    super::clickhouse_instruction_table_options
);
