//! This code was AUTOGENERATED using the Codama library.
#[allow(unused_imports)]
use carbon_core::clickhouse::rows::clickhouse_enum_variant;

#[derive(Debug, Clone, serde::Serialize)]
pub struct ClickHouseBatchItem {
    pub number_of_accounts: u8,
    pub instruction_data: Vec<u8>,
}

impl Default for ClickHouseBatchItem {
    fn default() -> Self {
        Self {
            number_of_accounts: 0,
            instruction_data: Vec::new(),
        }
    }
}

impl From<&crate::types::BatchItem> for ClickHouseBatchItem {
    fn from(value: &crate::types::BatchItem) -> Self {
        Self {
            number_of_accounts: value.number_of_accounts,
            instruction_data: value.instruction_data.to_vec(),
        }
    }
}
