//! This code was AUTOGENERATED using the Codama library.

#[allow(unused_imports)]
use carbon_core::clickhouse::rows::clickhouse_enum_variant;
use carbon_core::{
    clickhouse::{
        rows::{
            ClickHouseInstructionLandingMetadata, ClickHouseRowContext,
            CLICKHOUSE_INSTRUCTION_COMMON_COLUMNS,
        },
        ClickHouseColumnSpec,
    },
    instruction::InstructionMetadata,
};

#[derive(Debug, Clone, serde::Serialize)]
pub struct UiAmountToAmountInstructionClickHouseRow {
    #[serde(flatten)]
    pub metadata: ClickHouseInstructionLandingMetadata,
    pub ui_amount: String,
}

impl UiAmountToAmountInstructionClickHouseRow {
    pub const FAMILY_NAME: &'static str = "token_program_ui_amount_to_amount_instruction";
    pub const INSTRUCTION_TYPE: &'static str = "ui_amount_to_amount";
    pub const DEFAULT_TABLE_NAME: &'static str =
        "token_program_ui_amount_to_amount_instruction_landing";
    pub const COMMON_COLUMNS: &'static [ClickHouseColumnSpec] =
        CLICKHOUSE_INSTRUCTION_COMMON_COLUMNS;
    pub const PAYLOAD_COLUMNS: &'static [ClickHouseColumnSpec] =
        &[ClickHouseColumnSpec::new("ui_amount", r#"String"#)];

    pub fn from_parts(
        source: crate::instructions::ui_amount_to_amount::UiAmountToAmount,
        metadata: &InstructionMetadata,
        context: &ClickHouseRowContext,
    ) -> Self {
        let _ = &source;

        Self {
            metadata: ClickHouseInstructionLandingMetadata::new(
                crate::PROGRAM_ID.as_ref(),
                crate::PROGRAM_ID.to_string(),
                Self::FAMILY_NAME,
                Self::INSTRUCTION_TYPE,
                metadata,
                context,
            ),
            ui_amount: source.ui_amount.clone(),
        }
    }
}

carbon_core::impl_clickhouse_instruction_row!(
    UiAmountToAmountInstructionClickHouseRow,
    super::clickhouse_instruction_table_options
);
