//! This code was AUTOGENERATED using the Codama library.
pub mod token_ledger_row;

pub use self::token_ledger_row::*;

use std::time::Duration;

use carbon_core::{
    account::{AccountMetadata, DecodedAccount},
    clickhouse::{
        rows::{ClickHouseRow, ClickHouseRowContext, ClickHouseRows},
        ClickHouseAccountProcessor, ClickHouseAdmin, ClickHouseConfig, ClickHouseSchema,
    },
    error::CarbonResult,
};

use super::JupiterSwapAccount;

pub const DEFAULT_DATABASE: &str = "default";
pub const DEFAULT_SOURCE_NAME: &str = "block_crawler";
pub const DEFAULT_MODE: &str = "backfill";
pub const DEFAULT_DECODER_VERSION: &str = "v1";
pub const DEFAULT_MAX_ROWS: usize = 500;
pub const DEFAULT_FLUSH_INTERVAL_MS: u64 = 1_000;

#[derive(Debug, Clone, serde::Serialize)]
#[serde(untagged)]
pub enum JupiterSwapClickHouseAccountRow {
    TokenLedger(token_ledger_row::TokenLedgerAccountClickHouseRow),
}

impl ClickHouseRow for JupiterSwapClickHouseAccountRow {
    fn table_name(&self) -> &'static str {
        match self {
            Self::TokenLedger(row) => row.table_name(),
        }
    }

    fn partition_key(&self) -> String {
        match self {
            Self::TokenLedger(row) => row.partition_key(),
        }
    }
}

pub type JupiterSwapClickHouseAccountProcessor = ClickHouseAccountProcessor<
    JupiterSwapAccount,
    JupiterSwapAccountWithClickHouseMetadata,
    JupiterSwapClickHouseAccountRow,
>;

pub struct JupiterSwapClickHouseAccountsMigration;

impl ClickHouseSchema for JupiterSwapClickHouseAccountsMigration {
    fn operations(_config: &ClickHouseConfig) -> Vec<String> {
        let mut operations = Vec::new();
        operations.extend(
            token_ledger_row::TokenLedgerAccountClickHouseRow::migration_operations(
                token_ledger_row::TokenLedgerAccountClickHouseRow::DEFAULT_TABLE_NAME,
            ),
        );
        operations
    }
}

impl JupiterSwapClickHouseAccountsMigration {
    pub async fn run(config: &ClickHouseConfig) -> CarbonResult<()> {
        ClickHouseAdmin::new(config.clone())
            .execute_schema::<Self>()
            .await
    }
}

pub struct JupiterSwapAccountWithClickHouseMetadata(
    pub DecodedAccount<JupiterSwapAccount>,
    pub AccountMetadata,
);

impl From<(DecodedAccount<JupiterSwapAccount>, AccountMetadata)>
    for JupiterSwapAccountWithClickHouseMetadata
{
    fn from(value: (DecodedAccount<JupiterSwapAccount>, AccountMetadata)) -> Self {
        Self(value.0, value.1)
    }
}

impl ClickHouseRows<JupiterSwapClickHouseAccountRow> for JupiterSwapAccountWithClickHouseMetadata {
    fn clickhouse_rows(
        &self,
        context: &ClickHouseRowContext,
    ) -> Vec<JupiterSwapClickHouseAccountRow> {
        let JupiterSwapAccountWithClickHouseMetadata(decoded_account, metadata) = self;

        match &decoded_account.data {
            JupiterSwapAccount::TokenLedger(account) => {
                vec![JupiterSwapClickHouseAccountRow::TokenLedger(
                    token_ledger_row::TokenLedgerAccountClickHouseRow::from_parts(
                        *account.clone(),
                        decoded_account,
                        metadata,
                        context,
                    ),
                )]
            }
        }
    }
}

pub fn clickhouse_config_from_database_url(database_url: &str) -> CarbonResult<ClickHouseConfig> {
    ClickHouseConfig::from_database_url(
        database_url,
        DEFAULT_DATABASE.to_string(),
        token_ledger_row::TokenLedgerAccountClickHouseRow::DEFAULT_TABLE_NAME.to_string(),
        DEFAULT_SOURCE_NAME.to_string(),
        DEFAULT_MODE.to_string(),
        DEFAULT_DECODER_VERSION.to_string(),
        DEFAULT_MAX_ROWS,
        Duration::from_millis(DEFAULT_FLUSH_INTERVAL_MS),
    )
}

pub async fn bootstrap_clickhouse_from_database_url(
    database_url: &str,
) -> CarbonResult<ClickHouseConfig> {
    let config = clickhouse_config_from_database_url(database_url)?;
    JupiterSwapClickHouseAccountsMigration::run(&config).await?;
    Ok(config)
}

pub fn clickhouse_processor(config: ClickHouseConfig) -> JupiterSwapClickHouseAccountProcessor {
    ClickHouseAccountProcessor::new(config)
}

pub async fn setup_clickhouse(
    database_url: &str,
) -> CarbonResult<JupiterSwapClickHouseAccountProcessor> {
    let config = bootstrap_clickhouse_from_database_url(database_url).await?;
    Ok(clickhouse_processor(config))
}
