//! This code was AUTOGENERATED using the Codama library.
pub mod token_ledger_row;

pub use self::token_ledger_row::TokenLedgerAccountClickHouseRow;

use std::time::Duration;

use carbon_core::{
    account::{AccountMetadata, DecodedAccount},
    clickhouse::{
        ClickHouseAccountProcessor, ClickHouseAdmin, ClickHouseBatchSettings, ClickHouseConfig,
        ClickHouseTableOptions,
    },
    error::CarbonResult,
};

use super::JupiterSwapAccount;

pub const DEFAULT_DATABASE: &str = "default";
pub const DEFAULT_SOURCE_NAME: &str = "block_crawler";
pub const DEFAULT_MODE: &str = "backfill";
pub const DEFAULT_DECODER_VERSION: &str = "v1";
pub const DEFAULT_BATCH_MAX_ROWS: usize = 500;
pub const DEFAULT_BATCH_FLUSH_INTERVAL_MS: u64 = 1_000;

pub(crate) fn clickhouse_account_table_options() -> ClickHouseTableOptions {
    ClickHouseTableOptions {
        on_cluster_clause: r#""#,
        engine: r#"MergeTree"#.to_string(),
        local_engine: None,
        local_table_suffix: r#"_local"#,
        partition_by: r#"partition_slot"#,
        order_by: r#"(program_id, family_name, account_id, slot)"#,
        ttl_clause: r#""#,
        settings_clause: r#" SETTINGS non_replicated_deduplication_window = 1000"#,
    }
}

#[derive(Debug, Clone, serde::Serialize)]
#[serde(untagged)]
pub enum JupiterSwapClickHouseAccountRow {
    TokenLedger(token_ledger_row::TokenLedgerAccountClickHouseRow),
}

pub type JupiterSwapClickHouseAccountProcessor = ClickHouseAccountProcessor<
    JupiterSwapAccount,
    JupiterSwapAccountWithClickHouseMetadata,
    JupiterSwapClickHouseAccountRow,
>;

pub struct JupiterSwapClickHouseAccountsMigration;

carbon_core::clickhouse_row_dispatch!(
    account
    JupiterSwapClickHouseAccountRow,
    JupiterSwapClickHouseAccountsMigration,
    JupiterSwapAccountWithClickHouseMetadata,
    JupiterSwapAccount,
    {
        TokenLedger => token_ledger_row::TokenLedgerAccountClickHouseRow,
    }
);

impl JupiterSwapClickHouseAccountsMigration {
    pub async fn run(config: &ClickHouseConfig) -> CarbonResult<()> {
        ClickHouseAdmin::new(config.clone())
            .execute_schema::<Self>()
            .await
    }
}

pub struct JupiterSwapAccountWithClickHouseMetadata(
    pub DecodedAccount<JupiterSwapAccount>,
    pub AccountMetadata,
);

impl From<(DecodedAccount<JupiterSwapAccount>, AccountMetadata)>
    for JupiterSwapAccountWithClickHouseMetadata
{
    fn from(value: (DecodedAccount<JupiterSwapAccount>, AccountMetadata)) -> Self {
        Self(value.0, value.1)
    }
}

pub fn clickhouse_config_from_database_url(database_url: &str) -> CarbonResult<ClickHouseConfig> {
    ClickHouseConfig::from_database_url(
        database_url,
        DEFAULT_DATABASE.to_string(),
        token_ledger_row::TokenLedgerAccountClickHouseRow::DEFAULT_TABLE_NAME.to_string(),
        DEFAULT_SOURCE_NAME.to_string(),
        DEFAULT_MODE.to_string(),
        DEFAULT_DECODER_VERSION.to_string(),
        ClickHouseBatchSettings::new(
            DEFAULT_BATCH_MAX_ROWS,
            Duration::from_millis(DEFAULT_BATCH_FLUSH_INTERVAL_MS),
        ),
    )
}

pub async fn bootstrap_clickhouse_from_database_url(
    database_url: &str,
) -> CarbonResult<ClickHouseConfig> {
    let config = clickhouse_config_from_database_url(database_url)?;
    JupiterSwapClickHouseAccountsMigration::run(&config).await?;
    Ok(config)
}

pub fn clickhouse_processor(config: ClickHouseConfig) -> JupiterSwapClickHouseAccountProcessor {
    ClickHouseAccountProcessor::new(config)
}

pub async fn setup_clickhouse(
    database_url: &str,
) -> CarbonResult<JupiterSwapClickHouseAccountProcessor> {
    let config = bootstrap_clickhouse_from_database_url(database_url).await?;
    Ok(clickhouse_processor(config))
}
