//! This code was AUTOGENERATED using the Codama library.

#[allow(unused_imports)]
use carbon_core::clickhouse::rows::clickhouse_enum_variant;
use carbon_core::{
    account::{AccountMetadata, DecodedAccount},
    clickhouse::{
        clickhouse_column_names, clickhouse_create_table_sql, clickhouse_managed_tables,
        clickhouse_migration_operations,
        rows::{
            ClickHouseAccountLandingMetadata, ClickHouseRow, ClickHouseRowContext, ClickHouseTable,
            CLICKHOUSE_ACCOUNT_COMMON_COLUMNS,
        },
        ClickHouseColumnSpec, ClickHouseManagedTable, ClickHouseTableOptions,
    },
};

#[derive(Debug, Clone, serde::Serialize)]
pub struct TokenLedgerAccountClickHouseRow {
    #[serde(flatten)]
    pub metadata: ClickHouseAccountLandingMetadata,
    pub token_account: String,
    pub amount: u64,
}

impl TokenLedgerAccountClickHouseRow {
    pub const FAMILY_NAME: &'static str = "jupiter_swap_token_ledger_account";
    pub const ACCOUNT_TYPE: &'static str = "token_ledger";
    pub const DEFAULT_TABLE_NAME: &'static str = "jupiter_swap_token_ledger_account_landing";
    pub const COMMON_COLUMNS: &'static [ClickHouseColumnSpec] = CLICKHOUSE_ACCOUNT_COMMON_COLUMNS;
    pub const PAYLOAD_COLUMNS: &'static [ClickHouseColumnSpec] = &[
        ClickHouseColumnSpec::new("token_account", r#"String"#),
        ClickHouseColumnSpec::new("amount", r#"UInt64"#),
    ];

    pub fn from_parts(
        source: crate::accounts::token_ledger::TokenLedger,
        decoded_account: &DecodedAccount<crate::accounts::JupiterSwapAccount>,
        metadata: &AccountMetadata,
        context: &ClickHouseRowContext,
    ) -> Self {
        let _ = &source;

        Self {
            metadata: ClickHouseAccountLandingMetadata::new(
                crate::PROGRAM_ID.as_ref(),
                crate::PROGRAM_ID.to_string(),
                Self::FAMILY_NAME,
                Self::ACCOUNT_TYPE,
                decoded_account,
                metadata,
                context,
            ),
            token_account: source.token_account.to_string(),
            amount: source.amount,
        }
    }

    fn column_specs() -> Vec<ClickHouseColumnSpec> {
        let mut columns = Self::COMMON_COLUMNS.to_vec();
        columns.extend_from_slice(Self::PAYLOAD_COLUMNS);
        columns
    }

    fn table_options() -> ClickHouseTableOptions {
        ClickHouseTableOptions {
            on_cluster_clause: r#""#,
            engine: r#"MergeTree"#.to_string(),
            local_engine: None,
            local_table_suffix: r#"_local"#,
            partition_by: r#"partition_slot"#,
            order_by: r#"(program_id, family_name, account_id, slot)"#,
            ttl_clause: r#""#,
            settings_clause: r#""#,
        }
    }

    pub fn migration_operations(table_name: &str) -> Vec<String> {
        let columns = Self::column_specs();
        clickhouse_migration_operations(table_name, &columns, &Self::table_options())
    }

    pub fn managed_tables(table_name: &str) -> Vec<ClickHouseManagedTable> {
        let columns = Self::column_specs();
        clickhouse_managed_tables(table_name, &columns, &Self::table_options())
    }
}

impl ClickHouseTable for TokenLedgerAccountClickHouseRow {
    fn table() -> &'static str {
        Self::DEFAULT_TABLE_NAME
    }

    fn columns() -> Vec<&'static str> {
        let columns = Self::column_specs();
        clickhouse_column_names(&columns)
    }

    fn create_table_sql(table_name: &str) -> String {
        let columns = Self::column_specs();
        let options = Self::table_options();
        clickhouse_create_table_sql(
            table_name,
            &columns,
            &options.engine,
            options.local_engine.is_none(),
            &options,
        )
    }
}

impl ClickHouseRow for TokenLedgerAccountClickHouseRow {
    fn table_name(&self) -> &'static str {
        Self::table()
    }

    fn partition_key(&self) -> String {
        self.metadata.partition_key()
    }
}
