//! This code was AUTOGENERATED using the Codama library.

#[allow(unused_imports)]
use carbon_core::clickhouse::rows::clickhouse_enum_variant;
use carbon_core::{
    account::{AccountMetadata, DecodedAccount},
    clickhouse::{
        rows::{
            ClickHouseAccountLandingMetadata, ClickHouseRowContext,
            CLICKHOUSE_ACCOUNT_COMMON_COLUMNS,
        },
        ClickHouseColumnSpec,
    },
};

#[derive(Debug, Clone, serde::Serialize)]
pub struct TokenLedgerAccountClickHouseRow {
    #[serde(flatten)]
    pub metadata: ClickHouseAccountLandingMetadata,
    pub token_account: String,
    pub amount: u64,
}

impl TokenLedgerAccountClickHouseRow {
    pub const FAMILY_NAME: &'static str = "jupiter_swap_token_ledger_account";
    pub const ACCOUNT_TYPE: &'static str = "token_ledger";
    pub const DEFAULT_TABLE_NAME: &'static str = "jupiter_swap_token_ledger_account_landing";
    pub const COMMON_COLUMNS: &'static [ClickHouseColumnSpec] = CLICKHOUSE_ACCOUNT_COMMON_COLUMNS;
    pub const PAYLOAD_COLUMNS: &'static [ClickHouseColumnSpec] = &[
        ClickHouseColumnSpec::new("token_account", r#"String"#),
        ClickHouseColumnSpec::new("amount", r#"UInt64"#),
    ];

    pub fn from_parts(
        source: crate::accounts::token_ledger::TokenLedger,
        decoded_account: &DecodedAccount<crate::accounts::JupiterSwapAccount>,
        metadata: &AccountMetadata,
        context: &ClickHouseRowContext,
    ) -> Self {
        let _ = &source;

        Self {
            metadata: ClickHouseAccountLandingMetadata::new(
                crate::PROGRAM_ID.as_ref(),
                crate::PROGRAM_ID.to_string(),
                Self::FAMILY_NAME,
                Self::ACCOUNT_TYPE,
                decoded_account,
                metadata,
                context,
            ),
            token_account: source.token_account.to_string(),
            amount: source.amount,
        }
    }
}

carbon_core::impl_clickhouse_account_row!(TokenLedgerAccountClickHouseRow);
