//! This code was AUTOGENERATED using the Codama library.

#[allow(unused_imports)]
use carbon_core::clickhouse::rows::clickhouse_enum_variant;
use carbon_core::{
    account::{AccountMetadata, DecodedAccount},
    clickhouse::{
        rows::{
            ClickHouseAccountLandingMetadata, ClickHouseRowContext,
            CLICKHOUSE_ACCOUNT_COMMON_COLUMNS,
        },
        ClickHouseColumnSpec,
    },
};

#[derive(Debug, Clone, serde::Serialize)]
pub struct MintAccountClickHouseRow {
    #[serde(flatten)]
    pub metadata: ClickHouseAccountLandingMetadata,
    pub mint_authority: Option<String>,
    pub supply: u64,
    pub decimals: u8,
    pub is_initialized: bool,
    pub freeze_authority: Option<String>,
}

impl MintAccountClickHouseRow {
    pub const FAMILY_NAME: &'static str = "token_program_mint_account";
    pub const ACCOUNT_TYPE: &'static str = "mint";
    pub const DEFAULT_TABLE_NAME: &'static str = "token_program_mint_account_landing";
    pub const COMMON_COLUMNS: &'static [ClickHouseColumnSpec] = CLICKHOUSE_ACCOUNT_COMMON_COLUMNS;
    pub const PAYLOAD_COLUMNS: &'static [ClickHouseColumnSpec] = &[
        ClickHouseColumnSpec::new("mint_authority", r#"Nullable(String)"#),
        ClickHouseColumnSpec::new("supply", r#"UInt64"#),
        ClickHouseColumnSpec::new("decimals", r#"UInt8"#),
        ClickHouseColumnSpec::new("is_initialized", r#"Bool"#),
        ClickHouseColumnSpec::new("freeze_authority", r#"Nullable(String)"#),
    ];

    pub fn from_parts(
        source: crate::accounts::mint::Mint,
        decoded_account: &DecodedAccount<crate::accounts::TokenProgramAccount>,
        metadata: &AccountMetadata,
        context: &ClickHouseRowContext,
    ) -> Self {
        let _ = &source;

        Self {
            metadata: ClickHouseAccountLandingMetadata::new(
                crate::PROGRAM_ID.as_ref(),
                crate::PROGRAM_ID.to_string(),
                Self::FAMILY_NAME,
                Self::ACCOUNT_TYPE,
                decoded_account,
                metadata,
                context,
            ),
            mint_authority: source
                .mint_authority
                .as_ref()
                .map(|value| value.to_string()),
            supply: source.supply,
            decimals: source.decimals,
            is_initialized: source.is_initialized,
            freeze_authority: source
                .freeze_authority
                .as_ref()
                .map(|value| value.to_string()),
        }
    }
}

carbon_core::impl_clickhouse_account_row!(
    MintAccountClickHouseRow,
    super::clickhouse_account_table_options
);
