//! This code was AUTOGENERATED using the Codama library.

#[allow(unused_imports)]
use carbon_core::clickhouse::rows::clickhouse_enum_variant;
use carbon_core::{
    account::{AccountMetadata, DecodedAccount},
    clickhouse::{
        rows::{
            ClickHouseAccountLandingMetadata, ClickHouseRowContext,
            CLICKHOUSE_ACCOUNT_COMMON_COLUMNS,
        },
        ClickHouseColumnSpec,
    },
};

#[derive(Debug, Clone, serde::Serialize)]
pub struct MultisigAccountClickHouseRow {
    #[serde(flatten)]
    pub metadata: ClickHouseAccountLandingMetadata,
    pub m: u8,
    pub n: u8,
    pub is_initialized: bool,
    pub signers: Vec<String>,
}

impl MultisigAccountClickHouseRow {
    pub const FAMILY_NAME: &'static str = "token_program_multisig_account";
    pub const ACCOUNT_TYPE: &'static str = "multisig";
    pub const DEFAULT_TABLE_NAME: &'static str = "token_program_multisig_account_landing";
    pub const COMMON_COLUMNS: &'static [ClickHouseColumnSpec] = CLICKHOUSE_ACCOUNT_COMMON_COLUMNS;
    pub const PAYLOAD_COLUMNS: &'static [ClickHouseColumnSpec] = &[
        ClickHouseColumnSpec::new("m", r#"UInt8"#),
        ClickHouseColumnSpec::new("n", r#"UInt8"#),
        ClickHouseColumnSpec::new("is_initialized", r#"Bool"#),
        ClickHouseColumnSpec::new("signers", r#"Array(String)"#),
    ];

    pub fn from_parts(
        source: crate::accounts::multisig::Multisig,
        decoded_account: &DecodedAccount<crate::accounts::TokenProgramAccount>,
        metadata: &AccountMetadata,
        context: &ClickHouseRowContext,
    ) -> Self {
        let _ = &source;

        Self {
            metadata: ClickHouseAccountLandingMetadata::new(
                crate::PROGRAM_ID.as_ref(),
                crate::PROGRAM_ID.to_string(),
                Self::FAMILY_NAME,
                Self::ACCOUNT_TYPE,
                decoded_account,
                metadata,
                context,
            ),
            m: source.m,
            n: source.n,
            is_initialized: source.is_initialized,
            signers: source
                .signers
                .iter()
                .map(|value| value.to_string())
                .collect(),
        }
    }
}

carbon_core::impl_clickhouse_account_row!(MultisigAccountClickHouseRow);
