//! This code was AUTOGENERATED using the Codama library.

use {
    carbon_core::{
        account::{AccountMetadata, DecodedAccount},
        clickhouse::{
            rows::{
                deterministic_account_id, ClickHouseRow, ClickHouseRowContext, ClickHouseTable,
            },
            ClickHouseColumnDefinition, ClickHouseManagedTable,
        },
    },
    chrono::{DateTime, Utc},
};

#[derive(Debug, Clone, serde::Serialize)]
pub struct MultisigAccountClickHouseRow {
    pub program_id: String,
    pub family_name: String,
    pub account_type: String,
    pub account_id: String,
    pub slot: u64,
    pub pubkey: String,
    pub transaction_signature: Option<String>,
    pub lamports: u64,
    pub owner: String,
    pub executable: bool,
    pub rent_epoch: u64,
    pub source_name: String,
    pub mode: String,
    pub decoder_version: String,
    pub ingest_ts: String,
    pub partition_slot: u64,
    pub m: u8,
    pub n: u8,
    pub is_initialized: bool,
    pub signers: Vec<String>,
}

impl MultisigAccountClickHouseRow {
    pub const FAMILY_NAME: &'static str = "token_program_multisig_account";
    pub const ACCOUNT_TYPE: &'static str = "multisig";
    pub const DEFAULT_TABLE_NAME: &'static str = "token_program_multisig_account_landing";

    pub fn from_parts(
        source: crate::accounts::multisig::Multisig,
        decoded_account: &DecodedAccount<crate::accounts::TokenProgramAccount>,
        metadata: &AccountMetadata,
        context: &ClickHouseRowContext,
    ) -> Self {
        let _ = &source;
        let ingest_ts = Utc::now();
        let partition_slot = metadata.slot / 1_000_000;

        Self {
            program_id: crate::PROGRAM_ID.to_string(),
            family_name: Self::FAMILY_NAME.to_string(),
            account_type: Self::ACCOUNT_TYPE.to_string(),
            account_id: deterministic_account_id(
                crate::PROGRAM_ID.as_ref(),
                metadata.pubkey.as_ref(),
                metadata.slot,
                Self::ACCOUNT_TYPE,
            ),
            slot: metadata.slot,
            pubkey: metadata.pubkey.to_string(),
            transaction_signature: metadata
                .transaction_signature
                .as_ref()
                .map(|signature| signature.to_string()),
            lamports: decoded_account.lamports,
            owner: decoded_account.owner.to_string(),
            executable: decoded_account.executable,
            rent_epoch: decoded_account.rent_epoch,
            source_name: context.source_name.clone(),
            mode: context.mode.clone(),
            decoder_version: context.decoder_version.clone(),
            ingest_ts: format_datetime(ingest_ts),
            partition_slot,
            m: source.m,
            n: source.n,
            is_initialized: source.is_initialized,
            signers: source
                .signers
                .iter()
                .map(|value| value.to_string())
                .collect(),
        }
    }
}

impl ClickHouseTable for MultisigAccountClickHouseRow {
    fn table() -> &'static str {
        Self::DEFAULT_TABLE_NAME
    }

    fn columns() -> Vec<&'static str> {
        vec![
            "program_id",
            "family_name",
            "account_type",
            "account_id",
            "slot",
            "pubkey",
            "transaction_signature",
            "lamports",
            "owner",
            "executable",
            "rent_epoch",
            "source_name",
            "mode",
            "decoder_version",
            "ingest_ts",
            "partition_slot",
            "m",
            "n",
            "is_initialized",
            "signers",
        ]
    }

    fn create_table_sql(table_name: &str) -> String {
        let engine = Self::clickhouse_engine(table_name);
        Self::create_table_sql_for(table_name, &engine, true)
    }
}

impl MultisigAccountClickHouseRow {
    pub fn migration_operations(table_name: &str) -> Vec<String> {
        let mut operations = Vec::new();
        operations.push(Self::create_table_sql(table_name));
        operations.extend(Self::add_column_sql(table_name));
        operations
    }

    pub fn managed_tables(table_name: &str) -> Vec<ClickHouseManagedTable> {
        let engine = Self::clickhouse_engine(table_name);
        vec![Self::managed_table_for(
            table_name,
            Self::create_table_sql(table_name),
            engine,
            true,
        )]
    }

    fn managed_table_for(
        table_name: &str,
        create_table_sql: String,
        engine: String,
        include_merge_tree_layout: bool,
    ) -> ClickHouseManagedTable {
        ClickHouseManagedTable {
            name: table_name.to_string(),
            create_table_sql,
            drop_table_sql: format!("DROP TABLE IF EXISTS {table_name}"),
            engine: Some(Self::clickhouse_engine_name(&engine)),
            partition_by: include_merge_tree_layout.then(|| r#"partition_slot"#.to_string()),
            order_by: include_merge_tree_layout
                .then(|| r#"(program_id, family_name, account_id, slot)"#.to_string()),
            columns: Self::column_definitions(table_name),
        }
    }

    pub fn add_column_sql(table_name: &str) -> Vec<String> {
        vec![
            format!("ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS program_id String"),
            format!("ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS family_name String"),
            format!("ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS account_type String"),
            format!("ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS account_id String"),
            format!("ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS slot UInt64"),
            format!("ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS pubkey String"),
            format!("ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS transaction_signature Nullable(String)"),
            format!("ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS lamports UInt64"),
            format!("ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS owner String"),
            format!("ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS executable Bool"),
            format!("ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS rent_epoch UInt64"),
            format!("ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS source_name String"),
            format!("ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS mode String"),
            format!("ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS decoder_version String"),
            format!("ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS ingest_ts DateTime64(3, 'UTC')"),
            format!("ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS partition_slot UInt64"),
            format!("ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS m UInt8"),
            format!("ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS n UInt8"),
            format!("ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS is_initialized Bool"),
            format!("ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS signers Array(String)"),
        ]
    }

    pub fn column_definitions(table_name: &str) -> Vec<ClickHouseColumnDefinition> {
        vec![
            ClickHouseColumnDefinition {
                name: "program_id".to_string(),
                clickhouse_type: r#"String"#.to_string(),
                add_column_sql: format!("ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS program_id String"),
                modify_column_sql: format!("ALTER TABLE {table_name} MODIFY COLUMN program_id String"),
            },
            ClickHouseColumnDefinition {
                name: "family_name".to_string(),
                clickhouse_type: r#"String"#.to_string(),
                add_column_sql: format!("ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS family_name String"),
                modify_column_sql: format!("ALTER TABLE {table_name} MODIFY COLUMN family_name String"),
            },
            ClickHouseColumnDefinition {
                name: "account_type".to_string(),
                clickhouse_type: r#"String"#.to_string(),
                add_column_sql: format!("ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS account_type String"),
                modify_column_sql: format!("ALTER TABLE {table_name} MODIFY COLUMN account_type String"),
            },
            ClickHouseColumnDefinition {
                name: "account_id".to_string(),
                clickhouse_type: r#"String"#.to_string(),
                add_column_sql: format!("ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS account_id String"),
                modify_column_sql: format!("ALTER TABLE {table_name} MODIFY COLUMN account_id String"),
            },
            ClickHouseColumnDefinition {
                name: "slot".to_string(),
                clickhouse_type: r#"UInt64"#.to_string(),
                add_column_sql: format!("ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS slot UInt64"),
                modify_column_sql: format!("ALTER TABLE {table_name} MODIFY COLUMN slot UInt64"),
            },
            ClickHouseColumnDefinition {
                name: "pubkey".to_string(),
                clickhouse_type: r#"String"#.to_string(),
                add_column_sql: format!("ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS pubkey String"),
                modify_column_sql: format!("ALTER TABLE {table_name} MODIFY COLUMN pubkey String"),
            },
            ClickHouseColumnDefinition {
                name: "transaction_signature".to_string(),
                clickhouse_type: r#"Nullable(String)"#.to_string(),
                add_column_sql: format!("ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS transaction_signature Nullable(String)"),
                modify_column_sql: format!("ALTER TABLE {table_name} MODIFY COLUMN transaction_signature Nullable(String)"),
            },
            ClickHouseColumnDefinition {
                name: "lamports".to_string(),
                clickhouse_type: r#"UInt64"#.to_string(),
                add_column_sql: format!("ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS lamports UInt64"),
                modify_column_sql: format!("ALTER TABLE {table_name} MODIFY COLUMN lamports UInt64"),
            },
            ClickHouseColumnDefinition {
                name: "owner".to_string(),
                clickhouse_type: r#"String"#.to_string(),
                add_column_sql: format!("ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS owner String"),
                modify_column_sql: format!("ALTER TABLE {table_name} MODIFY COLUMN owner String"),
            },
            ClickHouseColumnDefinition {
                name: "executable".to_string(),
                clickhouse_type: r#"Bool"#.to_string(),
                add_column_sql: format!("ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS executable Bool"),
                modify_column_sql: format!("ALTER TABLE {table_name} MODIFY COLUMN executable Bool"),
            },
            ClickHouseColumnDefinition {
                name: "rent_epoch".to_string(),
                clickhouse_type: r#"UInt64"#.to_string(),
                add_column_sql: format!("ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS rent_epoch UInt64"),
                modify_column_sql: format!("ALTER TABLE {table_name} MODIFY COLUMN rent_epoch UInt64"),
            },
            ClickHouseColumnDefinition {
                name: "source_name".to_string(),
                clickhouse_type: r#"String"#.to_string(),
                add_column_sql: format!("ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS source_name String"),
                modify_column_sql: format!("ALTER TABLE {table_name} MODIFY COLUMN source_name String"),
            },
            ClickHouseColumnDefinition {
                name: "mode".to_string(),
                clickhouse_type: r#"String"#.to_string(),
                add_column_sql: format!("ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS mode String"),
                modify_column_sql: format!("ALTER TABLE {table_name} MODIFY COLUMN mode String"),
            },
            ClickHouseColumnDefinition {
                name: "decoder_version".to_string(),
                clickhouse_type: r#"String"#.to_string(),
                add_column_sql: format!("ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS decoder_version String"),
                modify_column_sql: format!("ALTER TABLE {table_name} MODIFY COLUMN decoder_version String"),
            },
            ClickHouseColumnDefinition {
                name: "ingest_ts".to_string(),
                clickhouse_type: r#"DateTime64(3, 'UTC')"#.to_string(),
                add_column_sql: format!("ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS ingest_ts DateTime64(3, 'UTC')"),
                modify_column_sql: format!("ALTER TABLE {table_name} MODIFY COLUMN ingest_ts DateTime64(3, 'UTC')"),
            },
            ClickHouseColumnDefinition {
                name: "partition_slot".to_string(),
                clickhouse_type: r#"UInt64"#.to_string(),
                add_column_sql: format!("ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS partition_slot UInt64"),
                modify_column_sql: format!("ALTER TABLE {table_name} MODIFY COLUMN partition_slot UInt64"),
            },
            ClickHouseColumnDefinition {
                name: "m".to_string(),
                clickhouse_type: r#"UInt8"#.to_string(),
                add_column_sql: format!("ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS m UInt8"),
                modify_column_sql: format!("ALTER TABLE {table_name} MODIFY COLUMN m UInt8"),
            },
            ClickHouseColumnDefinition {
                name: "n".to_string(),
                clickhouse_type: r#"UInt8"#.to_string(),
                add_column_sql: format!("ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS n UInt8"),
                modify_column_sql: format!("ALTER TABLE {table_name} MODIFY COLUMN n UInt8"),
            },
            ClickHouseColumnDefinition {
                name: "is_initialized".to_string(),
                clickhouse_type: r#"Bool"#.to_string(),
                add_column_sql: format!("ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS is_initialized Bool"),
                modify_column_sql: format!("ALTER TABLE {table_name} MODIFY COLUMN is_initialized Bool"),
            },
            ClickHouseColumnDefinition {
                name: "signers".to_string(),
                clickhouse_type: r#"Array(String)"#.to_string(),
                add_column_sql: format!("ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS signers Array(String)"),
                modify_column_sql: format!("ALTER TABLE {table_name} MODIFY COLUMN signers Array(String)"),
            },
        ]
    }

    fn clickhouse_engine(table_name: &str) -> String {
        let _ = table_name;
        format!("MergeTree")
    }

    fn clickhouse_engine_name(engine: &str) -> String {
        engine
            .split_once('(')
            .map(|(name, _)| name)
            .unwrap_or(engine)
            .to_string()
    }

    fn create_table_sql_for(
        table_name: &str,
        engine: &str,
        include_merge_tree_clauses: bool,
    ) -> String {
        let merge_tree_clauses = if include_merge_tree_clauses {
            " PARTITION BY partition_slot ORDER BY (program_id, family_name, account_id, slot)"
        } else {
            ""
        };
        format!(
            "CREATE TABLE IF NOT EXISTS {table_name} (\
            program_id String,\
            family_name String,\
            account_type String,\
            account_id String,\
            slot UInt64,\
            pubkey String,\
            transaction_signature Nullable(String),\
            lamports UInt64,\
            owner String,\
            executable Bool,\
            rent_epoch UInt64,\
            source_name String,\
            mode String,\
            decoder_version String,\
            ingest_ts DateTime64(3, 'UTC'),\
            partition_slot UInt64,\
            m UInt8,\
            n UInt8,\
            is_initialized Bool,\
            signers Array(String)\
        ) ENGINE = {engine}{merge_tree_clauses}"
        )
    }
}

impl ClickHouseRow for MultisigAccountClickHouseRow {
    fn table_name(&self) -> &'static str {
        Self::table()
    }

    fn partition_key(&self) -> String {
        self.partition_slot.to_string()
    }
}

fn format_datetime(value: DateTime<Utc>) -> String {
    value.format("%Y-%m-%d %H:%M:%S%.3f").to_string()
}

#[allow(dead_code)]
fn clickhouse_enum_variant<T>(value: &T) -> String
where
    T: serde::Serialize + std::fmt::Debug + ?Sized,
{
    match serde_json::to_value(value) {
        Ok(serde_json::Value::String(variant)) => variant,
        Ok(serde_json::Value::Object(object)) if object.len() == 1 => object
            .into_iter()
            .next()
            .map(|(variant, _)| variant)
            .unwrap_or_default(),
        _ => clickhouse_debug_variant(value),
    }
}

#[allow(dead_code)]
fn clickhouse_debug_variant<T>(value: &T) -> String
where
    T: std::fmt::Debug + ?Sized,
{
    let debug = format!("{value:?}");
    debug
        .split(|ch: char| ch == '(' || ch == '{' || ch.is_whitespace())
        .next()
        .unwrap_or_default()
        .to_string()
}
