//! This code was AUTOGENERATED using the Codama library.

#[allow(unused_imports)]
use carbon_core::clickhouse::rows::clickhouse_enum_variant;
use carbon_core::{
    account::{AccountMetadata, DecodedAccount},
    clickhouse::{
        clickhouse_column_names, clickhouse_create_table_sql, clickhouse_managed_tables,
        clickhouse_migration_operations,
        rows::{
            ClickHouseAccountLandingMetadata, ClickHouseRow, ClickHouseRowContext, ClickHouseTable,
            CLICKHOUSE_ACCOUNT_COMMON_COLUMNS,
        },
        ClickHouseColumnSpec, ClickHouseManagedTable, ClickHouseTableOptions,
    },
};

#[derive(Debug, Clone, serde::Serialize)]
pub struct MultisigAccountClickHouseRow {
    #[serde(flatten)]
    pub metadata: ClickHouseAccountLandingMetadata,
    pub m: u8,
    pub n: u8,
    pub is_initialized: bool,
    pub signers: Vec<String>,
}

impl MultisigAccountClickHouseRow {
    pub const FAMILY_NAME: &'static str = "token_program_multisig_account";
    pub const ACCOUNT_TYPE: &'static str = "multisig";
    pub const DEFAULT_TABLE_NAME: &'static str = "token_program_multisig_account_landing";
    pub const COMMON_COLUMNS: &'static [ClickHouseColumnSpec] = CLICKHOUSE_ACCOUNT_COMMON_COLUMNS;
    pub const PAYLOAD_COLUMNS: &'static [ClickHouseColumnSpec] = &[
        ClickHouseColumnSpec::new("m", r#"UInt8"#),
        ClickHouseColumnSpec::new("n", r#"UInt8"#),
        ClickHouseColumnSpec::new("is_initialized", r#"Bool"#),
        ClickHouseColumnSpec::new("signers", r#"Array(String)"#),
    ];

    pub fn from_parts(
        source: crate::accounts::multisig::Multisig,
        decoded_account: &DecodedAccount<crate::accounts::TokenProgramAccount>,
        metadata: &AccountMetadata,
        context: &ClickHouseRowContext,
    ) -> Self {
        let _ = &source;

        Self {
            metadata: ClickHouseAccountLandingMetadata::new(
                crate::PROGRAM_ID.as_ref(),
                crate::PROGRAM_ID.to_string(),
                Self::FAMILY_NAME,
                Self::ACCOUNT_TYPE,
                decoded_account,
                metadata,
                context,
            ),
            m: source.m,
            n: source.n,
            is_initialized: source.is_initialized,
            signers: source
                .signers
                .iter()
                .map(|value| value.to_string())
                .collect(),
        }
    }

    fn column_specs() -> Vec<ClickHouseColumnSpec> {
        let mut columns = Self::COMMON_COLUMNS.to_vec();
        columns.extend_from_slice(Self::PAYLOAD_COLUMNS);
        columns
    }

    fn table_options() -> ClickHouseTableOptions {
        ClickHouseTableOptions {
            on_cluster_clause: r#""#,
            engine: r#"MergeTree"#.to_string(),
            local_engine: None,
            local_table_suffix: r#"_local"#,
            partition_by: r#"partition_slot"#,
            order_by: r#"(program_id, family_name, account_id, slot)"#,
            ttl_clause: r#""#,
            settings_clause: r#" SETTINGS non_replicated_deduplication_window = 1000"#,
        }
    }

    pub fn migration_operations(table_name: &str) -> Vec<String> {
        let columns = Self::column_specs();
        clickhouse_migration_operations(table_name, &columns, &Self::table_options())
    }

    pub fn managed_tables(table_name: &str) -> Vec<ClickHouseManagedTable> {
        let columns = Self::column_specs();
        clickhouse_managed_tables(table_name, &columns, &Self::table_options())
    }
}

impl ClickHouseTable for MultisigAccountClickHouseRow {
    fn table() -> &'static str {
        Self::DEFAULT_TABLE_NAME
    }

    fn columns() -> Vec<&'static str> {
        let columns = Self::column_specs();
        clickhouse_column_names(&columns)
    }

    fn create_table_sql(table_name: &str) -> String {
        let columns = Self::column_specs();
        let options = Self::table_options();
        clickhouse_create_table_sql(
            table_name,
            &columns,
            &options.engine,
            options.local_engine.is_none(),
            &options,
        )
    }
}

impl ClickHouseRow for MultisigAccountClickHouseRow {
    fn table_name(&self) -> &'static str {
        Self::table()
    }

    fn partition_key(&self) -> String {
        self.metadata.partition_key()
    }
}
