//! This code was AUTOGENERATED using the Codama library.

#[allow(unused_imports)]
use carbon_core::clickhouse::rows::clickhouse_enum_variant;
use carbon_core::{
    account::{AccountMetadata, DecodedAccount},
    clickhouse::{
        clickhouse_column_names, clickhouse_create_table_sql, clickhouse_managed_tables,
        clickhouse_migration_operations,
        rows::{
            ClickHouseAccountLandingMetadata, ClickHouseRow, ClickHouseRowContext, ClickHouseTable,
            CLICKHOUSE_ACCOUNT_COMMON_COLUMNS,
        },
        ClickHouseColumnSpec, ClickHouseManagedTable, ClickHouseTableOptions,
    },
};

#[derive(Debug, Clone, serde::Serialize)]
pub struct TokenAccountClickHouseRow {
    #[serde(flatten)]
    pub metadata: ClickHouseAccountLandingMetadata,
    pub mint: String,
    pub token_owner: String,
    pub amount: u64,
    pub delegate: Option<String>,
    pub state: String,
    pub is_native: Option<u64>,
    pub delegated_amount: u64,
    pub close_authority: Option<String>,
}

impl TokenAccountClickHouseRow {
    pub const FAMILY_NAME: &'static str = "token_program_token_account";
    pub const ACCOUNT_TYPE: &'static str = "token";
    pub const DEFAULT_TABLE_NAME: &'static str = "token_program_token_account_landing";
    pub const COMMON_COLUMNS: &'static [ClickHouseColumnSpec] = CLICKHOUSE_ACCOUNT_COMMON_COLUMNS;
    pub const PAYLOAD_COLUMNS: &'static [ClickHouseColumnSpec] = &[
        ClickHouseColumnSpec::new("mint", r#"String"#),
        ClickHouseColumnSpec::new("token_owner", r#"String"#),
        ClickHouseColumnSpec::new("amount", r#"UInt64"#),
        ClickHouseColumnSpec::new("delegate", r#"Nullable(String)"#),
        ClickHouseColumnSpec::new(
            "state",
            r#"Enum8('Uninitialized' = 0, 'Initialized' = 1, 'Frozen' = 2)"#,
        ),
        ClickHouseColumnSpec::new("is_native", r#"Nullable(UInt64)"#),
        ClickHouseColumnSpec::new("delegated_amount", r#"UInt64"#),
        ClickHouseColumnSpec::new("close_authority", r#"Nullable(String)"#),
    ];

    pub fn from_parts(
        source: crate::accounts::token::Token,
        decoded_account: &DecodedAccount<crate::accounts::TokenProgramAccount>,
        metadata: &AccountMetadata,
        context: &ClickHouseRowContext,
    ) -> Self {
        let _ = &source;

        Self {
            metadata: ClickHouseAccountLandingMetadata::new(
                crate::PROGRAM_ID.as_ref(),
                crate::PROGRAM_ID.to_string(),
                Self::FAMILY_NAME,
                Self::ACCOUNT_TYPE,
                decoded_account,
                metadata,
                context,
            ),
            mint: source.mint.to_string(),
            token_owner: source.owner.to_string(),
            amount: source.amount,
            delegate: source.delegate.as_ref().map(|value| value.to_string()),
            state: clickhouse_enum_variant(&source.state),
            is_native: source.is_native.as_ref().map(|value| *value),
            delegated_amount: source.delegated_amount,
            close_authority: source
                .close_authority
                .as_ref()
                .map(|value| value.to_string()),
        }
    }

    fn column_specs() -> Vec<ClickHouseColumnSpec> {
        let mut columns = Self::COMMON_COLUMNS.to_vec();
        columns.extend_from_slice(Self::PAYLOAD_COLUMNS);
        columns
    }

    fn table_options() -> ClickHouseTableOptions {
        ClickHouseTableOptions {
            on_cluster_clause: r#""#,
            engine: r#"MergeTree"#.to_string(),
            local_engine: None,
            local_table_suffix: r#"_local"#,
            partition_by: r#"partition_slot"#,
            order_by: r#"(program_id, family_name, account_id, slot)"#,
            ttl_clause: r#""#,
            settings_clause: r#""#,
        }
    }

    pub fn migration_operations(table_name: &str) -> Vec<String> {
        let columns = Self::column_specs();
        clickhouse_migration_operations(table_name, &columns, &Self::table_options())
    }

    pub fn managed_tables(table_name: &str) -> Vec<ClickHouseManagedTable> {
        let columns = Self::column_specs();
        clickhouse_managed_tables(table_name, &columns, &Self::table_options())
    }
}

impl ClickHouseTable for TokenAccountClickHouseRow {
    fn table() -> &'static str {
        Self::DEFAULT_TABLE_NAME
    }

    fn columns() -> Vec<&'static str> {
        let columns = Self::column_specs();
        clickhouse_column_names(&columns)
    }

    fn create_table_sql(table_name: &str) -> String {
        let columns = Self::column_specs();
        let options = Self::table_options();
        clickhouse_create_table_sql(
            table_name,
            &columns,
            &options.engine,
            options.local_engine.is_none(),
            &options,
        )
    }
}

impl ClickHouseRow for TokenAccountClickHouseRow {
    fn table_name(&self) -> &'static str {
        Self::table()
    }

    fn partition_key(&self) -> String {
        self.metadata.partition_key()
    }
}
