//! This code was AUTOGENERATED using the Codama library.

#[allow(unused_imports)]
use carbon_core::clickhouse::rows::clickhouse_enum_variant;
use carbon_core::{
    account::{AccountMetadata, DecodedAccount},
    clickhouse::{
        rows::{
            ClickHouseAccountLandingMetadata, ClickHouseRowContext,
            CLICKHOUSE_ACCOUNT_COMMON_COLUMNS,
        },
        ClickHouseColumnSpec,
    },
};

#[derive(Debug, Clone, serde::Serialize)]
pub struct TokenAccountClickHouseRow {
    #[serde(flatten)]
    pub metadata: ClickHouseAccountLandingMetadata,
    pub mint: String,
    pub token_owner: String,
    pub amount: u64,
    pub delegate: Option<String>,
    pub state: String,
    pub is_native: Option<u64>,
    pub delegated_amount: u64,
    pub close_authority: Option<String>,
}

impl TokenAccountClickHouseRow {
    pub const FAMILY_NAME: &'static str = "token_program_token_account";
    pub const ACCOUNT_TYPE: &'static str = "token";
    pub const DEFAULT_TABLE_NAME: &'static str = "token_program_token_account_landing";
    pub const COMMON_COLUMNS: &'static [ClickHouseColumnSpec] = CLICKHOUSE_ACCOUNT_COMMON_COLUMNS;
    pub const PAYLOAD_COLUMNS: &'static [ClickHouseColumnSpec] = &[
        ClickHouseColumnSpec::new("mint", r#"String"#),
        ClickHouseColumnSpec::new("token_owner", r#"String"#),
        ClickHouseColumnSpec::new("amount", r#"UInt64"#),
        ClickHouseColumnSpec::new("delegate", r#"Nullable(String)"#),
        ClickHouseColumnSpec::new(
            "state",
            r#"Enum8('Uninitialized' = 0, 'Initialized' = 1, 'Frozen' = 2)"#,
        ),
        ClickHouseColumnSpec::new("is_native", r#"Nullable(UInt64)"#),
        ClickHouseColumnSpec::new("delegated_amount", r#"UInt64"#),
        ClickHouseColumnSpec::new("close_authority", r#"Nullable(String)"#),
    ];

    pub fn from_parts(
        source: crate::accounts::token::Token,
        decoded_account: &DecodedAccount<crate::accounts::TokenProgramAccount>,
        metadata: &AccountMetadata,
        context: &ClickHouseRowContext,
    ) -> Self {
        let _ = &source;

        Self {
            metadata: ClickHouseAccountLandingMetadata::new(
                crate::PROGRAM_ID.as_ref(),
                crate::PROGRAM_ID.to_string(),
                Self::FAMILY_NAME,
                Self::ACCOUNT_TYPE,
                decoded_account,
                metadata,
                context,
            ),
            mint: source.mint.to_string(),
            token_owner: source.owner.to_string(),
            amount: source.amount,
            delegate: source.delegate.as_ref().map(|value| value.to_string()),
            state: clickhouse_enum_variant(&source.state),
            is_native: source.is_native.as_ref().map(|value| *value),
            delegated_amount: source.delegated_amount,
            close_authority: source
                .close_authority
                .as_ref()
                .map(|value| value.to_string()),
        }
    }
}

carbon_core::impl_clickhouse_account_row!(TokenAccountClickHouseRow);
