//! This code was AUTOGENERATED using the Codama library.
pub mod transaction_row;

pub use self::transaction_row::*;

use std::time::Duration;

use carbon_core::{
    clickhouse::{
        rows::ClickHouseTable, ClickHouseAdmin, ClickHouseConfig, ClickHouseSchema,
        ClickHouseTransactionProcessor,
    },
    error::CarbonResult,
};

pub const DEFAULT_DATABASE: &str = "default";
pub const DEFAULT_SOURCE_NAME: &str = "block_crawler";
pub const DEFAULT_MODE: &str = "backfill";
pub const DEFAULT_DECODER_VERSION: &str = "v1";
pub const DEFAULT_MAX_ROWS: usize = 500;
pub const DEFAULT_FLUSH_INTERVAL_MS: u64 = 1_000;

pub type JupiterSwapClickHouseTransactionProcessor = ClickHouseTransactionProcessor<
    JupiterSwapClickHouseInstructionCollection,
    JupiterSwapTransactionWithClickHouseMetadata,
    JupiterSwapTransactionClickHouseRow,
>;

pub struct JupiterSwapClickHouseTransactionsMigration;

impl ClickHouseSchema for JupiterSwapClickHouseTransactionsMigration {
    fn operations(_config: &ClickHouseConfig) -> Vec<String> {
        vec![JupiterSwapTransactionClickHouseRow::create_table_sql(
            JupiterSwapTransactionClickHouseRow::DEFAULT_TABLE_NAME,
        )]
    }
}

impl JupiterSwapClickHouseTransactionsMigration {
    pub async fn run(config: &ClickHouseConfig) -> CarbonResult<()> {
        ClickHouseAdmin::new(config.clone())
            .execute_schema::<Self>()
            .await
    }
}

pub fn clickhouse_config_from_database_url(database_url: &str) -> CarbonResult<ClickHouseConfig> {
    ClickHouseConfig::from_database_url(
        database_url,
        DEFAULT_DATABASE.to_string(),
        JupiterSwapTransactionClickHouseRow::DEFAULT_TABLE_NAME.to_string(),
        DEFAULT_SOURCE_NAME.to_string(),
        DEFAULT_MODE.to_string(),
        DEFAULT_DECODER_VERSION.to_string(),
        DEFAULT_MAX_ROWS,
        Duration::from_millis(DEFAULT_FLUSH_INTERVAL_MS),
    )
}

pub async fn bootstrap_clickhouse_from_database_url(
    database_url: &str,
) -> CarbonResult<ClickHouseConfig> {
    let config = clickhouse_config_from_database_url(database_url)?;
    JupiterSwapClickHouseTransactionsMigration::run(&config).await?;
    Ok(config)
}

pub fn clickhouse_processor(config: ClickHouseConfig) -> JupiterSwapClickHouseTransactionProcessor {
    ClickHouseTransactionProcessor::new(config)
}

pub async fn setup_clickhouse(
    database_url: &str,
) -> CarbonResult<JupiterSwapClickHouseTransactionProcessor> {
    let config = bootstrap_clickhouse_from_database_url(database_url).await?;
    Ok(clickhouse_processor(config))
}
