//! This code was AUTOGENERATED using the Codama library.
use std::sync::Arc;

use carbon_core::{
    clickhouse::rows::{
        deterministic_transaction_id, ClickHouseRow, ClickHouseRowContext, ClickHouseRows,
        ClickHouseTable,
    },
    collection::InstructionDecoderCollection,
    instruction::{InstructionDecoder, InstructionMetadata},
    transaction::TransactionMetadata,
};
use chrono::{DateTime, Utc};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize)]
pub enum JupiterSwapClickHouseInstructionKind {
    Claim,
    ClaimToken,
    CloseToken,
    CloseWsolTokenAccount,
    CreateTokenAccount,
    CreateTokenLedger,
    ExactOutRoute,
    ExactOutRouteV2,
    Route,
    RouteV2,
    RouteWithTokenLedger,
    SetTokenLedger,
    SharedAccountsExactOutRoute,
    SharedAccountsExactOutRouteV2,
    SharedAccountsRoute,
    SharedAccountsRouteV2,
    SharedAccountsRouteWithTokenLedger,
    BestSwapOutAmountViolationCpiEvent,
    CandidateSwapQuoteErrorCpiEvent,
    CandidateSwapResultsCpiEvent,
    FeeEventCpiEvent,
    SwapEventCpiEvent,
    SwapsEventCpiEvent,
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize)]
pub struct JupiterSwapClickHouseInstructionCollection {
    pub kind: JupiterSwapClickHouseInstructionKind,
}

impl InstructionDecoderCollection for JupiterSwapClickHouseInstructionCollection {
    type InstructionType = JupiterSwapClickHouseInstructionKind;

    fn parse_instruction(instruction: &solana_instruction::Instruction) -> Option<Self> {
        let decoder = crate::JupiterSwapDecoder;
        let decoded = decoder.decode_instruction(instruction)?;
        let kind = match decoded {
            crate::instructions::JupiterSwapInstruction::Claim { .. } => {
                Self::InstructionType::Claim
            }
            crate::instructions::JupiterSwapInstruction::ClaimToken { .. } => {
                Self::InstructionType::ClaimToken
            }
            crate::instructions::JupiterSwapInstruction::CloseToken { .. } => {
                Self::InstructionType::CloseToken
            }
            crate::instructions::JupiterSwapInstruction::CloseWsolTokenAccount { .. } => {
                Self::InstructionType::CloseWsolTokenAccount
            }
            crate::instructions::JupiterSwapInstruction::CreateTokenAccount { .. } => {
                Self::InstructionType::CreateTokenAccount
            }
            crate::instructions::JupiterSwapInstruction::CreateTokenLedger { .. } => {
                Self::InstructionType::CreateTokenLedger
            }
            crate::instructions::JupiterSwapInstruction::ExactOutRoute { .. } => {
                Self::InstructionType::ExactOutRoute
            }
            crate::instructions::JupiterSwapInstruction::ExactOutRouteV2 { .. } => {
                Self::InstructionType::ExactOutRouteV2
            }
            crate::instructions::JupiterSwapInstruction::Route { .. } => {
                Self::InstructionType::Route
            }
            crate::instructions::JupiterSwapInstruction::RouteV2 { .. } => {
                Self::InstructionType::RouteV2
            }
            crate::instructions::JupiterSwapInstruction::RouteWithTokenLedger { .. } => {
                Self::InstructionType::RouteWithTokenLedger
            }
            crate::instructions::JupiterSwapInstruction::SetTokenLedger { .. } => {
                Self::InstructionType::SetTokenLedger
            }
            crate::instructions::JupiterSwapInstruction::SharedAccountsExactOutRoute { .. } => {
                Self::InstructionType::SharedAccountsExactOutRoute
            }
            crate::instructions::JupiterSwapInstruction::SharedAccountsExactOutRouteV2 {
                ..
            } => Self::InstructionType::SharedAccountsExactOutRouteV2,
            crate::instructions::JupiterSwapInstruction::SharedAccountsRoute { .. } => {
                Self::InstructionType::SharedAccountsRoute
            }
            crate::instructions::JupiterSwapInstruction::SharedAccountsRouteV2 { .. } => {
                Self::InstructionType::SharedAccountsRouteV2
            }
            crate::instructions::JupiterSwapInstruction::SharedAccountsRouteWithTokenLedger {
                ..
            } => Self::InstructionType::SharedAccountsRouteWithTokenLedger,
            crate::instructions::JupiterSwapInstruction::CpiEvent { data, .. } => match data {
                crate::instructions::CpiEvent::BestSwapOutAmountViolation(_) => {
                    Self::InstructionType::BestSwapOutAmountViolationCpiEvent
                }
                crate::instructions::CpiEvent::CandidateSwapQuoteError(_) => {
                    Self::InstructionType::CandidateSwapQuoteErrorCpiEvent
                }
                crate::instructions::CpiEvent::CandidateSwapResults(_) => {
                    Self::InstructionType::CandidateSwapResultsCpiEvent
                }
                crate::instructions::CpiEvent::FeeEvent(_) => {
                    Self::InstructionType::FeeEventCpiEvent
                }
                crate::instructions::CpiEvent::SwapEvent(_) => {
                    Self::InstructionType::SwapEventCpiEvent
                }
                crate::instructions::CpiEvent::SwapsEvent(_) => {
                    Self::InstructionType::SwapsEventCpiEvent
                }
            },
        };

        Some(Self { kind })
    }

    fn get_type(&self) -> Self::InstructionType {
        self.kind
    }
}

#[derive(Debug, Clone, serde::Serialize)]
pub struct JupiterSwapTransactionClickHouseRow {
    pub program_id: String,
    pub family_name: String,
    pub transaction_id: String,
    pub scope: String,
    pub slot: u64,
    pub signature: String,
    pub fee_payer: String,
    pub is_vote: bool,
    pub tx_index: Option<u64>,
    pub block_hash: Option<String>,
    pub chain_time: Option<String>,
    pub partition_time: String,
    pub fee: u64,
    pub status_success: bool,
    pub status_error: Option<String>,
    pub compute_units_consumed: Option<u64>,
    pub cost_units: Option<u64>,
    pub decoded_instruction_count: u64,
    pub instruction_kinds: Vec<JupiterSwapClickHouseInstructionKind>,
    pub absolute_paths: Vec<Vec<u8>>,
    pub instruction_indexes: Vec<u32>,
    pub stack_heights: Vec<u32>,
    pub source_name: String,
    pub mode: String,
    pub decoder_version: String,
    pub ingest_ts: String,
}

impl JupiterSwapTransactionClickHouseRow {
    pub const FAMILY_NAME: &'static str = "jupiter_swap_transaction";
    pub const SCOPE: &'static str = "jupiter_swap";
    pub const DEFAULT_TABLE_NAME: &'static str = "jupiter_swap_transaction_landing";

    pub fn from_parts(
        metadata: &TransactionMetadata,
        instructions: &[(
            InstructionMetadata,
            JupiterSwapClickHouseInstructionCollection,
        )],
        context: &ClickHouseRowContext,
    ) -> Self {
        Self::from_parts_with_ingest_ts(metadata, instructions, context, Utc::now())
    }

    pub fn from_parts_with_ingest_ts(
        metadata: &TransactionMetadata,
        instructions: &[(
            InstructionMetadata,
            JupiterSwapClickHouseInstructionCollection,
        )],
        context: &ClickHouseRowContext,
        ingest_ts: DateTime<Utc>,
    ) -> Self {
        let chain_time = metadata
            .block_time
            .and_then(DateTime::<Utc>::from_timestamp_secs);
        let partition_time = chain_time.unwrap_or(ingest_ts);
        let signature = metadata.signature.to_string();
        let (status_success, status_error) = transaction_status_parts(metadata);

        Self {
            program_id: crate::PROGRAM_ID.to_string(),
            family_name: Self::FAMILY_NAME.to_string(),
            transaction_id: deterministic_transaction_id(Self::SCOPE, &signature),
            scope: Self::SCOPE.to_string(),
            slot: metadata.slot,
            signature,
            fee_payer: metadata.fee_payer.to_string(),
            is_vote: metadata.is_vote,
            tx_index: metadata.index,
            block_hash: metadata.block_hash.map(|hash| hash.to_string()),
            chain_time: chain_time.map(format_datetime),
            partition_time: format_datetime(partition_time),
            fee: metadata.meta.fee,
            status_success,
            status_error,
            compute_units_consumed: metadata.meta.compute_units_consumed,
            cost_units: metadata.meta.cost_units,
            decoded_instruction_count: instructions.len() as u64,
            instruction_kinds: instructions
                .iter()
                .map(|(_, decoded)| decoded.kind)
                .collect(),
            absolute_paths: instructions
                .iter()
                .map(|(instruction_metadata, _)| instruction_metadata.absolute_path.clone())
                .collect(),
            instruction_indexes: instructions
                .iter()
                .map(|(instruction_metadata, _)| instruction_metadata.index)
                .collect(),
            stack_heights: instructions
                .iter()
                .map(|(instruction_metadata, _)| instruction_metadata.stack_height)
                .collect(),
            source_name: context.source_name.clone(),
            mode: context.mode.clone(),
            decoder_version: context.decoder_version.clone(),
            ingest_ts: format_datetime(ingest_ts),
        }
    }
}

impl ClickHouseTable for JupiterSwapTransactionClickHouseRow {
    fn table() -> &'static str {
        Self::DEFAULT_TABLE_NAME
    }

    fn columns() -> Vec<&'static str> {
        vec![
            "program_id",
            "family_name",
            "transaction_id",
            "scope",
            "slot",
            "signature",
            "fee_payer",
            "is_vote",
            "tx_index",
            "block_hash",
            "chain_time",
            "partition_time",
            "fee",
            "status_success",
            "status_error",
            "compute_units_consumed",
            "cost_units",
            "decoded_instruction_count",
            "instruction_kinds",
            "absolute_paths",
            "instruction_indexes",
            "stack_heights",
            "source_name",
            "mode",
            "decoder_version",
            "ingest_ts",
        ]
    }

    fn create_table_sql(table_name: &str) -> String {
        format!(
            "CREATE TABLE IF NOT EXISTS {table_name} (\
            program_id String,\
            family_name String,\
            transaction_id String,\
            scope String,\
            slot UInt64,\
            signature String,\
            fee_payer String,\
            is_vote Bool,\
            tx_index Nullable(UInt64),\
            block_hash Nullable(String),\
            chain_time Nullable(DateTime64(3, 'UTC')),\
            partition_time DateTime64(3, 'UTC'),\
            fee UInt64,\
            status_success Bool,\
            status_error Nullable(String),\
            compute_units_consumed Nullable(UInt64),\
            cost_units Nullable(UInt64),\
            decoded_instruction_count UInt64,\
            instruction_kinds Array({}),\
            absolute_paths Array(Array(UInt8)),\
            instruction_indexes Array(UInt32),\
            stack_heights Array(UInt32),\
            source_name String,\
            mode String,\
            decoder_version String,\
            ingest_ts DateTime64(3, 'UTC')\
        ) ENGINE = MergeTree \
        PARTITION BY toYear(partition_time) \
        ORDER BY (program_id, family_name, transaction_id, slot)",
            instruction_kind_clickhouse_type(),
        )
    }
}

impl ClickHouseRow for JupiterSwapTransactionClickHouseRow {
    fn table_name(&self) -> &'static str {
        Self::table()
    }

    fn partition_key(&self) -> String {
        self.partition_time[..4].to_string()
    }
}

pub struct JupiterSwapTransactionWithClickHouseMetadata(
    pub Arc<TransactionMetadata>,
    pub  Vec<(
        InstructionMetadata,
        JupiterSwapClickHouseInstructionCollection,
    )>,
);

impl
    From<(
        Arc<TransactionMetadata>,
        Vec<(
            InstructionMetadata,
            JupiterSwapClickHouseInstructionCollection,
        )>,
    )> for JupiterSwapTransactionWithClickHouseMetadata
{
    fn from(
        value: (
            Arc<TransactionMetadata>,
            Vec<(
                InstructionMetadata,
                JupiterSwapClickHouseInstructionCollection,
            )>,
        ),
    ) -> Self {
        Self(value.0, value.1)
    }
}

impl ClickHouseRows<JupiterSwapTransactionClickHouseRow>
    for JupiterSwapTransactionWithClickHouseMetadata
{
    fn clickhouse_rows(
        &self,
        context: &ClickHouseRowContext,
    ) -> Vec<JupiterSwapTransactionClickHouseRow> {
        let Self(metadata, instructions) = self;
        if instructions.is_empty() {
            return Vec::new();
        }

        vec![JupiterSwapTransactionClickHouseRow::from_parts(
            metadata,
            instructions,
            context,
        )]
    }
}

fn instruction_kind_clickhouse_type() -> &'static str {
    "Enum16('Claim' = 0, 'ClaimToken' = 1, 'CloseToken' = 2, 'CloseWsolTokenAccount' = 3, 'CreateTokenAccount' = 4, 'CreateTokenLedger' = 5, 'ExactOutRoute' = 6, 'ExactOutRouteV2' = 7, 'Route' = 8, 'RouteV2' = 9, 'RouteWithTokenLedger' = 10, 'SetTokenLedger' = 11, 'SharedAccountsExactOutRoute' = 12, 'SharedAccountsExactOutRouteV2' = 13, 'SharedAccountsRoute' = 14, 'SharedAccountsRouteV2' = 15, 'SharedAccountsRouteWithTokenLedger' = 16, 'BestSwapOutAmountViolationCpiEvent' = 17, 'CandidateSwapQuoteErrorCpiEvent' = 18, 'CandidateSwapResultsCpiEvent' = 19, 'FeeEventCpiEvent' = 20, 'SwapEventCpiEvent' = 21, 'SwapsEventCpiEvent' = 22)"
}

fn transaction_status_parts(metadata: &TransactionMetadata) -> (bool, Option<String>) {
    match &metadata.meta.status {
        Ok(()) => (true, None),
        Err(error) => (false, Some(format!("{error:?}"))),
    }
}

fn format_datetime(value: DateTime<Utc>) -> String {
    value.format("%Y-%m-%d %H:%M:%S%.3f").to_string()
}

#[cfg(test)]
mod tests {
    use super::*;
    use carbon_core::transaction::TransactionMetadata;
    use solana_hash::Hash;
    use solana_message::VersionedMessage;
    use solana_signature::Signature;
    use solana_transaction_status::TransactionStatusMeta;

    fn context() -> ClickHouseRowContext {
        ClickHouseRowContext {
            source_name: "block_crawler".to_string(),
            mode: "backfill".to_string(),
            decoder_version: "v1".to_string(),
        }
    }

    fn metadata() -> TransactionMetadata {
        TransactionMetadata {
            slot: 55,
            signature: Signature::new_unique(),
            fee_payer: solana_pubkey::Pubkey::new_unique(),
            meta: TransactionStatusMeta {
                fee: 5000,
                compute_units_consumed: Some(10),
                cost_units: Some(11),
                ..Default::default()
            },
            message: VersionedMessage::Legacy(solana_message::legacy::Message::default()),
            index: Some(11),
            block_time: Some(1_704_067_200),
            block_hash: Some(Hash::new_unique()),
            is_vote: false,
        }
    }

    #[test]
    fn transaction_row_contains_instruction_indexes_without_payloads() {
        let metadata = Arc::new(metadata());
        let instruction_metadata = InstructionMetadata {
            transaction_metadata: Arc::clone(&metadata),
            stack_height: 2,
            index: 3,
            absolute_path: vec![1, 2],
        };
        let wrapper = JupiterSwapTransactionWithClickHouseMetadata(
            metadata,
            vec![(
                instruction_metadata,
                JupiterSwapClickHouseInstructionCollection {
                    kind: JupiterSwapClickHouseInstructionKind::SwapEventCpiEvent,
                },
            )],
        );

        let rows = wrapper.clickhouse_rows(&context());

        assert_eq!(rows.len(), 1);
        assert_eq!(rows[0].decoded_instruction_count, 1);
        assert_eq!(
            rows[0].instruction_kinds,
            vec![JupiterSwapClickHouseInstructionKind::SwapEventCpiEvent]
        );
        assert_eq!(rows[0].absolute_paths, vec![vec![1, 2]]);
        assert_eq!(rows[0].instruction_indexes, vec![3]);
        assert_eq!(rows[0].stack_heights, vec![2]);
        assert_eq!(rows[0].partition_key(), "2024");
    }

    #[test]
    fn transaction_wrapper_skips_rows_without_decoded_jupiter_instructions() {
        let wrapper =
            JupiterSwapTransactionWithClickHouseMetadata(Arc::new(metadata()), Vec::new());

        let rows = wrapper.clickhouse_rows(&context());

        assert!(rows.is_empty());
    }

    #[test]
    fn transaction_ddl_uses_enum16_instruction_kind_array() {
        let sql = JupiterSwapTransactionClickHouseRow::create_table_sql(
            JupiterSwapTransactionClickHouseRow::DEFAULT_TABLE_NAME,
        );

        assert!(sql.contains("instruction_kinds Array(Enum16("));
        assert!(sql.contains("'SwapEventCpiEvent' = 21"));
        assert!(sql.contains("absolute_paths Array(Array(UInt8))"));
    }
}
